/** **************************************************************************************
 * SEMIDRIVE Copyright Statement
 * Copyright (c) SEMIDRIVE. All rights reserved
 *
 * This software and all rights therein are owned by SEMIDRIVE, and are
 * protected by copyright law and other relevant laws, regulations and
 * protection. Without SEMIDRIVE's prior written consent and/or related rights,
 * please do not use this software or any potion thereof in any form or by any
 * means. You may not reproduce, modify or distribute this software except in
 * compliance with the License. Unless required by applicable law or agreed to
 * in writing, software distributed under the License is distributed on
 * an 'AS IS' basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 *****************************************************************************************/
/** **************************************************************************************
 *  \file     Xtrg_Sig.h
 *  \brief    This file contains interface header for CAN MCAL driver, ...
 *
 * <table>
 * <tr><th>Date           <th>Version
 * <tr><td>2023/08/04     <td>1.0.0
 * </table>
 *****************************************************************************************/
#ifndef XTRG_SIG_H
#define XTRG_SIG_H

#ifdef __cplulspluls
extern "C" {
#endif
/*****************************************************************************************
 *                       Include header files
 *****************************************************************************************/
#include "Xtrg_Ip.h"
/*****************************************************************************************
 *                   Global Macro definition
 *****************************************************************************************/
/**
 *  \addtogroup MCAL_XTRG_MACRO Xtrg Macro.
 *
 * This files defines XTRG MCAL macros.
 *  \{
 */
/** \brief Marco for the SIG_i group */
#define ETIMER1_CMP_A1 ETIMER_CMP_A1(0UL)
#define ETIMER1_CMP_B0 ETIMER_CMP_B0(0UL)
#define ETIMER1_CMP_B1 ETIMER_CMP_B1(0UL)
#define ETIMER1_CMP_C0 ETIMER_CMP_C0(0UL)
#define ETIMER1_CMP_C1 ETIMER_CMP_C1(0UL)
#define ETIMER1_CMP_D0 ETIMER_CMP_D0(0UL)
#define ETIMER1_CMP_D1 ETIMER_CMP_D1(0UL)
#define ETIMER2_CMP_A1 ETIMER_CMP_A1(1UL)
#define ETIMER2_CMP_B0 ETIMER_CMP_B0(1UL)
#define ETIMER2_CMP_B1 ETIMER_CMP_B1(1UL)
#define ETIMER2_CMP_C0 ETIMER_CMP_C0(1UL)
#define ETIMER2_CMP_C1 ETIMER_CMP_C1(1UL)
#define ETIMER2_CMP_D0 ETIMER_CMP_D0(1UL)
#define ETIMER2_CMP_D1 ETIMER_CMP_D1(1UL)
#define ETIMER3_CMP_A1 ETIMER_CMP_A1(2UL)
#define ETIMER3_CMP_B0 ETIMER_CMP_B0(2UL)
#define ETIMER3_CMP_B1 ETIMER_CMP_B1(2UL)
#define ETIMER3_CMP_C0 ETIMER_CMP_C0(2UL)
#define ETIMER3_CMP_C1 ETIMER_CMP_C1(2UL)
#define ETIMER3_CMP_D0 ETIMER_CMP_D0(2UL)
#define ETIMER3_CMP_D1 ETIMER_CMP_D1(2UL)
#define ETIMER4_CMP_A1 ETIMER_CMP_A1(3UL)
#define ETIMER4_CMP_B0 ETIMER_CMP_B0(3UL)
#define ETIMER4_CMP_B1 ETIMER_CMP_B1(3UL)
#define ETIMER4_CMP_C0 ETIMER_CMP_C0(3UL)
#define ETIMER4_CMP_C1 ETIMER_CMP_C1(3UL)
#define ETIMER4_CMP_D0 ETIMER_CMP_D0(3UL)
#define ETIMER4_CMP_D1 ETIMER_CMP_D1(3UL)
#define ETIMER1_DIR ETIMER_DIR(0UL)
#define ETIMER2_DIR ETIMER_DIR(1UL)
#define ETIMER3_DIR ETIMER_DIR(2UL)
#define ETIMER4_DIR ETIMER_DIR(3UL)
#define EPWM1_CMP_A1 EPWM_CMP_A1(0UL)
#define EPWM1_CMP_B0 EPWM_CMP_B0(0UL)
#define EPWM1_CMP_B1 EPWM_CMP_B1(0UL)
#define EPWM1_CMP_C0 EPWM_CMP_C0(0UL)
#define EPWM1_CMP_C1 EPWM_CMP_C1(0UL)
#define EPWM1_CMP_D0 EPWM_CMP_D0(0UL)
#define EPWM1_CMP_D1 EPWM_CMP_D1(0UL)
#define EPWM2_CMP_A1 EPWM_CMP_A1(1UL)
#define EPWM2_CMP_B0 EPWM_CMP_B0(1UL)
#define EPWM2_CMP_B1 EPWM_CMP_B1(1UL)
#define EPWM2_CMP_C0 EPWM_CMP_C0(1UL)
#define EPWM2_CMP_C1 EPWM_CMP_C1(1UL)
#define EPWM2_CMP_D0 EPWM_CMP_D0(1UL)
#define EPWM2_CMP_D1 EPWM_CMP_D1(1UL)
#define EPWM3_CMP_A1 EPWM_CMP_A1(2UL)
#define EPWM3_CMP_B0 EPWM_CMP_B0(2UL)
#define EPWM3_CMP_B1 EPWM_CMP_B1(2UL)
#define EPWM3_CMP_C0 EPWM_CMP_C0(2UL)
#define EPWM3_CMP_C1 EPWM_CMP_C1(2UL)
#define EPWM3_CMP_D0 EPWM_CMP_D0(2UL)
#define EPWM3_CMP_D1 EPWM_CMP_D1(2UL)
#define EPWM4_CMP_A1 EPWM_CMP_A1(3UL)
#define EPWM4_CMP_B0 EPWM_CMP_B0(3UL)
#define EPWM4_CMP_B1 EPWM_CMP_B1(3UL)
#define EPWM4_CMP_C0 EPWM_CMP_C0(3UL)
#define EPWM4_CMP_C1 EPWM_CMP_C1(3UL)
#define EPWM4_CMP_D0 EPWM_CMP_D0(3UL)
#define EPWM4_CMP_D1 EPWM_CMP_D1(3UL)
#define ADC_DONE_0 ADC_DONE(0UL)
#define ADC_DONE_1 ADC_DONE(1UL)
#define ADC_DONE_2 ADC_DONE(2UL)
/** \brief Marco for the TRG_i group */
#define ETIMER1_CMP_A0 ETIMER_CMP_A0(0UL)
#define ETIMER2_CMP_A0 ETIMER_CMP_A0(1UL)
#define ETIMER3_CMP_A0 ETIMER_CMP_A0(2UL)
#define ETIMER4_CMP_A0 ETIMER_CMP_A0(3UL)
#define EPWM1_CMP_A0 EPWM_CMP_A0(0UL)
#define EPWM2_CMP_A0 EPWM_CMP_A0(1UL)
#define EPWM3_CMP_A0 EPWM_CMP_A0(2UL)
#define EPWM4_CMP_A0 EPWM_CMP_A0(3UL)
/** \brief Marco for the IO_I group */
#define IO_I_0 IO_I(0UL)
#define IO_I_1 IO_I(1UL)
#define IO_I_2 IO_I(2UL)
#define IO_I_3 IO_I(3UL)
#define IO_I_4 IO_I(4UL)
#define IO_I_5 IO_I(5UL)
#define IO_I_6 IO_I(6UL)
#define IO_I_7 IO_I(7UL)
#define IO_I_8 IO_I(8UL)
#define IO_I_9 IO_I(9UL)
#define IO_I_10 IO_I(10UL)
#define IO_I_11 IO_I(11UL)
#define IO_I_12 IO_I(12UL)
#define IO_I_13 IO_I(13UL)
#define IO_I_14 IO_I(14UL)
#define IO_I_15 IO_I(15UL)
#define IO_I_16 IO_I(16UL)
#define IO_I_17 IO_I(17UL)
#define IO_I_18 IO_I(18UL)
#define IO_I_19 IO_I(19UL)
#define IO_I_20 IO_I(20UL)
#define IO_I_21 IO_I(21UL)
#define IO_I_22 IO_I(22UL)
#define IO_I_23 IO_I(23UL)
#define IO_I_24 IO_I(24UL)
#define IO_I_25 IO_I(25UL)
#define IO_I_26 IO_I(26UL)
#define IO_I_27 IO_I(27UL)
#define IO_I_28 IO_I(28UL)
#define IO_I_29 IO_I(29UL)
#define IO_I_30 IO_I(30UL)
#define IO_I_31 IO_I(31UL)
#define IO_I_32 IO_I(32UL)
#define IO_I_33 IO_I(33UL)
#define IO_I_34 IO_I(34UL)
#define IO_I_35 IO_I(35UL)
#define IO_I_36 IO_I(36UL)
#define IO_I_37 IO_I(37UL)
#define IO_I_38 IO_I(38UL)
#define IO_I_39 IO_I(39UL)
#define IO_I_40 IO_I(40UL)
#define IO_I_41 IO_I(41UL)
#define IO_I_42 IO_I(42UL)
#define IO_I_43 IO_I(43UL)
#define IO_I_44 IO_I(44UL)
#define IO_I_45 IO_I(45UL)
#define IO_I_46 IO_I(46UL)
#define IO_I_47 IO_I(47UL)
#define IO_I_48 IO_I(48UL)
#define IO_I_49 IO_I(49UL)
#define IO_I_50 IO_I(50UL)
#define IO_I_51 IO_I(51UL)
#define IO_I_52 IO_I(52UL)
#define IO_I_53 IO_I(53UL)
#define IO_I_54 IO_I(54UL)
#define IO_I_55 IO_I(55UL)
#define IO_I_56 IO_I(56UL)
#define IO_I_57 IO_I(57UL)
#define IO_I_58 IO_I(58UL)
#define IO_I_59 IO_I(59UL)
#define IO_I_60 IO_I(60UL)
#define IO_I_61 IO_I(61UL)
#define IO_I_62 IO_I(62UL)
#define IO_I_63 IO_I(63UL)
/** \brief Marco for the IO_O group */
#define IO_O_0 IO_O(0UL)
#define IO_O_1 IO_O(1UL)
#define IO_O_2 IO_O(2UL)
#define IO_O_3 IO_O(3UL)
#define IO_O_4 IO_O(4UL)
#define IO_O_5 IO_O(5UL)
#define IO_O_6 IO_O(6UL)
#define IO_O_7 IO_O(7UL)
#define IO_O_8 IO_O(8UL)
#define IO_O_9 IO_O(9UL)
#define IO_O_10 IO_O(10UL)
#define IO_O_11 IO_O(11UL)
#define IO_O_12 IO_O(12UL)
#define IO_O_13 IO_O(13UL)
#define IO_O_14 IO_O(14UL)
#define IO_O_15 IO_O(15UL)
#define IO_O_16 IO_O(16UL)
#define IO_O_17 IO_O(17UL)
#define IO_O_18 IO_O(18UL)
#define IO_O_19 IO_O(19UL)
#define IO_O_20 IO_O(20UL)
#define IO_O_21 IO_O(21UL)
#define IO_O_22 IO_O(22UL)
#define IO_O_23 IO_O(23UL)
#define IO_O_24 IO_O(24UL)
#define IO_O_25 IO_O(25UL)
#define IO_O_26 IO_O(26UL)
#define IO_O_27 IO_O(27UL)
#define IO_O_28 IO_O(28UL)
#define IO_O_29 IO_O(29UL)
#define IO_O_30 IO_O(30UL)
#define IO_O_31 IO_O(31UL)
#define IO_O_32 IO_O(32UL)
#define IO_O_33 IO_O(33UL)
#define IO_O_34 IO_O(34UL)
#define IO_O_35 IO_O(35UL)
#define IO_O_36 IO_O(36UL)
#define IO_O_37 IO_O(37UL)
#define IO_O_38 IO_O(38UL)
#define IO_O_39 IO_O(39UL)
#define IO_O_40 IO_O(40UL)
#define IO_O_41 IO_O(41UL)
#define IO_O_42 IO_O(42UL)
#define IO_O_43 IO_O(43UL)
#define IO_O_44 IO_O(44UL)
#define IO_O_45 IO_O(45UL)
#define IO_O_46 IO_O(46UL)
#define IO_O_47 IO_O(47UL)
#define IO_O_48 IO_O(48UL)
#define IO_O_49 IO_O(49UL)
#define IO_O_50 IO_O(50UL)
#define IO_O_51 IO_O(51UL)
#define IO_O_52 IO_O(52UL)
#define IO_O_53 IO_O(53UL)
#define IO_O_54 IO_O(54UL)
#define IO_O_55 IO_O(55UL)
#define IO_O_56 IO_O(56UL)
#define IO_O_57 IO_O(57UL)
#define IO_O_58 IO_O(58UL)
#define IO_O_59 IO_O(59UL)
#define IO_O_60 IO_O(60UL)
#define IO_O_61 IO_O(61UL)
#define IO_O_62 IO_O(62UL)
#define IO_O_63 IO_O(63UL)
/** \brief Marco for the SIG_o group */
#define ETIMER1_CPT_A0 ETIMER_CPT0(0UL, 0UL)
#define ETIMER1_CPT_A1 ETIMER_CPT0(0UL, 1UL)
#define ETIMER1_CPT_B0 ETIMER_CPT0(0UL, 2UL)
#define ETIMER1_CPT_B1 ETIMER_CPT0(0UL, 3UL)
#define ETIMER1_CPT_C0 ETIMER_CPT0(0UL, 4UL)
#define ETIMER1_CPT_C1 ETIMER_CPT0(0UL, 5UL)
#define ETIMER1_CPT_D0 ETIMER_CPT0(0UL, 6UL)
#define ETIMER1_CPT_D1 ETIMER_CPT0(0UL, 7UL)
#define ETIMER2_CPT_A0 ETIMER_CPT0(1UL, 0UL)
#define ETIMER2_CPT_A1 ETIMER_CPT0(1UL, 1UL)
#define ETIMER2_CPT_B0 ETIMER_CPT0(1UL, 2UL)
#define ETIMER2_CPT_B1 ETIMER_CPT0(1UL, 3UL)
#define ETIMER2_CPT_C0 ETIMER_CPT0(1UL, 4UL)
#define ETIMER2_CPT_C1 ETIMER_CPT0(1UL, 5UL)
#define ETIMER2_CPT_D0 ETIMER_CPT0(1UL, 6UL)
#define ETIMER2_CPT_D1 ETIMER_CPT0(1UL, 7UL)
#define ETIMER3_CPT_A0 ETIMER_CPT0(2UL, 0UL)
#define ETIMER3_CPT_A1 ETIMER_CPT0(2UL, 1UL)
#define ETIMER3_CPT_B0 ETIMER_CPT0(2UL, 2UL)
#define ETIMER3_CPT_B1 ETIMER_CPT0(2UL, 3UL)
#define ETIMER3_CPT_C0 ETIMER_CPT0(2UL, 4UL)
#define ETIMER3_CPT_C1 ETIMER_CPT0(2UL, 5UL)
#define ETIMER3_CPT_D0 ETIMER_CPT0(2UL, 6UL)
#define ETIMER3_CPT_D1 ETIMER_CPT0(2UL, 7UL)
#define ETIMER4_CPT_A0 ETIMER_CPT0(3UL, 0UL)
#define ETIMER4_CPT_A1 ETIMER_CPT0(3UL, 1UL)
#define ETIMER4_CPT_B0 ETIMER_CPT0(3UL, 2UL)
#define ETIMER4_CPT_B1 ETIMER_CPT0(3UL, 3UL)
#define ETIMER4_CPT_C0 ETIMER_CPT0(3UL, 4UL)
#define ETIMER4_CPT_C1 ETIMER_CPT0(3UL, 5UL)
#define ETIMER4_CPT_D0 ETIMER_CPT0(3UL, 6UL)
#define ETIMER4_CPT_D1 ETIMER_CPT0(3UL, 7UL)
#define ETIMER1_FAULT_0 ETIMER_FAULT(0UL, 0UL)
#define ETIMER1_FAULT_1 ETIMER_FAULT(0UL, 1UL)
#define ETIMER1_FAULT_2 ETIMER_FAULT(0UL, 2UL)
#define ETIMER1_FAULT_3 ETIMER_FAULT(0UL, 3UL)
#define ETIMER2_FAULT_0 ETIMER_FAULT(1UL, 0UL)
#define ETIMER2_FAULT_1 ETIMER_FAULT(1UL, 1UL)
#define ETIMER2_FAULT_2 ETIMER_FAULT(1UL, 2UL)
#define ETIMER2_FAULT_3 ETIMER_FAULT(1UL, 3UL)
#define ETIMER3_FAULT_0 ETIMER_FAULT(2UL, 0UL)
#define ETIMER3_FAULT_1 ETIMER_FAULT(2UL, 1UL)
#define ETIMER3_FAULT_2 ETIMER_FAULT(2UL, 2UL)
#define ETIMER3_FAULT_3 ETIMER_FAULT(2UL, 3UL)
#define ETIMER4_FAULT_0 ETIMER_FAULT(3UL, 0UL)
#define ETIMER4_FAULT_1 ETIMER_FAULT(3UL, 1UL)
#define ETIMER4_FAULT_2 ETIMER_FAULT(3UL, 2UL)
#define ETIMER4_FAULT_3 ETIMER_FAULT(3UL, 3UL)
#define ETIMER1_CLK ETIMER_CLK(0UL)
#define ETIMER2_CLK ETIMER_CLK(1UL)
#define ETIMER3_CLK ETIMER_CLK(2UL)
#define ETIMER4_CLK ETIMER_CLK(3UL)
#define EPWM1_FAULT_0 EPWM_FAULT(0UL, 0UL)
#define EPWM1_FAULT_1 EPWM_FAULT(0UL, 1UL)
#define EPWM1_FAULT_2 EPWM_FAULT(0UL, 2UL)
#define EPWM1_FAULT_3 EPWM_FAULT(0UL, 3UL)
#define EPWM2_FAULT_0 EPWM_FAULT(1UL, 0UL)
#define EPWM2_FAULT_1 EPWM_FAULT(1UL, 1UL)
#define EPWM2_FAULT_2 EPWM_FAULT(1UL, 2UL)
#define EPWM2_FAULT_3 EPWM_FAULT(1UL, 3UL)
#define EPWM3_FAULT_0 EPWM_FAULT(2UL, 0UL)
#define EPWM3_FAULT_1 EPWM_FAULT(2UL, 1UL)
#define EPWM3_FAULT_2 EPWM_FAULT(2UL, 2UL)
#define EPWM3_FAULT_3 EPWM_FAULT(2UL, 3UL)
#define EPWM4_FAULT_0 EPWM_FAULT(3UL, 0UL)
#define EPWM4_FAULT_1 EPWM_FAULT(3UL, 1UL)
#define EPWM4_FAULT_2 EPWM_FAULT(3UL, 2UL)
#define EPWM4_FAULT_3 EPWM_FAULT(3UL, 3UL)
#define EPWM1_CLK EPWM_CLK(0UL)
#define EPWM2_CLK EPWM_CLK(1UL)
#define EPWM3_CLK EPWM_CLK(2UL)
#define EPWM4_CLK EPWM_CLK(3UL)
/** \brief Marco for the SWT_i group */
#define XTRG_SWT_0 XTRG_SWT(0UL)
#define XTRG_SWT_1 XTRG_SWT(1UL)
#define XTRG_SWT_2 XTRG_SWT(2UL)
#define XTRG_SWT_3 XTRG_SWT(3UL)
#define XTRG_SWT_4 XTRG_SWT(4UL)
#define XTRG_SWT_5 XTRG_SWT(5UL)
#define XTRG_SWT_6 XTRG_SWT(6UL)
#define XTRG_SWT_7 XTRG_SWT(7UL)
/** \brief Marco for the SSIG group */
#define SSIG_0 SSIG(0UL)
#define SSIG_1 SSIG(1UL)
#define SSIG_2 SSIG(2UL)
#define SSIG_3 SSIG(3UL)
#define SSIG_4 SSIG(4UL)
#define SSIG_5 SSIG(5UL)
#define SSIG_6 SSIG(6UL)
#define SSIG_7 SSIG(7UL)
#define SSIG_8 SSIG(8UL)
#define SSIG_9 SSIG(9UL)
#define SSIG_10 SSIG(10UL)
#define SSIG_11 SSIG(11UL)
#define SSIG_12 SSIG(12UL)
#define SSIG_13 SSIG(13UL)
#define SSIG_14 SSIG(14UL)
#define SSIG_15 SSIG(15UL)
/** \brief Marco for the SYNC_i group */
#define ETIMER1_SNAP_SHOT_I ETIMER_SNAP_SHOT_I(0UL)
#define ETIMER2_SNAP_SHOT_I ETIMER_SNAP_SHOT_I(1UL)
#define ETIMER3_SNAP_SHOT_I ETIMER_SNAP_SHOT_I(2UL)
#define ETIMER4_SNAP_SHOT_I ETIMER_SNAP_SHOT_I(3UL)
#define ETIMER1_SET_I ETIMER_SET_I(0UL)
#define ETIMER2_SET_I ETIMER_SET_I(1UL)
#define ETIMER3_SET_I ETIMER_SET_I(2UL)
#define ETIMER4_SET_I ETIMER_SET_I(3UL)
#define ETIMER1_CLR_I ETIMER_CLR_I(0UL)
#define ETIMER2_CLR_I ETIMER_CLR_I(1UL)
#define ETIMER3_CLR_I ETIMER_CLR_I(2UL)
#define ETIMER4_CLR_I ETIMER_CLR_I(3UL)
#define EPWM1_SET_I EPWM_SET_I(0UL)
#define EPWM2_SET_I EPWM_SET_I(1UL)
#define EPWM3_SET_I EPWM_SET_I(2UL)
#define EPWM4_SET_I EPWM_SET_I(3UL)
#define EPWM1_CLR_I EPWM_CLR_I(0UL)
#define EPWM2_CLR_I EPWM_CLR_I(1UL)
#define EPWM3_CLR_I EPWM_CLR_I(2UL)
#define EPWM4_CLR_I EPWM_CLR_I(3UL)
/** \brief Marco for the SYNC_o group */
#define ETIMER1_SNAP_SHOT_O ETIMER_SNAP_SHOT_O(0UL)
#define ETIMER2_SNAP_SHOT_O ETIMER_SNAP_SHOT_O(1UL)
#define ETIMER3_SNAP_SHOT_O ETIMER_SNAP_SHOT_O(2UL)
#define ETIMER4_SNAP_SHOT_O ETIMER_SNAP_SHOT_O(3UL)
#define ETIMER1_SET_O ETIMER_SET_O(0UL)
#define ETIMER2_SET_O ETIMER_SET_O(1UL)
#define ETIMER3_SET_O ETIMER_SET_O(2UL)
#define ETIMER4_SET_O ETIMER_SET_O(3UL)
#define ETIMER1_CLR_O ETIMER_CLR_O(0UL)
#define ETIMER2_CLR_O ETIMER_CLR_O(1UL)
#define ETIMER3_CLR_O ETIMER_CLR_O(2UL)
#define ETIMER4_CLR_O ETIMER_CLR_O(3UL)
#define EPWM1_SET_O EPWM_SET_O(0UL)
#define EPWM2_SET_O EPWM_SET_O(1UL)
#define EPWM3_SET_O EPWM_SET_O(2UL)
#define EPWM4_SET_O EPWM_SET_O(3UL)
#define EPWM1_CLR_O EPWM_CLR_O(0UL)
#define EPWM2_CLR_O EPWM_CLR_O(1UL)
#define EPWM3_CLR_O EPWM_CLR_O(2UL)
#define EPWM4_CLR_O EPWM_CLR_O(3UL)
/** \} */

#ifdef __cplulspluls
}
#endif
#endif /* XTRG_SIG_H */
/* End of file */

