/**
*   @file ComStack_Cfg.h
*   @brief AUTOSAR Base - type definition of the PduIdType and PduLengthType.
*   @details AUTOSAR type definition of the PduIdType and PduLengthType. shall be generated by
*            the generator of EcuC Virtual Layer
*            This file contains sample code only. It is not part of the production code deliverables
*/

/********************************************************
 *        Copyright(c) 2020    Semidrive                *
 *        All rights reserved.                          *
 ********************************************************/

/*==================================================================================================
==================================================================================================*/
#ifndef COMSTACK_CFG_H
#define COMSTACK_CFG_H

#ifdef __cplusplus
extern "C" {
#endif
/* Version and Check Begin */
/* Version Info Begin */
#define COMSTACK_CFG_H_VENDOR_ID    0x8C
#define COMSTACK_CFG_H_AR_RELEASE_MAJOR_VERSION    4
#define COMSTACK_CFG_H_AR_RELEASE_MINOR_VERSION    3
#define COMSTACK_CFG_H_AR_RELEASE_REVISION_VERSION 1
#define COMSTACK_CFG_H_SW_MAJOR_VERSION    1
#define COMSTACK_CFG_H_SW_MINOR_VERSION    0
#define COMSTACK_CFG_H_SW_PATCH_VERSION    0
/* Version Info End */
/* Version and Check End */

/**
* @brief   This type serve as a unique identifier of a PDU within a software module.
*          Allowed ranges: uint8 .. uint16
* @implements PduIdType_type
*/
typedef uint16       PduIdType;

/**
* @brief   This type serve as length information of a PDU in bytes.
*          Allowed ranges: uint8 .. uint32
* @implements PduLengthType_Type
*/
typedef uint32       PduLengthType;

#ifdef __cplusplus
}
#endif

#endif /* COMSTACK_CFG_H */
