/*
* SEMIDRIVE Copyright Statement
* Copyright (c) SEMIDRIVE. All rights reserved
*
* This software and all rights therein are owned by SEMIDRIVE, and are
* protected by copyright law and other relevant laws, regulations and
* protection. Without SEMIDRIVE's prior written consent and/or related rights,
* please do not use this software or any potion thereof in any form or by any
* means. You may not reproduce, modify or distribute this software except in
* compliance with the License. Unless required by applicable law or agreed to
* in writing, software distributed under the License is distributed on
* an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
*
* You should have received a copy of the License along with this program.
* If not, see <http://www.semidrive.com/licenses/>.
*/

#ifndef _CK_INDEX_H_
#define _CK_INDEX_H_

#define CKGEN_CKGEN_FAB_AP_APMAINCLK_CG                                0
#define CKGEN_CKGEN_FAB_AP_DISPCLK_CG                                  1
#define CKGEN_CKGEN_FAB_AP_HSMPERCLK_CG                                3
#define CKGEN_CKGEN_FAB_AP_PERCLK_CG                                   2
#define CKGEN_CKGEN_FAB_AP_SDRAMCLK_CG                                 4
#define CKGEN_CKGEN_FAB_DISP_MAINCLK_CG                                5
#define CKGEN_CKGEN_FAB_DISP_PERCLK_CG                                 6
#define CKGEN_AP_MAC_PCLK_CG                                           20
#define CKGEN_APBMUX6_PCLK_CG                                          6
#define CKGEN_APBMUX7_PCLK_CG                                          52
#define CKGEN_CSI_AXI_CLK_CG                                           48
#define CKGEN_CSI_I_PCLK_CG                                            51
#define CKGEN_CSI_PROC_CLK_CG                                          55
#define CKGEN_DC_AXI_CLK_CG                                            49
#define CKGEN_DC_DSP_CLK_CG                                            59
#define CKGEN_DC_PIX_CLK_CG                                            54
#define CKGEN_DISP_MUX_DISP_CKGEN_PIX_CLK_CG                           56
#define CKGEN_DISP_MUX_PCLK_CG                                         53
#define CKGEN_DMA_AP_ACLK_CG                                           3
#define CKGEN_DMA_AP_CLK_CG                                            2
#define CKGEN_DMA_AP_HCLK_CG                                           4
#define CKGEN_DMA_AP_PCLK_CG                                           19
#define CKGEN_G2D_AXI_CLK_CG                                           50
#define CKGEN_GPIO_AP_PCLK_CG                                          8
#define CKGEN_IOMUXC_AP_PCLK_CG                                        9
#define CKGEN_LVDS_CH0_CLK_X14_CG                                      57
#define CKGEN_LVDS_CH0_CLK_X7_CG                                       58
#define CKGEN_POR_AP_I_PCLK_CG                                         24
#define CKGEN_PT_SNS_AP_CLKIN_CG                                       41
#define CKGEN_PT_SNS_AP_I_PCLK_CG                                      22
#define CKGEN_RSTGEN_AP_PCLK_CG                                        14
#define CKGEN_SACI1_EXT_CLK_CG                                         33
#define CKGEN_SACI1_I2S_MCLK_CG                                        31
#define CKGEN_SACI1_I2S_RX_CLK_CG                                      37
#define CKGEN_SACI1_I2S_TX_CLK_CG                                      35
#define CKGEN_SACI1_PCLK_CG                                            17
#define CKGEN_SACI1_PDM_PER_CLK_CG                                     39
#define CKGEN_SACI2_EXT_CLK_CG                                         34
#define CKGEN_SACI2_I2S_MCLK_CG                                        32
#define CKGEN_SACI2_I2S_RX_CLK_CG                                      38
#define CKGEN_SACI2_I2S_TX_CLK_CG                                      36
#define CKGEN_SACI2_PCLK_CG                                            18
#define CKGEN_SACI2_PDM_PER_CLK_CG                                     40
#define CKGEN_SCR_AP_I_PCLK_CG                                         23
#define CKGEN_SDRAM_ACLK_CG                                            28
#define CKGEN_SDRAMC_SDRAMC_PCLK_CG                                    7
#define CKGEN_SEHC1_ACLK_CG                                            0
#define CKGEN_SEHC1_CQE_SQS_CLK_CG                                     44
#define CKGEN_SEHC1_MAIN_CLK_CG                                        29
#define CKGEN_SEHC1_PCLK_CG                                            12
#define CKGEN_SEHC1_TM_CLK_CG                                          46
#define CKGEN_SEHC2_ACLK_CG                                            1
#define CKGEN_SEHC2_CQE_SQS_CLK_CG                                     45
#define CKGEN_SEHC2_MAIN_CLK_CG                                        30
#define CKGEN_SEHC2_PCLK_CG                                            13
#define CKGEN_SEHC2_TM_CLK_CG                                          47
#define CKGEN_SEIP_HCLK_CG                                             26
#define CKGEN_SEIP_I_FD_REF_CLK_CG                                     27
#define CKGEN_SEIP_I_PCLK_CG                                           25
#define CKGEN_SEIP_SH_CLK_CG                                           5
#define CKGEN_U_CKGEN_AP_PCLK_CG                                       10
#define CKGEN_USB2_PCLK_CG                                             11
#define CKGEN_USB_I_PHY_REF_CLK_CG                                     42
#define CKGEN_VD_AP_I_PCLK_CG                                          21
#define CKGEN_WDT8_BUS_CLK_CG                                          16
#define CKGEN_WDT8_MAIN_CLK_CG                                         43
#define CKGEN_WDT8_PCLK_CG                                             15
#define CKGEN_FAB_SF_CR5SFCLK_CG                                       2
#define CKGEN_FAB_SF_CR5SXCLK_CG                                       0
#define CKGEN_FAB_SF_MAINCLK_CG                                        4
#define CKGEN_FAB_SF_PERCLK_CG                                         5
#define CKGEN_FAB_SF_XSPI1ACLK_CG                                      7
#define CKGEN_FAB_SF_XSPI1BCLK_CG                                      8
#define CKGEN_FAB_SF_XSPI2ACLK_CG                                      9
#define CKGEN_FAB_SF_XSPI2BCLK_CG                                      10
#define CKGEN_FAB_SP_CR5SPCLK_CG                                       11
#define CKGEN_FAB_SP_MAINCLK_CG                                        12
#define CKGEN_FAB_SP_PERCLK_CG                                         14
#define CKGEN_FAB_SP_SFMAINCLK_CG                                      13
#define CKGEN_FAB_SX_MAINCLK_CG                                        1
#define CKGEN_FAB_SX_SFMAINCLK_CG                                      3
#define CKGEN_FAB_SX_SFPERCLK_CG                                       6
#define CKGEN_CR5_SF_CLKIN_CG                                          2
#define CKGEN_CR5_SP0_CLKIN_CG                                         3
#define CKGEN_CR5_SP1_CLKIN_CG                                         4
#define CKGEN_CR5_SX0_CLKIN_CG                                         0
#define CKGEN_CR5_SX1_CLKIN_CG                                         1
#define CKGEN_AAHB_SPSF_MST_SLVCLK_CG                                  155
#define CKGEN_ACMP1_CTRL_CLK_CG                                        248
#define CKGEN_ACMP1_PCLK_CG                                            128
#define CKGEN_ACMP2_CTRL_CLK_CG                                        249
#define CKGEN_ACMP2_PCLK_CG                                            129
#define CKGEN_ACMP3_CTRL_CLK_CG                                        250
#define CKGEN_ACMP3_PCLK_CG                130
#define CKGEN_ACMP4_CTRL_CLK_CG                251
#define CKGEN_ACMP4_PCLK_CG                131
#define CKGEN_ADMA_ETH1_DMACLK_CG                151
#define CKGEN_ADMA_ETH1_PERCLK_CG                318
#define CKGEN_ADMA_ETH2_DMACLK_CG                152
#define CKGEN_ADMA_ETH2_PERCLK_CG                319
#define CKGEN_AHB_syncup_GAMA1_MAINCLK_CG                307
#define CKGEN_APB_CR5SF_DBG_SLV_SRC_PCLK_CG                327
#define CKGEN_APB_CR5SX0_DBG_SLV_SRC_PCLK_CG                325
#define CKGEN_APB_CR5SX1_DBG_SLV_SRC_PCLK_CG                326
#define CKGEN_APB_MAC_AP_SLV_SRC_PCLK_CG                126
#define CKGEN_APB_MAC_SP_SLV_SRC_PCLK_CG                125
#define CKGEN_APB_CKGEN_SEIP_NVM_mst_dst_PCLK_CG                146
#define CKGEN_APBMUX2_PCLK_CG                113
#define CKGEN_APBMUX2_SF_PCLK_CG                116
#define CKGEN_APBMUX3_PCLK_CG                114
#define CKGEN_APBMUX4_PCLK_CG                115
#define CKGEN_APBMUX5_PCLK_CG                314
#define CKGEN_BTI_SF_AHB_HCLK_CG                154
#define CKGEN_BTM1_I_PCLK_CG                136
#define CKGEN_BTM1_I_XTAL24MHZ_CLK_CG                292
#define CKGEN_BTM2_I_PCLK_CG                137
#define CKGEN_BTM2_I_XTAL24MHZ_CLK_CG                293
#define CKGEN_BTM3_I_PCLK_CG                138
#define CKGEN_BTM3_I_XTAL24MHZ_CLK_CG                294
#define CKGEN_BTM4_I_PCLK_CG                139
#define CKGEN_BTM4_I_XTAL24MHZ_CLK_CG                295
#define CKGEN_BTM5_I_PCLK_CG                140
#define CKGEN_BTM5_I_XTAL24MHZ_CLK_CG                296
#define CKGEN_BTM6_I_PCLK_CG                141
#define CKGEN_BTM6_I_XTAL24MHZ_CLK_CG                297
#define CKGEN_CANFD10_CLK24M_CG                267
#define CKGEN_CANFD10_IPG_CLK_PE_CG                230
#define CKGEN_CANFD10_PCLK_CG                58
#define CKGEN_CANFD11_CLK24M_CG                268
#define CKGEN_CANFD11_IPG_CLK_PE_CG                231
#define CKGEN_CANFD11_PCLK_CG                59
#define CKGEN_CANFD12_CLK24M_CG                269
#define CKGEN_CANFD12_IPG_CLK_PE_CG                232
#define CKGEN_CANFD12_PCLK_CG                60
#define CKGEN_CANFD13_CLK24M_CG                270
#define CKGEN_CANFD13_IPG_CLK_PE_CG                233
#define CKGEN_CANFD13_PCLK_CG                61
#define CKGEN_CANFD14_CLK24M_CG                271
#define CKGEN_CANFD14_IPG_CLK_PE_CG                234
#define CKGEN_CANFD14_PCLK_CG                62
#define CKGEN_CANFD15_CLK24M_CG                272
#define CKGEN_CANFD15_IPG_CLK_PE_CG                235
#define CKGEN_CANFD15_PCLK_CG                63
#define CKGEN_CANFD16_CLK24M_CG                273
#define CKGEN_CANFD16_IPG_CLK_PE_CG                236
#define CKGEN_CANFD16_PCLK_CG                64
#define CKGEN_CANFD17_CLK24M_CG                274
#define CKGEN_CANFD17_IPG_CLK_PE_CG                237
#define CKGEN_CANFD17_PCLK_CG                65
#define CKGEN_CANFD18_CLK24M_CG                275
#define CKGEN_CANFD18_IPG_CLK_PE_CG                238
#define CKGEN_CANFD18_PCLK_CG                66
#define CKGEN_CANFD19_CLK24M_CG                276
#define CKGEN_CANFD19_IPG_CLK_PE_CG                239
#define CKGEN_CANFD19_PCLK_CG                67
#define CKGEN_CANFD1_CLK24M_CG                258
#define CKGEN_CANFD1_IPG_CLK_PE_CG                221
#define CKGEN_CANFD1_PCLK_CG                49
#define CKGEN_CANFD20_CLK24M_CG                277
#define CKGEN_CANFD20_IPG_CLK_PE_CG                240
#define CKGEN_CANFD20_PCLK_CG                68
#define CKGEN_CANFD21_CLK24M_CG                278
#define CKGEN_CANFD21_IPG_CLK_PE_CG                241
#define CKGEN_CANFD21_PCLK_CG                69
#define CKGEN_CANFD22_CLK24M_CG                279
#define CKGEN_CANFD22_IPG_CLK_PE_CG                242
#define CKGEN_CANFD22_PCLK_CG                70
#define CKGEN_CANFD23_CLK24M_CG                280
#define CKGEN_CANFD23_IPG_CLK_PE_CG                243
#define CKGEN_CANFD23_PCLK_CG                71
#define CKGEN_CANFD24_CLK24M_CG                281
#define CKGEN_CANFD24_IPG_CLK_PE_CG                244
#define CKGEN_CANFD24_PCLK_CG                72
#define CKGEN_CANFD2_CLK24M_CG                259
#define CKGEN_CANFD2_IPG_CLK_PE_CG                222
#define CKGEN_CANFD2_PCLK_CG                50
#define CKGEN_CANFD3_CLK24M_CG                260
#define CKGEN_CANFD3_IPG_CLK_PE_CG                223
#define CKGEN_CANFD3_PCLK_CG                51
#define CKGEN_CANFD4_CLK24M_CG                261
#define CKGEN_CANFD4_IPG_CLK_PE_CG                224
#define CKGEN_CANFD4_PCLK_CG                52
#define CKGEN_CANFD5_CLK24M_CG                262
#define CKGEN_CANFD5_IPG_CLK_PE_CG                225
#define CKGEN_CANFD5_PCLK_CG                53
#define CKGEN_CANFD6_CLK24M_CG                263
#define CKGEN_CANFD6_IPG_CLK_PE_CG                226
#define CKGEN_CANFD6_PCLK_CG                54
#define CKGEN_CANFD7_CLK24M_CG                264
#define CKGEN_CANFD7_IPG_CLK_PE_CG                227
#define CKGEN_CANFD7_PCLK_CG                55
#define CKGEN_CANFD8_CLK24M_CG                265
#define CKGEN_CANFD8_IPG_CLK_PE_CG                228
#define CKGEN_CANFD8_PCLK_CG                56
#define CKGEN_CANFD9_CLK24M_CG                266
#define CKGEN_CANFD9_IPG_CLK_PE_CG                229
#define CKGEN_CANFD9_PCLK_CG                57
#define CKGEN_CR5_SP_MIX_MAC_PCLK_CG                321
#define CKGEN_CSLITE_PCLKDBG_CG                323
#define CKGEN_CSLITE_PCLKSYS_CG                324
#define CKGEN_DCDC1_CLK_24M_CG                284
#define CKGEN_DMA_SF_ACLK0_CG                11
#define CKGEN_DMA_SF_ACLK1_CG                12
#define CKGEN_DMA_SF_CLK0_CG                9
#define CKGEN_DMA_SF_CLK1_CG                10
#define CKGEN_DMA_SF_HCLK0_CG                13
#define CKGEN_DMA_SF_HCLK1_CG                14
#define CKGEN_DMA_SF_PCLK0_CG                110
#define CKGEN_DMA_SF_PCLK1_CG                111
#define CKGEN_EFUSEC_PCLK_CG                102
#define CKGEN_EIC_BOOT_I_PCLK_CG                143
#define CKGEN_EIC_SF_I_PCLK_CG                142
#define CKGEN_EIC_SP_I_PCLK_CG                322
#define CKGEN_ETH1_ACLK_CG                304
#define CKGEN_ETH1_CLK_CSR_I_CG                316
#define CKGEN_ETH1_PTP_REF_CLK_CG                193
#define CKGEN_ETH1_REF_CLK_TX_I_CG                192
#define CKGEN_ETH2_ACLK_CG                305
#define CKGEN_ETH2_CLK_CSR_I_CG                317
#define CKGEN_ETH2_PTP_REF_CLK_CG                194
#define CKGEN_ETH2_REF_CLK_TX_I_CG                195
#define CKGEN_EPWM1_AHF_CLK_CG                209
#define CKGEN_EPWM1_HF_CLK_CG                217
#define CKGEN_EPWM1_PCLK_CG                80
#define CKGEN_EPWM2_AHF_CLK_CG                210
#define CKGEN_EPWM2_HF_CLK_CG                218
#define CKGEN_EPWM2_PCLK_CG                81
#define CKGEN_EPWM3_AHF_CLK_CG                211
#define CKGEN_EPWM3_HF_CLK_CG                219
#define CKGEN_EPWM3_PCLK_CG                82
#define CKGEN_EPWM4_AHF_CLK_CG                212
#define CKGEN_EPWM4_HF_CLK_CG                220
#define CKGEN_EPWM4_PCLK_CG                83
#define CKGEN_ETMR1_AHF_CLK_CG                205
#define CKGEN_ETMR1_HF_CLK_CG                213
#define CKGEN_ETMR1_PCLK_CG                73
#define CKGEN_ETMR2_AHF_CLK_CG                206
#define CKGEN_ETMR2_HF_CLK_CG                214
#define CKGEN_ETMR2_PCLK_CG                74
#define CKGEN_ETMR3_AHF_CLK_CG                207
#define CKGEN_ETMR3_HF_CLK_CG                215
#define CKGEN_ETMR3_PCLK_CG                75
#define CKGEN_ETMR4_AHF_CLK_CG                208
#define CKGEN_ETMR4_HF_CLK_CG                216
#define CKGEN_ETMR4_PCLK_CG                76
#define CKGEN_FLEXRAY1_HCLK_CG                15
#define CKGEN_FLEXRAY1_IPG_CLK_PE_CG                252
#define CKGEN_FLEXRAY2_HCLK_CG                16
#define CKGEN_FLEXRAY2_IPG_CLK_PE_CG                253
#define CKGEN_FS_24M_PCLK_CG                127
#define CKGEN_GAME1_ACLK_CG                306
#define CKGEN_GAME1_HCLK_CG                299
#define CKGEN_GPIO_SF_PCLK_CG                89
#define CKGEN_I2C1_I_PCLK_CG                17
#define CKGEN_I2C1_I_SCLK_CG                160
#define CKGEN_I2C2_I_PCLK_CG                18
#define CKGEN_I2C2_I_SCLK_CG                161
#define CKGEN_I2C3_I_PCLK_CG                19
#define CKGEN_I2C3_I_SCLK_CG                162
#define CKGEN_I2C4_I_PCLK_CG                20
#define CKGEN_I2C4_I_SCLK_CG                163
#define CKGEN_I2C5_I_PCLK_CG                21
#define CKGEN_I2C5_I_SCLK_CG                164
#define CKGEN_I2C6_I_PCLK_CG                22
#define CKGEN_I2C6_I_SCLK_CG                165
#define CKGEN_I2C7_I_PCLK_CG                23
#define CKGEN_I2C7_I_SCLK_CG                166
#define CKGEN_I2C8_I_PCLK_CG                24
#define CKGEN_I2C8_I_SCLK_CG                167
#define CKGEN_IOC_CLK_CG                254
#define CKGEN_IOC_PCLK_CG                135
#define CKGEN_IOMUXC_SF_COMP_PCLK_CG                101
#define CKGEN_IOMUXC_SF_PCLK_CG                100
#define CKGEN_IRAM_MUX_ACLK_CG                0
#define CKGEN_IRAM_MUX_PCLK_CG                84
#define CKGEN_IRAMc1_ACLK_CG                1
#define CKGEN_IRAMc1_PCLK_CG                85
#define CKGEN_IRAMc2_ACLK_CG                2
#define CKGEN_IRAMc2_PCLK_CG                86
#define CKGEN_IRAMc3_ACLK_CG                3
#define CKGEN_IRAMc3_PCLK_CG                87
#define CKGEN_IRAMc4_ACLK_CG                308
#define CKGEN_IRAMc4_PCLK_CG                328
#define CKGEN_IROMC_ACLK_CG                4
#define CKGEN_IROMC_PCLK_CG                88
#define CKGEN_ISTC_I_ISTC_CLK_CG                256
#define CKGEN_ISTC_I_PCLK_CG                144
#define CKGEN_LDO_DIG_PCLK_CG                283
#define CKGEN_MAC_PCLK_CG                103
#define CKGEN_MB_CLK_CG                8
#define CKGEN_MPC_CKGEN_CR5_SF_PCLK_CG                106
#define CKGEN_MPC_CKGEN_CR5_SX0_PCLK_CG                78
#define CKGEN_MPC_CKGEN_CR5_SX1_PCLK_CG                79
#define CKGEN_MPC_XSPI1A_ACLK_CG                197
#define CKGEN_MPC_XSPI1B_ACLK_CG                199
#define CKGEN_MPC_XSPI2A_ACLK_CG                201
#define CKGEN_MPC_XSPI2B_ACLK_CG                203
#define CKGEN_POR_SF_DIG_I_PCLK_CG                123
#define CKGEN_PPC_APBMUX1_PCLK_CG                117
#define CKGEN_PPC_CKGEN_APBMUX2_PCLK_CG                118
#define CKGEN_PPC_CKGEN_APBMUX3_PCLK_CG                119
#define CKGEN_PPC_CKGEN_APBMUX4_PCLK_CG                120
#define CKGEN_PPC_CKGEN_APBMUX5_PCLK_CG                313
#define CKGEN_PT_SNS_SF_CLKIN_CG                255
#define CKGEN_PT_SNS_SF_DIG_CLK_24M_CG                298
#define CKGEN_PT_SNS_SF_DIG_I_PCLK_CG                77
#define CKGEN_RSTGEN_SF_PCLK_CG                109
#define CKGEN_RTC_PCLK_CG                333
#define CKGEN_SADC1_CTRL_CLK_CG                245
#define CKGEN_SADC1_PCLK_CG                132
#define CKGEN_SADC2_CTRL_CLK_CG                246
#define CKGEN_SADC2_PCLK_CG                133
#define CKGEN_SADC3_CTRL_CLK_CG                247
#define CKGEN_SADC3_PCLK_CG                134
#define CKGEN_SCR_SF_PCLK_CG                107
#define CKGEN_SEM1_PCLK_CG                98
#define CKGEN_SEM2_PCLK_CG                99
#define CKGEN_SF_BOOT_MAINCLK_CG                7
#define CKGEN_SF_IRAM_MIX_MAC_PCLK_CG                105
#define CKGEN_SF_IRAM_MIX_MAINCLK_CG                5
#define CKGEN_SF_PERIPH_CKGEN_APBMUX3_PCLK_CG                145
#define CKGEN_SF_PERIPH_MAC_PCLK_CG                104
#define CKGEN_SF_PERIPH_MAINCLK_CG                6
#define CKGEN_SMC_CLK_24M_CG                257
#define CKGEN_SMC_PCLK_CG                121
#define CKGEN_SP_MAC_PCLK_CG                320
#define CKGEN_SPI1_PCLK_CG                25
#define CKGEN_SPI1_SPI_per_CLK_CG                168
#define CKGEN_SPI2_PCLK_CG                26
#define CKGEN_SPI2_SPI_per_CLK_CG                169
#define CKGEN_SPI3_PCLK_CG                27
#define CKGEN_SPI3_SPI_per_CLK_CG                170
#define CKGEN_SPI4_PCLK_CG                28
#define CKGEN_SPI4_SPI_per_CLK_CG                171
#define CKGEN_SPI5_PCLK_CG                29
#define CKGEN_SPI5_SPI_per_CLK_CG                172
#define CKGEN_SPI6_PCLK_CG                30
#define CKGEN_SPI6_SPI_per_CLK_CG                173
#define CKGEN_SPI7_PCLK_CG                31
#define CKGEN_SPI7_SPI_per_CLK_CG                174
#define CKGEN_SPI8_PCLK_CG                32
#define CKGEN_SPI8_SPI_per_CLK_CG                175
#define CKGEN_U_CKGEN_SF_PCLK_CG                108
#define CKGEN_UART10_I_PCLK_CG                42
#define CKGEN_UART10_I_SCLK_CG                185
#define CKGEN_UART11_I_PCLK_CG                43
#define CKGEN_UART11_I_SCLK_CG                186
#define CKGEN_UART12_I_PCLK_CG                44
#define CKGEN_UART12_I_SCLK_CG                187
#define CKGEN_UART13_I_PCLK_CG                45
#define CKGEN_UART13_I_SCLK_CG                188
#define CKGEN_UART14_I_PCLK_CG                46
#define CKGEN_UART14_I_SCLK_CG                189
#define CKGEN_UART15_I_PCLK_CG                47
#define CKGEN_UART15_I_SCLK_CG                190
#define CKGEN_UART16_I_PCLK_CG                48
#define CKGEN_UART16_I_SCLK_CG                191
#define CKGEN_UART1_I_PCLK_CG                33
#define CKGEN_UART1_I_SCLK_CG                176
#define CKGEN_UART2_I_PCLK_CG                34
#define CKGEN_UART2_I_SCLK_CG                177
#define CKGEN_UART3_I_PCLK_CG                35
#define CKGEN_UART3_I_SCLK_CG                178
#define CKGEN_UART4_I_PCLK_CG                36
#define CKGEN_UART4_I_SCLK_CG                179
#define CKGEN_UART5_I_PCLK_CG                37
#define CKGEN_UART5_I_SCLK_CG                180
#define CKGEN_UART6_I_PCLK_CG                38
#define CKGEN_UART6_I_SCLK_CG                181
#define CKGEN_UART7_I_PCLK_CG                39
#define CKGEN_UART7_I_SCLK_CG                182
#define CKGEN_UART8_I_PCLK_CG                40
#define CKGEN_UART8_I_SCLK_CG                183
#define CKGEN_UART9_I_PCLK_CG                41
#define CKGEN_UART9_I_SCLK_CG                184
#define CKGEN_VD_SF_DIG_I_PCLK_CG                122
#define CKGEN_VIC1_HCLK_CG                156
#define CKGEN_VIC1_WDT_REF_CLK_CG                285
#define CKGEN_VIC2a_HCLK_CG                301
#define CKGEN_VIC2a_WDT_REF_CLK_CG                331
#define CKGEN_VIC2b_HCLK_CG                302
#define CKGEN_VIC2b_WDT_REF_CLK_CG                332
#define CKGEN_VIC3a_HCLK_CG                157
#define CKGEN_VIC3a_WDT_REF_CLK_CG                286
#define CKGEN_VIC3b_HCLK_CG                158
#define CKGEN_VIC3b_WDT_REF_CLK_CG                287
#define CKGEN_VIC_SF_irqsync_CG                159
#define CKGEN_VIC_SP_IRQSYNC_CG                303
#define CKGEN_WDT1_BUS_CLK_CG                92
#define CKGEN_WDT1_MAIN_CLK_CG                288
#define CKGEN_WDT1_PCLK_CG                90
#define CKGEN_WDT2_BUS_CLK_CG                93
#define CKGEN_WDT2_MAIN_CLK_CG                289
#define CKGEN_WDT2_PCLK_CG                91
#define CKGEN_WDT3_BUS_CLK_CG                310
#define CKGEN_WDT3_MAIN_CLK_CG                329
#define CKGEN_WDT3_PCLK_CG                309
#define CKGEN_WDT4_BUS_CLK_CG                312
#define CKGEN_WDT4_MAIN_CLK_CG                330
#define CKGEN_WDT4_PCLK_CG                311
#define CKGEN_WDT5_BUS_CLK_CG                95
#define CKGEN_WDT5_MAIN_CLK_CG                290
#define CKGEN_WDT5_PCLK_CG                94
#define CKGEN_WDT6_BUS_CLK_CG                97
#define CKGEN_WDT6_MAIN_CLK_CG                291
#define CKGEN_WDT6_PCLK_CG                96
#define CKGEN_XB_SF_HCLK_CG                153
#define CKGEN_XB_SF_PCLK_CG                112
#define CKGEN_XSPI1a_CLK_CG                196
#define CKGEN_XSPI1a_DMA_CLK_CG                147
#define CKGEN_XSPI1b_CLK_CG                198
#define CKGEN_XSPI1b_DMA_CLK_CG                148
#define CKGEN_XSPI2a_CLK_CG                200
#define CKGEN_XSPI2a_DMA_CLK_CG                149
#define CKGEN_XSPI2b_CLK_CG                202
#define CKGEN_XSPI2b_DMA_CLK_CG                150
#define CKGEN_XSPI_SLV_ACLK_CG                300
#define CKGEN_XSPI_SLV_PCLK_CG                315
#define CKGEN_XTRG_CLK_CG                204
#define CKGEN_XTRG_PCLK_CG                124
#define CKGEN_XTRG_WDT_CLK_CG                282


#endif
