/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2022)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : Com_Cfg_Cbk.h                                                   **
**                                                                            **
**  Created on  :2024/10/10 14:30:29                                                             
**  Author      : ISOFT                                                       **
**  Vendor      :                                                             **
**  DESCRIPTION : If there is no RTE module, it is generated by COM           **
**                                                                            **
**  SPECIFICATION(S) :   AUTOSAR classic Platform 4.2.2                       **
**                                                                            **
*******************************************************************************/

#ifndef  COM_CFG_CBK_H
#define  COM_CFG_CBK_H

#include "ComStack_Types.h"

boolean IPDU_COM_VCU_0_Value_EPT_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_VCU_10_Torque_CHA_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_3_State_CHA_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_ACStatuts_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_COMP_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_1_Command_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_HVCH_Command_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_3_State_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_2_State_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TMS_LINTestData1_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TMS_LINTestData2_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TMS_LINTestData3_BOD_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_VCU_3_OprtCmd_EPT_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_VCU_B_AcclPedal_EPT_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_VCU_1_InvCmd_EPT_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_VCU_C_OprtCmd_EPT_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_BCM_IMMOAuthResp1_EPT_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_ACStatuts_BAC_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_AC_3_State_BAC_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_BCM_HFSData_BAC_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_NM_ASR_CCU_BAC_CANFD8_BAC_CAN1_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_NM_ASR_CCU_BOD_CANFD5_BOD_CAN6_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_NM_ASR_CCU_CHA_CANFD3_CHA_CAN5_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_NM_ASR_CCU_EPT_CANFD6_EPT_CAN2_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_VCU_DispInfo_BAC_CANFD8_BAC_CAN1_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_BCM_ESCLCommand_BOD_CANFD5_BOD_CAN6_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_VCU_B_AcclPedal_BAC_CANFD8_BAC_CAN1_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_CCU_VehInfo_CHA_CANFD3_CHA_CAN5_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_VCU_D_Status_CHA_CANFD3_CHA_CAN5_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_BCM_B_Package_CHA_CANFD3_CHA_CAN5_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_CCU_VehInfo_BOD_CANFD4_BOD_CAN4_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_AC_8_status_BOD_CANFD4_BOD_CAN4_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_VCU_4_ChrgCmd_EPT_CANFD6_EPT_CAN2_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_CCU_VehInfo_EPT_CANFD6_EPT_CAN2_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_CCU_VehInfo_BAC_CANFD8_BAC_CAN1_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_TX_BCM_B_Package_BAC_CANFD8_BAC_CAN1_TxCallout(PduIdType PduId, PduInfoType* PduInfoPtr);

boolean IPDU_COM_FCM_23_Obj0109_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_FCM_24_Obj1018_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_ESC_WheelPulseTime_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_SRS_2_YRSOriginalSts_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_SRS_3_YRSActualSts_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_EPS_3_LatDrvAndEPSSts_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_EPS_2_StrWhlAng_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_EPS_1_Status_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_CRRR_A_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_CRRR_10_Posn_CHA_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_CCP_PanelStatus_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_SCS_LeSwitchSts_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_TPMS_Info_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_ESCL_ESCLStatus_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_AVAS_State_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_COMP_AC_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_ACCM_Version_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_HVCH_Status1_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_HVCH_Status2_BOD_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_2_BatState_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_3_DC_ChargeState_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_4_AC_ChargeState_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_10_DC_ChargeStates_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_5_BatTemp_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_7_CellVolt_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_9_BattInfo_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_A_GB_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_B_GB_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_C_GB_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_BMS_D_GB_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_IPU_OBC_3_CP_CC_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_IPU_DCC_1_State_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_IPU_OBC_1_State_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_IPU_DCC_2_ChrgInValue_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_IPU_OBC_2_Inlet_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_IPU_OBC_4_state_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_INV_1_Value_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_INV_2_Value_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_INV_3_Value_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_INV_4_Value_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_INV_5_Values_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_INV_IMMO_Req_EPT_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_ICU_Info_BAC_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_ICU_2_Odo_BAC_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_HU_C_BAC_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_TBOX_BJS_Time_BAC_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_HU_B_BAC_CANFD8_BAC_CAN1_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_SCS_RiSwitchSts_BOD_CANFD5_BOD_CAN6_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_ESC_A_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_ESC_7_FuncStatus_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_EHB_B_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_SRS_1_Status_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_PP_InformAndStatus_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_BMS_HMI_EPT_CANFD6_EPT_CAN2_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_FCM_B_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_FCM_A_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_FCM_25_Line123_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_EHB_A_CHA_CANFD3_CHA_CAN5_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_BMS_1_MainState_EPT_CANFD6_EPT_CAN2_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_BMS_6_DischrgRecup_EPT_CANFD6_EPT_CAN2_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_BMS_8_TempVoltLimit_EPT_CANFD6_EPT_CAN2_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

boolean IPDU_COM_RX_HU_A_BAC_CANFD8_BAC_CAN1_RxCallout(PduIdType PduId, const PduInfoType* PduInfoPtr);

#endif
