/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2022)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : Com_Cfg_Cbk.c                                                   **
**                                                                            **
**  Created on  :2024/10/10 14:30:29                                                            
**  Author      : ISOFT                                                       **
**  Vendor      :                                                             **
**  DESCRIPTION : If there is  RTE module, it is generated by COM             **
**                                                                            **
**  SPECIFICATION(S) :   AUTOSAR classic Platform 4.2.2                       **
**                                                                            **
*******************************************************************************/
#include "ComStack_Types.h"
#include "Com_Cfg_Cbk.h"
#include "DIAG_ABI.h"

/* *************************************************************************************** */
//uint8 HU_A_BAC_AliveCnt[7] = {15,15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40,48}
uint8 HU_B_BAC_AliveCnt[3] = {15,15,15};    //ChksumByte  {0,8,16}
//uint8 HU_C_BAC_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 ICU_2_Odo_BAC_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 ICU_Info_BAC_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 TBOX_BJS_Time_BAC_AliveCnt[1] = {15};    //ChksumByte  {0}

//uint8 ACCM_Version_BOD_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 AVAS_State_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 CCP_PanelStatus_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 COMP_AC_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 ESCL_ESCLStatus_BOD_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 HVCH_Status1_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 HVCH_Status2_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 SCS_LeSwitchSts_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 SCS_RiSwitchSts_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 TPMS_Info_BOD_AliveCnt[1] = {15};    //ChksumByte  {255}

//uint8 CRRR_10_Posn_CHA_AliveCnt[2] = {15,15};    //ChksumByte  {0,8}
uint8 CRRR_A_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 EHB_A_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 EHB_B_CHA_AliveCnt[3] = {15,15,15};    //ChksumByte  {0,8,16}
//uint8 EPS_1_Status_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 EPS_2_StrWhlAng_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 EPS_3_LatDrvAndEPSSts_CHA_AliveCnt[2] = {15,15};    //ChksumByte  {0,8}
uint8 ESC_7_FuncStatus_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 ESC_A_CHA_AliveCnt[7] = {15,15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40,48}
//uint8 ESC_WheelPulseTime_CHA_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 FCM_23_Obj0109_CHA_AliveCnt[8] = {15,15,15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40,48,56}
//uint8 FCM_24_Obj1018_CHA_AliveCnt[8] = {15,15,15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40,48,56}
//uint8 FCM_25_Line123_CHA_AliveCnt[6] = {15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40}
//uint8 FCM_A_CHA_AliveCnt[6] = {15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40}
uint8 FCM_B_CHA_AliveCnt[5] = {15,15,15,15,15};    //ChksumByte  {0,8,16,24,32}
uint8 PP_InformAndStatus_CHA_AliveCnt[5] = {15,15,15,15,15};    //ChksumByte  {0,8,16,24,32}
uint8 SRS_1_Status_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 SRS_2_YRSOriginalSts_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 SRS_3_YRSActualSts_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}

//uint8 BMS_1_MainState_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 BMS_10_DC_ChargeStates_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 BMS_2_BatState_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 BMS_3_DC_ChargeState_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 BMS_4_AC_ChargeState_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 BMS_5_BatTemp_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 BMS_6_DischrgRecup_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_7_CellVolt_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_8_TempVoltLimit_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_9_BattInfo_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_A_GB_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_B_GB_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_C_GB_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_D_GB_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
//uint8 BMS_HMI_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 INV_1_Value_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 INV_2_Value_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 INV_3_Value_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 INV_4_Value_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 INV_5_Values_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 INV_IMMO_Req_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 IPU_DCC_1_State_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 IPU_DCC_2_ChrgInValue_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 IPU_OBC_1_State_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 IPU_OBC_2_Inlet_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 IPU_OBC_3_CP_CC_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
//uint8 IPU_OBC_4_state_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}

uint8 AC_3_State_BAC_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 AC_ACStatuts_BAC_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 BCM_B_Package_BAC_AliveCnt[7] = {15,15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40,48}
uint8 BCM_HFSData_BAC_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 CCU_VehInfo_BAC_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_B_AcclPedal_BAC_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_DispInfo_BAC_AliveCnt[5] = {15,15,15,15,15};    //ChksumByte  {0,8,16,24,32}

uint8 AC_1_Command_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 AC_2_State_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 AC_3_State_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 AC_8_status_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 AC_ACStatuts_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 AC_COMP_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 BCM_ESCLCommand_BOD_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 CCU_VehInfo_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 HVCH_Command_BOD_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 TMS_LINTestData1_BOD_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 TMS_LINTestData2_BOD_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 TMS_LINTestData3_BOD_AliveCnt[1] = {15};    //ChksumByte  {255}

uint8 AC_3_State_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 BCM_B_Package_CHA_AliveCnt[7] = {15,15,15,15,15,15,15};    //ChksumByte  {0,8,16,24,32,40,48}
uint8 CCU_VehInfo_CHA_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_10_Torque_CHA_AliveCnt[4] = {15,15,15,15};    //ChksumByte  {0,8,16,24}
uint8 VCU_D_Status_CHA_AliveCnt[4] = {15,15,15,15};    //ChksumByte  {0,8,16,24}

uint8 BCM_IMMOAuthResp1_EPT_AliveCnt[1] = {15};    //ChksumByte  {255}
uint8 CCU_VehInfo_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_0_Value_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_1_InvCmd_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_3_OprtCmd_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_4_ChrgCmd_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_B_AcclPedal_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
uint8 VCU_C_OprtCmd_EPT_AliveCnt[1] = {15};    //ChksumByte  {0}
/* *************************************************************************************** */

boolean IPDU_COM_VCU_0_Value_EPT_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_0_Value_EPT_ChksumByte;
    uint8* AliveCntPtr = &VCU_0_Value_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_VCU_10_Torque_CHA_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_10_Torque_CHA_ChksumByte;
    uint8* AliveCntPtr = &VCU_10_Torque_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_AC_3_State_CHA_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_3_State_CHA_ChksumByte;
    uint8* AliveCntPtr = &AC_3_State_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_AC_ACStatuts_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_ACStatuts_BOD_ChksumByte;
    uint8* AliveCntPtr = &AC_ACStatuts_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_AC_COMP_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_COMP_BOD_ChksumByte;
    uint8* AliveCntPtr = &AC_COMP_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_AC_1_Command_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_1_Command_BOD_ChksumByte;
    uint8* AliveCntPtr = &AC_1_Command_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_HVCH_Command_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = HVCH_Command_BOD_ChksumByte;
    uint8* AliveCntPtr = &HVCH_Command_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_AC_3_State_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_3_State_BOD_ChksumByte;
    uint8* AliveCntPtr = &AC_3_State_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_AC_2_State_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_2_State_BOD_ChksumByte;
    uint8* AliveCntPtr = &AC_2_State_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TMS_LINTestData1_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TMS_LINTestData2_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TMS_LINTestData3_BOD_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_VCU_3_OprtCmd_EPT_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_3_OprtCmd_EPT_ChksumByte;
    uint8* AliveCntPtr = &VCU_3_OprtCmd_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_VCU_B_AcclPedal_EPT_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_B_AcclPedal_EPT_ChksumByte;
    uint8* AliveCntPtr = &VCU_B_AcclPedal_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_VCU_1_InvCmd_EPT_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_1_InvCmd_EPT_ChksumByte;
    uint8* AliveCntPtr = &VCU_1_InvCmd_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_VCU_C_OprtCmd_EPT_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_C_OprtCmd_EPT_ChksumByte;
    uint8* AliveCntPtr = &VCU_C_OprtCmd_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_BCM_IMMOAuthResp1_EPT_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_AC_ACStatuts_BAC_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_ACStatuts_BAC_ChksumByte;
    uint8* AliveCntPtr = &AC_ACStatuts_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_AC_3_State_BAC_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_3_State_BAC_ChksumByte;
    uint8* AliveCntPtr = &AC_3_State_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_BCM_HFSData_BAC_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TX_NM_ASR_CCU_BAC_CANFD8_BAC_CAN1_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TX_NM_ASR_CCU_BOD_CANFD5_BOD_CAN6_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TX_NM_ASR_CCU_CHA_CANFD3_CHA_CAN5_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TX_NM_ASR_CCU_EPT_CANFD6_EPT_CAN2_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}
extern uint8 Test_100ms_count;
extern uint8 Test_20ms_count;
extern uint8 Test_5ms_count;
extern uint8 Test_10ms_count;
extern uint8 Test_50ms_count;
boolean IPDU_COM_TX_VCU_DispInfo_BAC_CANFD8_BAC_CAN1_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_DispInfo_BAC_ChksumByte;
    uint8* AliveCntPtr = &VCU_DispInfo_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr); 
    #if 0
    *(PduInfoPtr->SduDataPtr) = Test_100ms_count;
    *((PduInfoPtr->SduDataPtr) + 8) = Test_50ms_count;
    *((PduInfoPtr->SduDataPtr) + 16) = Test_20ms_count;
    *((PduInfoPtr->SduDataPtr) + 24) = Test_10ms_count;
    *((PduInfoPtr->SduDataPtr) + 32) = Test_5ms_count;
    #endif
    return TRUE;
}

boolean IPDU_COM_TX_BCM_ESCLCommand_BOD_CANFD5_BOD_CAN6_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TX_VCU_B_AcclPedal_BAC_CANFD8_BAC_CAN1_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_B_AcclPedal_BAC_ChksumByte;
    uint8* AliveCntPtr = &VCU_B_AcclPedal_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_CCU_VehInfo_CHA_CANFD3_CHA_CAN5_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = CCU_VehInfo_CHA_ChksumByte;
    uint8* AliveCntPtr = &CCU_VehInfo_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_VCU_D_Status_CHA_CANFD3_CHA_CAN5_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_D_Status_CHA_ChksumByte;
    uint8* AliveCntPtr = &VCU_D_Status_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_BCM_B_Package_CHA_CANFD3_CHA_CAN5_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = BCM_B_Package_CHA_ChksumByte;
    uint8* AliveCntPtr = &BCM_B_Package_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_CCU_VehInfo_BOD_CANFD4_BOD_CAN4_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = CCU_VehInfo_BOD_ChksumByte;
    uint8* AliveCntPtr = &CCU_VehInfo_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_AC_8_status_BOD_CANFD4_BOD_CAN4_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = AC_8_status_BOD_ChksumByte;
    uint8* AliveCntPtr = &AC_8_status_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_VCU_4_ChrgCmd_EPT_CANFD6_EPT_CAN2_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = VCU_4_ChrgCmd_EPT_ChksumByte;
    uint8* AliveCntPtr = &VCU_4_ChrgCmd_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_CCU_VehInfo_EPT_CANFD6_EPT_CAN2_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = CCU_VehInfo_EPT_ChksumByte;
    uint8* AliveCntPtr = &CCU_VehInfo_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_CCU_VehInfo_BAC_CANFD8_BAC_CAN1_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = CCU_VehInfo_BAC_ChksumByte;
    uint8* AliveCntPtr = &CCU_VehInfo_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_TX_BCM_B_Package_BAC_CANFD8_BAC_CAN1_TxCallout(
    PduIdType PduId,
    PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = BCM_B_Package_BAC_ChksumByte;
    uint8* AliveCntPtr = &BCM_B_Package_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_TxChksumAliveCnt_Calc(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_FCM_23_Obj0109_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_FCM_24_Obj1018_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_ESC_WheelPulseTime_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_SRS_2_YRSOriginalSts_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_SRS_3_YRSActualSts_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_EPS_3_LatDrvAndEPSSts_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_EPS_2_StrWhlAng_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = EPS_2_StrWhlAng_CHA_ChksumByte;
    uint8* AliveCntPtr = &EPS_2_StrWhlAng_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_EPS_1_Status_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_CRRR_A_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = CRRR_A_CHA_ChksumByte;
    uint8* AliveCntPtr = &CRRR_A_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_CRRR_10_Posn_CHA_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_CCP_PanelStatus_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = CCP_PanelStatus_BOD_ChksumByte;
    uint8* AliveCntPtr = &CCP_PanelStatus_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_SCS_LeSwitchSts_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TPMS_Info_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_ESCL_ESCLStatus_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_AVAS_State_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_COMP_AC_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = COMP_AC_BOD_ChksumByte;
    uint8* AliveCntPtr = &COMP_AC_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_ACCM_Version_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_HVCH_Status1_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = HVCH_Status1_BOD_ChksumByte;
    uint8* AliveCntPtr = &HVCH_Status1_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_HVCH_Status2_BOD_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_2_BatState_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = BMS_2_BatState_EPT_ChksumByte;
    uint8* AliveCntPtr = &BMS_2_BatState_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_BMS_3_DC_ChargeState_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_4_AC_ChargeState_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_10_DC_ChargeStates_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_5_BatTemp_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_7_CellVolt_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_9_BattInfo_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_A_GB_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_B_GB_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_C_GB_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_BMS_D_GB_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_IPU_OBC_3_CP_CC_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_IPU_DCC_1_State_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = IPU_DCC_1_State_EPT_ChksumByte;
    uint8* AliveCntPtr = &IPU_DCC_1_State_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_IPU_OBC_1_State_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_IPU_DCC_2_ChrgInValue_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_IPU_OBC_2_Inlet_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_IPU_OBC_4_state_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_INV_1_Value_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = INV_1_Value_EPT_ChksumByte;
    uint8* AliveCntPtr = &INV_1_Value_EPT_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_INV_2_Value_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_INV_3_Value_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_INV_4_Value_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_INV_5_Values_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_INV_IMMO_Req_EPT_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_ICU_Info_BAC_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = ICU_Info_BAC_ChksumByte;
    uint8* AliveCntPtr = &ICU_Info_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_ICU_2_Odo_BAC_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_HU_C_BAC_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_TBOX_BJS_Time_BAC_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = TBOX_BJS_Time_BAC_ChksumByte;
    uint8* AliveCntPtr = &TBOX_BJS_Time_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_HU_B_BAC_CANFD8_BAC_CAN1_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = HU_B_BAC_ChksumByte;
    uint8* AliveCntPtr = &HU_B_BAC_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_SCS_RiSwitchSts_BOD_CANFD5_BOD_CAN6_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = SCS_RiSwitchSts_BOD_ChksumByte;
    uint8* AliveCntPtr = &SCS_RiSwitchSts_BOD_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_ESC_A_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_ESC_7_FuncStatus_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = ESC_7_FuncStatus_CHA_ChksumByte;
    uint8* AliveCntPtr = &ESC_7_FuncStatus_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_EHB_B_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = EHB_B_CHA_ChksumByte;
    uint8* AliveCntPtr = &EHB_B_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_SRS_1_Status_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = SRS_1_Status_CHA_ChksumByte;
    uint8* AliveCntPtr = &SRS_1_Status_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_PP_InformAndStatus_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = PP_InformAndStatus_CHA_ChksumByte;
    uint8* AliveCntPtr = &PP_InformAndStatus_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_BMS_HMI_EPT_CANFD6_EPT_CAN2_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_FCM_B_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
    uint8 ChksumAtByte[] = FCM_B_CHA_ChksumByte;
    uint8* AliveCntPtr = &FCM_B_CHA_AliveCnt[0];
    uint8 ChksumLen = sizeof(ChksumAtByte);
    Com_RxChksumAliveCnt_Check(PduId, PduInfoPtr->SduDataPtr, PduInfoPtr->SduLength, ChksumAtByte, ChksumLen, AliveCntPtr);
    return TRUE;
}

boolean IPDU_COM_RX_FCM_A_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_FCM_25_Line123_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_EHB_A_CHA_CANFD3_CHA_CAN5_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_BMS_1_MainState_EPT_CANFD6_EPT_CAN2_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_BMS_6_DischrgRecup_EPT_CANFD6_EPT_CAN2_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_BMS_8_TempVoltLimit_EPT_CANFD6_EPT_CAN2_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

boolean IPDU_COM_RX_HU_A_BAC_CANFD8_BAC_CAN1_RxCallout(
    PduIdType PduId,
    const PduInfoType* PduInfoPtr
)
{
boolean ret = TRUE;
return ret;
}

