/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2022)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : Ea_Cfg.c                                                    **
**                                                                            **
**  Created on  : 2025/02/06 18:31:54                                         **
**  Author      : tao.yu                                                      **
**  Vendor      :                                                             **
**  DESCRIPTION : Ea globle data define                                       **
**                                                                            **
**  SPECIFICATION(S) :   AUTOSAR classic Platform R19-11                      **
**                                                                            **
*******************************************************************************/

#include "Ea_Cfg.h"
#include "Ea_Types.h"
#include "Eep_62.h"
#include "Eep_62_Api.h"

#define EA_START_SEC_CONST_UNSPECIFIED
#include "Ea_MemMap.h"
static CONST(Ea_BlockConfigurationType, EA_PRIVATE_CONST) Ea_BlockConfiguration[EA_NUMBER_OF_BLOCKS] =
{
    {
        0U,
        16U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        32U,
        17U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        64U,
        32U,
        64U,
        FALSE,
        0u,
        0u
    },
    {
        128U,
        48U,
        64U,
        FALSE,
        0u,
        0u
    },
    {
        192U,
        64U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        224U,
        80U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        256U,
        96U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        288U,
        112U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        320U,
        128U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        352U,
        144U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        384U,
        160U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        416U,
        176U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        448U,
        192U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        480U,
        256U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        512U,
        288U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        608U,
        304U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        704U,
        320U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        800U,
        336U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        896U,
        352U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        992U,
        368U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1088U,
        384U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1184U,
        400U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1280U,
        416U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1376U,
        432U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1472U,
        448U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1568U,
        464U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1664U,
        480U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1760U,
        496U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1856U,
        512U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        1952U,
        528U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2048U,
        544U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2144U,
        560U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2240U,
        576U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2336U,
        592U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2432U,
        608U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2528U,
        624U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2624U,
        640U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2720U,
        656U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2816U,
        672U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        2912U,
        688U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3008U,
        704U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3104U,
        720U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3200U,
        736U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3296U,
        752U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3392U,
        768U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3488U,
        784U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3584U,
        800U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3680U,
        816U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3776U,
        832U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3872U,
        848U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        3968U,
        864U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4064U,
        880U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4160U,
        896U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4256U,
        912U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4352U,
        928U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4448U,
        944U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4544U,
        960U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4640U,
        976U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4736U,
        992U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4832U,
        1008U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        4928U,
        1024U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        5024U,
        1040U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        5120U,
        1056U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        5216U,
        1072U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        5312U,
        1088U,
        928U,
        FALSE,
        0u,
        0u
    },
    {
        6240U,
        1120U,
        96U,
        FALSE,
        0u,
        0u
    },
    {
        6336U,
        1136U,
        288U,
        FALSE,
        0u,
        0u
    },
    {
        6624U,
        1148U,
        160U,
        FALSE,
        0u,
        0u
    },
    {
        6784U,
        1164U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        6816U,
        1180U,
        288U,
        FALSE,
        0u,
        0u
    },
    {
        7104U,
        1196U,
        32U,
        FALSE,
        0u,
        0u
    },
    {
        7136U,
        1212U,
        160U,
        FALSE,
        0u,
        0u
    },
};

static CONST(Ea_BlockCfgType, EA_CONST) Ea_BlockCfg =
{
    EA_NUMBER_OF_BLOCKS,
    Ea_BlockConfiguration
};

static CONST(Ea_EepApiType, EA_CONST) Ea_EepApi[1] =
{
    {
        Eep_62_Read_0,
        Eep_62_Write_0,
        Eep_62_Erase_0,
        Eep_62_Cancel_0,
        Eep_62_GetStatus_0,
        Eep_62_GetJobResult_0,
        Eep_62_SetMode_0
    },
};

/* PRQA S 3408,1531++ */ /* MISRA Rule 8.4,Rule 8.7 */
CONST(Ea_ConfigType, EA_CONST) Ea_Config =
/* PRQA S 3408,1531-- */ /* MISRA Rule 8.4,Rule 8.7 */
{
    &Ea_BlockCfg,
    0x1u,
    Ea_EepApi,
    NULL_PTR,
    NULL_PTR
};

#define EA_STOP_SEC_CONST_UNSPECIFIED
#include "Ea_MemMap.h"

