/*
 * SEMIDRIVE Copyright Statement
 * Copyright (c) SEMIDRIVE. All rights reserved
 *
 * This software and all rights therein are owned by SEMIDRIVE, and are
 * protected by copyright law and other relevant laws, regulations and
 * protection. Without SEMIDRIVE's prior written consent and/or related rights,
 * please do not use this software or any potion thereof in any form or by any
 * means. You may not reproduce, modify or distribute this software except in
 * compliance with the License. Unless required by applicable law or agreed to
 * in writing, software distributed under the License is distributed on
 * an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 * You should have received a copy of the License along with this program.
 * If not, see <http://www.semidrive.com/licenses/>.
 */

/*
* @file Fls_Cfg.c
* @brief AutoSAR Fls configuration source file
* @details Automatically generated by user settings
* @date 2024-01-23 17:30:16
*/

#ifdef __cplusplus
extern "C" {
#endif

#include "Fls.h"

extern void Fee_JobEndNotification(void);
extern void Fee_JobErrorNotification(void);

#define FLS_START_SEC_VAR_INIT_UNSPECIFIED
#include "Fls_MemMap.h"

Fls_ProgramDescriptorType fls_FlashProgDescriptor = {
    .FlsJobEndNotification = Fee_JobEndNotification,
    .FlsJobErrorNotification = Fee_JobErrorNotification,
};

Fls_SectorConfigType fls_SectorList[1] =
{
    {
        .FlsNumberOfSectors = 59,
        .FlsPageSize        = 256,
        .FlsSectorSize      = 262144,
        .FlsSectorStartAddr = 1310720,
        .FlsTotalSize       = 15466496,
        .ControllerIndex    = -1,
    }
};

static Fls_ContextType Cor0Context = {
    .index = 0,
    .ops = &hyperbus_ops,
};

#define FLS_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "Fls_MemMap.h"

#define FLS_START_SEC_CONST_UNSPECIFIED
#include "Fls_MemMap.h"
const Fls_ConfigType  Fls_ConfigData =
{
    .async_mode = 0,
    .NumberOfController = 1,
    .OSPIController = {
        {
            .ID = FLS_XSPI1_PORTA,
            .HostConfig = {
                .id = FLS_XSPI1_PORTA,
                .cs = 0,
                .baudrate = 20000000,
                .xfer_mode = SPI_NOR_XFER_POLLING_MODE,
                .dev_mode = SPI_NOR_DEV_SINGLE_MODE,
                .hyperbus_mode = FLS_INTERFACE_HYPERBUS,
                .async_mode = 0,
            },
            .FlsSpecialFlag = FLS_SPECIAL_AUTO,
            .FlsPrivateData = &Cor0Context,
        },
    },
    .Flash = {
        .FlsCallCycle = 100000,  /* in us */
        .FlsDefaultMode= MEMIF_MODE_SLOW,
        .FlsMaxReadFastMode = 256,
        .FlsMaxReadNormalMode = 4096,
        .FlsMaxWriteFastMode = 256,
        .FlsMaxWriteNormalMode = 4096,
        .FlsProtection = 0,
        .FlsSectorListSize = 1U,
        .FlsSectorList = fls_SectorList,
        .FlsProgDesc = &fls_FlashProgDescriptor,
    },
};
#define FLS_STOP_SEC_CONST_UNSPECIFIED
#include "Fls_MemMap.h"

#ifdef __cplusplus
}
#endif
