/*
 * SEMIDRIVE Copyright Statement
 * Copyright (c) SEMIDRIVE. All rights reserved
 *
 * This software and all rights therein are owned by SEMIDRIVE, and are
 * protected by copyright law and other relevant laws, regulations and
 * protection. Without SEMIDRIVE's prior written consent and/or related rights,
 * please do not use this software or any potion thereof in any form or by any
 * means. You may not reproduce, modify or distribute this software except in
 * compliance with the License. Unless required by applicable law or agreed to
 * in writing, software distributed under the License is distributed on
 * an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 * You should have received a copy of the License along with this program.
 * If not, see <http://www.semidrive.com/licenses/>.
 */

/**
 * @file Spi_PbCfg.c
 * @brief AutoSAR SPI configuration header file
 * @details Automatically generated by user settings
 * @date 2023-09-21 19:24:34
 */

/*******************************************************************************
**                      Include Section                                       **
*******************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

#include "Spi.h"



/*******************************************************************************
**                      Version Information                                   **
*******************************************************************************/

/* AUTOSAR specification version information */
#define SPI_PBCFG_C_AR_RELEASE_MAJOR_VERSION  4U
#define SPI_PBCFG_C_AR_RELEASE_MINOR_VERSION  3U
#define SPI_PBCFG_C_AR_RELEASE_REVISION_VERSION  1U

/*******************************************************************************
**                      Version Check                                         **
*******************************************************************************/


#if (SPI_AR_RELEASE_MAJOR_VERSION_VALUE != \
         SPI_PBCFG_C_AR_RELEASE_MAJOR_VERSION)
  #error "Spi_PBcfg.c : Mismatch in Release Major Version"
#endif

#if (SPI_AR_RELEASE_MINOR_VERSION_VALUE != \
         SPI_PBCFG_C_AR_RELEASE_MINOR_VERSION)
  #error "Spi_PBcfg.c : Mismatch in Release Minor Version"
#endif

#if (SPI_AR_RELEASE_REVISION_VERSION_VALUE != \
         SPI_PBCFG_C_AR_RELEASE_REVISION_VERSION)
  #error "Spi_PBcfg.c : Mismatch in Release Revision Version"
#endif


/*******************************************************************************
**                      Global Data                                           **
*******************************************************************************/

#define SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "Spi_MemMap.h"

/* Channels params check */
                                                              
    
/* Global array for internal write buffers */
VAR_ALIGN(uint8 Spi_IBWriteBuffer_SpiChannel_TJA1145[ROUNDUP(SPI_BUFFER_SIZE_CHANNEL_0,BUFF_SIZE_ROUNDUP_LEN)],SPI_BUFF_ALIGN_LEN);
/* Global array for internal read buffers */


#define SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "Spi_MemMap.h"

#define SPI_START_SEC_CONST_UNSPECIFIED
#include "Spi_MemMap.h"

/* This array contains configuration details for Channels */
CONST(Spi_ChannelCfgType, SPI_CONST) Spi_ChannelConfig[SPI_TOTAL_CH_COUNT] =
{
  /* Index: 0 - SpiChannel_TJA1145 */
  {
    /* ChannelBufferType */
    EB,
    /* TxDataWidth */
    8U,
    /* BufferSize */
    SPI_BUFFER_SIZE_CHANNEL_0,
    /* WriteBufferIndex */
    (Spi_DataBufferType*)Spi_IBWriteBuffer_SpiChannel_TJA1145,
    /* ReadBufferIndex */
    NULL_PTR,
    /* TransferType */
    MSB,
    /* DefaultValue */
    0,
  }    
};

/* Channel list */
CONST(Spi_ChannelType, SPI_CONST) SpiJob_TJA1145_ChannelList [1]=
{
    /* Linked channels for job: 0  */
    0U,
};
/*
  Why don't we use a loop statement here, because I can't figure out the German thinking circuit
*/
                


/*
  This array contains configuration details for Jobs.
  And sorted by Job priority
*/

  
    



CONST(Spi_JobCfgType, SPI_CONST) Spi_JobConfig[SPI_TOTAL_JOB_COUNT] =
{
    /* Index: 0 - SpiJob_TJA1145 */
  {
    /* DataWith */
    8,
    /* BitOrder */
    MSB,
    /* Device Idx */
    0,
    /*HwUnitIdxCfg*/
    0U,
    /* HWUnit */
    CSIB7,
    /* CSPin */
    SPI_CS_0,
    /* CSFunc */
    FALSE,
    /* PortPinId */
    0xFF,
    /* PinMux */
    PIN_MUX_ALT0,
    /* GPIOCsPinID*/
    0xFF,
    /* EnableRx */
    TRUE,
    /* CSHandling */
    CS_VIA_PERIPHERAL_ENGINE,
    /* CSPolarity */
    LOW,
    /* BaudRate Div */
    24U,
    /* TimeClkCs StartDelay */
    0U,    
    /* EndDelay */
    0U,    
    /* ShiftClk */
    LOW,
    /* ShiftEdge */
    LEADING,
    /* Priority */
    3U,
    /* JobEndNotification */
    NULL_PTR,
    /* NoOfChannels */
    1U,
    /* ChannelList */
    SpiJob_TJA1145_ChannelList,
    /* In master mode, delay half sclk to sample miso */
    FALSE,

  },
};

/* Job list */

CONST(Spi_JobType, SPI_CONST) SpiSequence_TJA1145_JobList [1]=
{
    /*
      Linked Job for Sequence: 0
      and sorted by Job priority.
    */
    0U ,  
};






/* This array contains configuration details for Sequences */
CONST(Spi_SequenceCfgType, SPI_CONST) Spi_SequenceConfig[SPI_TOTAL_SEQ_COUNT] =
{
  /* Index: 0 - SpiSequence_TJA1145 */
  {
    /* InterruptableSequence */
    TRUE,
    /* SequenceEndNotification */
    NULL_PTR,
    /* NoOfJobs */
    1U,
    /* JobList */
    SpiSequence_TJA1145_JobList,
    /* Jobs HwMask */
    0x1 << CSIB7
  },

};

/* Hw list */
/* This array contains HwUnit property */
CONST(Spi_HwUnitConfigType, SPI_CONST) Spi_HwUnitConfig[SPI_TOTAL_HW_COUNT] =
{
  
  /* SpiHwUnit_SPI7 */
  {
    .HwUnit = CSIB7,
    /* DMA mode Enable */
    .HwDMA = (boolean)FALSE,
    /* HwMode: spi master or slave */
    .HwMode = SPI_MASTER,
    /* Ti mode Enable */
    .HwTiMode = (boolean)FALSE,
    /* In E3 this params no use */
    .TransferMode = SPI_ASYNC_MODE,
  }
};


CONST(uint8, SPI_CONST) Spi_InstanceMask_Config[5] =
{
      0x01<<CSIB7 | 0 ,    
      0,  
      0,  
      0,  
      0,  

};
/* Structure for SPI Init configuration */
CONST(Spi_ConfigType, SPI_CONST) Spi_Config[SPI_TOTAL_DRIVERS] =
{
  /* Index: 0 - SpiDriver */
  {
    /* ChannelType */
    Spi_ChannelConfig,
    /* JobType */
    Spi_JobConfig,
    /* SequenceType */
    Spi_SequenceConfig

  }
};

#define SPI_STOP_SEC_CONST_UNSPECIFIED
#include "Spi_MemMap.h"

#ifdef __cplusplus
}
#endif
/*******************************************************************************
**                          End of File                                       **
*******************************************************************************/

