/*********************************************************************************************************************
 * Copyright (c) 2019, Infineon Technologies AG
 *
 *
 * Distributed under the Boost Software License, Version 1.0.
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *********************************************************************************************************************/


/****************************************************************************************************//**
 * @file        TLE94x1_SPI.c
 *
 * @brief       Implementation of all SPI related functions
 *
 * @version     V1.0.0
 * @date        15. April 2019
 * @author      Markus Noll / markus.noll@infineon.com
 * @author      Yannek Micha Rixen / Yannek.Rixen@infineon.com
 *******************************************************************************************************/




/* ================================================================================ */
/* ============================   HEADER FILES     ================================ */
/* ================================================================================ */

#include "TLE94x1_SPI.h"
#include "Mcu_Delay.h"

#include "Spi.h"
#include "Spi_Cfg.h"

/* ================================================================================ */
/* =======================   SPI communication functions     ====================== */
/* ================================================================================ */



uint8 SBC_SPI_INIT(void) {

    Spi_Init(Spi_Config);

    return 0;
}

uint16 SBC_SPI_TRANSFER16(uint8 Upper, uint8 Lower) {

    uint8 txBuf[2] = {0};
    uint8 rxBuf[2] = {0};
    uint16 outdata = 0;
    sint32 ret = 0;

    txBuf[0] = Upper;
    txBuf[1] = Lower;
    Mcu_PmuCounterInit();
    SuspendAllInterrupts();
    ret = Spi_SetupEB(SpiConf_SpiChannel_SpiChannel_32,
        (void*)&txBuf[0],
        (void*)&rxBuf[0],
    SPI_BUFFER_SIZE_CHANNEL_32);
    if(ret != 0){
        DBG("Fail Spi_SetupEB %d\n",SpiConf_SpiChannel_SpiChannel_32);
    }

    if(Spi_SyncTransmit(SpiConf_SpiSequence_SpiSequence_5) != 0){
        DBG("Fail sequence Busy. \n");
    }
    ResumeAllInterrupts(); 
    /* CSN High Time at least 3us. See datasheet 162 */
    Mcu_udelay(3);

    outdata = rxBuf[0];
    outdata <<= 8;
    outdata |= rxBuf[1];

    return outdata;
}
