
/*
 * SEMIDRIVE Copyright Statement
 * Copyright (c) SEMIDRIVE. All rights reserved
 *
 * This software and all rights therein are owned by SEMIDRIVE, and are
 * protected by copyright law and other relevant laws, regulations and
 * protection. Without SEMIDRIVE's prior written consent and/or related rights,
 * please do not use this software or any potion thereof in any form or by any
 * means. You may not reproduce, modify or distribute this software except in
 * compliance with the License. Unless required by applicable law or agreed to
 * in writing, software distributed under the License is distributed on
 * an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 * You should have received a copy of the License along with this program.
 * If not, see <http://www.semidrive.com/licenses/>.
 */

/**
 * @file  ioc_reg_e3.h
 * @brief Semidrive. AUTOSAR 4.3.1 MCAL Lin
 */

/* Generated by tool. Do not modify manually. */

#ifndef IOC_INDEX_H
#define IOC_INDEX_H

#ifndef SEMIDRIVE_E3_LITE_SERIES
#include "ioc_index_e3.h"
#else
#include "ioc_index_e3l.h"
#endif
#endif /* IOC_INDEX_H */
