param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.4\common\bin\cspybat" -f "D:\wwq\gitlib\Gecko_CCU\Gecko_E3420_CCU_R19_MCAL3_1_IAR_V8_50_6_Project_PPV\iar\iar_v850\E3_ref_gateway_E3420_xip\settings\E3_ref_gateway_E3420_xip.Debug.general.xcl" --backend -f "D:\wwq\gitlib\Gecko_CCU\Gecko_E3420_CCU_R19_MCAL3_1_IAR_V8_50_6_Project_PPV\iar\iar_v850\E3_ref_gateway_E3420_xip\settings\E3_ref_gateway_E3420_xip.Debug.driver.xcl" 
}
else
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.4\common\bin\cspybat" -f "D:\wwq\gitlib\Gecko_CCU\Gecko_E3420_CCU_R19_MCAL3_1_IAR_V8_50_6_Project_PPV\iar\iar_v850\E3_ref_gateway_E3420_xip\settings\E3_ref_gateway_E3420_xip.Debug.general.xcl" --debug_file=$debugfile --backend -f "D:\wwq\gitlib\Gecko_CCU\Gecko_E3420_CCU_R19_MCAL3_1_IAR_V8_50_6_Project_PPV\iar\iar_v850\E3_ref_gateway_E3420_xip\settings\E3_ref_gateway_E3420_xip.Debug.driver.xcl" 
}
