/*
 * File: TMS_MonitorData.c
 *
 * Code generated for Simulink model 'ME11'.
 *
 * Model version                  : 1.2191
 * Simulink Coder version         : 9.8 (R2022b) 13-May-2022
 * C/C++ source code generated on : Fri Oct 11 13:47:24 2024
 *
 * Target selection: autosar.tlc
 * Embedded hardware selection: NXP->Cortex-M4
 * Code generation objectives: Unspecified
 * Validation result: Not run
 */

#include "TMS_MonitorData.h"
#include "ME11.h"

/* Exported data definition */

/* Volatile memory section */
#include "XcpTest_types.h"

/* Definition for custom storage class: TMS_MonitorData */
MONPRM volatile float32 ACCCtl_sACCabinPreSetByEnv = 0.0F;/* '<S185>/cal_ACCabinPreSetByEnv_MAP' */
MONPRM volatile float32 ACCCtl_sACCabinPreSetByEnvECO = 0.0F;
                                    /* '<S185>/cal_ACCabinPreSetByEnvECO_MAP' */
MONPRM volatile float32 ACCCtl_sBlowerFanSpd = 0.0F;/* '<S56>/MinMax' */
MONPRM volatile float32 ACCCtl_sSetPtcDesTempMax = 0.0F;/* '<S179>/cal_SetPtcDesTempMax_MAP' */
MONPRM volatile uint8 ACCtl_BloweFanSpeed = ((uint8)0U);/* '<S42>/Merge' */
MONPRM volatile BlowerModes ACCtl_BlowerMode = BlowerModes_FaceMode;/* '<S43>/Merge' */
MONPRM volatile float32 ACCtl_DVTIDeadBand = 0.0F;/* '<S187>/Constant7' */
MONPRM volatile float32 ACCtl_DrfacPtc2NominalTemp = 0.0F;/* '<S391>/Switch4' */
MONPRM volatile uint8 ACCtl_IntakeRatio = ((uint8)0U);/* '<S47>/Merge' */
MONPRM volatile float32 ACCtl_PsfacPtc2NominalTemp = 0.0F;/* '<S417>/Switch4' */
MONPRM volatile float32 ACCtl_RFace2FaceFloor = 0.0F;
                                      /* '<S80>/cal_RFace2FaceFloorByEnv_CUR' */
MONPRM volatile float32 ACCtl_RFaceFloor2Face = 0.0F;
                                      /* '<S80>/cal_RFaceFloor2FaceByEnv_CUR' */
MONPRM volatile float32 ACCtl_RFaceFloor2Floor = 0.0F;
                                     /* '<S80>/cal_RFaceFloor2FloorByEnv_CUR' */
MONPRM volatile float32 ACCtl_RFloor2FaceFloor = 0.0F;
                                     /* '<S80>/cal_RFloor2FaceFloorByEnv_CUR' */
MONPRM volatile boolean ACCtl_bExhFlg = false;/* '<S1118>/Switch' */
MONPRM volatile boolean ACCtl_bExhaustFlg = false;/* '<S12>/AND2' */
MONPRM volatile uint16 ACCtl_pwrHeatingFeed = ((uint16)0U);/* '<S94>/cal_ACPTCPwrPreSetByEnv_MAP' */
MONPRM volatile float32 ACCtl_pwrHeatingICor = 0.0F;/* '<S105>/Merge1' */
MONPRM volatile float32 ACCtl_pwrHeatingISum = 0.0F;/* '<S101>/Switch1' */
MONPRM volatile float32 ACCtl_pwrHeatingPCor = 0.0F;/* '<S104>/Merge' */
MONPRM volatile uint16 ACCtl_pwrHeatingReq = ((uint16)0U);/* '<S38>/Signal Copy' */
MONPRM volatile uint8 ACCtl_rDrBasicMixDoor = ((uint8)0U);/* '<S389>/Switch6' */
MONPRM volatile uint8 ACCtl_rDrMixDoorDes = ((uint8)0U);/* '<S390>/Data Type Conversion' */
MONPRM volatile float32 ACCtl_rDrSetMixDoorICor = 0.0F;/* '<S400>/Merge1' */
MONPRM volatile float32 ACCtl_rDrSetMixDoorISum = 0.0F;/* '<S396>/Switch1' */
MONPRM volatile float32 ACCtl_rDrSetMixDoorPCor = 0.0F;/* '<S399>/Merge' */
MONPRM volatile uint8 ACCtl_rPsBasicMixDoor = ((uint8)0U);/* '<S415>/Switch6' */
MONPRM volatile float32 ACCtl_rPsBlowerModeSet = 0.0F;/* '<S415>/Multiport Switch2' */
MONPRM volatile uint8 ACCtl_rPsMixDoorDes = ((uint8)0U);/* '<S416>/Data Type Conversion' */
MONPRM volatile float32 ACCtl_rPsSetMixDoorICor = 0.0F;/* '<S424>/Merge1' */
MONPRM volatile float32 ACCtl_rPsSetMixDoorISum = 0.0F;/* '<S420>/Switch1' */
MONPRM volatile float32 ACCtl_rPsSetMixDoorPCor = 0.0F;/* '<S423>/Merge' */
MONPRM volatile float32 ACCtl_sECOEvaDesValLL = 0.0F;/* '<S178>/cal_ECOEvaDesValLL_MAP' */
MONPRM volatile float32 ACCtl_sMixDoorClsFF = 0.0F;/* '<S390>/Switch' */
MONPRM volatile boolean ACCtl_stACPTCHeated = false;/* '<S179>/PTCHeatedCheck' */
MONPRM volatile boolean ACCtl_stCabinCoolingEn = false;/* '<S44>/Merge' */
MONPRM volatile boolean ACCtl_stCabinHeatingEn = false;/* '<S93>/Logical Operator' */
MONPRM volatile uint8 ACCtl_stDvtPIDFreez = ((uint8)0U);/* '<S190>/Merge' */
MONPRM volatile boolean ACCtl_stEvaCooledFlag = false;/* '<S178>/EvaCooledCheck' */
MONPRM volatile boolean ACCtl_stRecACHotStartEna = false;/* '<S126>/Relational Operator5' */
MONPRM volatile boolean ACCtl_stRecAQSEna = false;/* '<S127>/Recirc_AQS' */
MONPRM volatile boolean ACCtl_stRecForceChangeEna = false;/* '<S128>/Switch3' */
MONPRM volatile boolean ACCtl_stRecForceDefogEna = false;/* '<S129>/Relational Operator' */
MONPRM volatile uint8 ACCtl_stRecLevelFinal = ((uint8)0U);/* '<S38>/Max' */
MONPRM volatile boolean ACCtl_stRecManualEna = false;/* '<S125>/Logical Operator' */
MONPRM volatile boolean ACCtl_stRecNormalDefogEna = false;/* '<S130>/Logical Operator' */
MONPRM volatile boolean ACCtl_stRecOut = false;/* '<S47>/Merge' */
MONPRM volatile boolean ACCtl_stRecPCUTempEna = false;/* '<S131>/Switch' */
MONPRM volatile boolean ACCtl_stRecPTCDvtEna = false;/* '<S132>/Switch1' */
MONPRM volatile boolean ACCtl_stRecQkChargeCoolingEna = false;/* '<S133>/Logical Operator' */
MONPRM volatile boolean ACCtl_stRecRemoteACEna = false;/* '<S134>/Relational Operator3' */
MONPRM volatile boolean ACCtl_stRecSummerCondEna = false;/* '<S135>/Relational Operator4' */
MONPRM volatile boolean ACCtl_stRecTargetOutTempEna = false;/* '<S136>/Switch1' */
MONPRM volatile boolean ACCtl_stRecTempLowEna = false;/* '<S35>/OR' */
MONPRM volatile boolean ACCtl_stRecVentEna = false;/* '<S138>/Logical Operator2' */
MONPRM volatile boolean ACCtl_stRecWinterCondEna = false;/* '<S139>/Relational Operator4' */
MONPRM volatile uint8 ACCtl_stStartState = ((uint8)0U);/* '<S39>/AirConditionStartState' */
MONPRM volatile float32 ACCtl_tDVTFeedfoward = 0.0F;/* '<S208>/Switch2' */
MONPRM volatile float32 ACCtl_tDVTFlt = 0.0F;/* '<S58>/Add' */
MONPRM volatile float32 ACCtl_tDVTPIBas = 0.0F;/* '<S190>/Merge' */
MONPRM volatile float32 ACCtl_tDesFrontCabin = 0.0F;/* '<S185>/Switch3' */
MONPRM volatile float32 ACCtl_tDrDVT = 0.0F;/* '<S181>/Switch3' */
MONPRM volatile float32 ACCtl_tDrDVTSolarCor = 0.0F;/* '<S181>/cal_ACDrDVTSolarCor_MAP' */
MONPRM volatile float32 ACCtl_tDrEvapDes = 0.0F;/* '<S283>/Switch2' */
MONPRM volatile float32 ACCtl_tDrEvapDesPI = 0.0F;/* '<S286>/Merge' */
MONPRM volatile float32 ACCtl_tDrEvapICor = 0.0F;/* '<S289>/Merge1' */
MONPRM volatile float32 ACCtl_tDrEvapISum = 0.0F;/* '<S284>/Switch1' */
MONPRM volatile float32 ACCtl_tDrEvapPCor = 0.0F;/* '<S288>/Merge' */
MONPRM volatile float32 ACCtl_tDrPTCICor = 0.0F;/* '<S348>/Merge1' */
MONPRM volatile float32 ACCtl_tDrPTCISum = 0.0F;/* '<S344>/Switch1' */
MONPRM volatile float32 ACCtl_tDrPTCPCor = 0.0F;/* '<S347>/Merge' */
MONPRM volatile float32 ACCtl_tDrSetBasicEvap = 0.0F;/* '<S305>/Switch2' */
MONPRM volatile float32 ACCtl_tDrSetBasicPTC = 0.0F;/* '<S343>/Switch2' */
MONPRM volatile float32 ACCtl_tDvtICor = 0.0F;/* '<S192>/Merge1' */
MONPRM volatile float32 ACCtl_tDvtISum = 0.0F;/* '<S188>/Switch1' */
MONPRM volatile float32 ACCtl_tDvtPCor = 0.0F;/* '<S191>/Merge' */
MONPRM volatile float32 ACCtl_tErrACPTC = 0.0F;/* '<S102>/Switch1' */
MONPRM volatile boolean ACCtl_tErrACPTCPosFlag = false;/* '<S102>/Relational Operator' */
MONPRM volatile float32 ACCtl_tErrDVT = 0.0F;/* '<S189>/Switch1' */
MONPRM volatile boolean ACCtl_tErrDVTFlag = false;/* '<S189>/Relational Operator' */
MONPRM volatile float32 ACCtl_tErrDrDVT2Duct = 0.0F;/* '<S285>/Switch1' */
MONPRM volatile float32 ACCtl_tErrPsDVT2Duct = 0.0F;/* '<S311>/Switch1' */
MONPRM volatile float32 ACCtl_tLeftDuct = 0.0F;/* '<S175>/Switch' */
MONPRM volatile float32 ACCtl_tPsDVT = 0.0F;/* '<S182>/Switch1' */
MONPRM volatile float32 ACCtl_tPsDVTCabinCor = 0.0F;/* '<S182>/cal_ACPsDVTSetCorByEnv_MAP' */
MONPRM volatile float32 ACCtl_tPsDVTSolarCor = 0.0F;/* '<S182>/cal_ACPsDVTSolarCor_MAP' */
MONPRM volatile float32 ACCtl_tPsEvapDes = 0.0F;/* '<S308>/Switch2' */
MONPRM volatile float32 ACCtl_tPsEvapDesPI = 0.0F;/* '<S312>/Merge' */
MONPRM volatile float32 ACCtl_tPsEvapICor = 0.0F;/* '<S315>/Merge1' */
MONPRM volatile float32 ACCtl_tPsEvapISum = 0.0F;/* '<S310>/Switch1' */
MONPRM volatile float32 ACCtl_tPsEvapPCor = 0.0F;/* '<S313>/Merge' */
MONPRM volatile float32 ACCtl_tPsPTCICor = 0.0F;/* '<S370>/Merge1' */
MONPRM volatile float32 ACCtl_tPsPTCISum = 0.0F;/* '<S366>/Switch1' */
MONPRM volatile float32 ACCtl_tPsPTCPCor = 0.0F;/* '<S369>/Merge' */
MONPRM volatile float32 ACCtl_tPsSetBasicEvap = 0.0F;/* '<S330>/Switch2' */
MONPRM volatile float32 ACCtl_tPsSetBasicPTC = 0.0F;/* '<S365>/Switch2' */
MONPRM volatile float32 ACCtl_tRightDuct = 0.0F;/* '<S175>/Switch1' */
MONPRM volatile float32 ACCtl_tRightSetPointModeCor = 0.0F;/* '<S185>/Sum3' */
MONPRM volatile float32 ACCtl_tSetPointEvap = 0.0F;/* '<S178>/Switch1' */
MONPRM volatile float32 ACCtl_tSetPointPTC = 0.0F;/* '<S338>/Switch2' */
MONPRM volatile float32 ACDVTPreSetSolarCor = 0.0F;
                                      /* '<S185>/cal_ACDVTPreSetSolarCor_MAP' */
MONPRM volatile float32 ACDVTPreSetSolarCorByVx = 0.0F;
                                  /* '<S185>/cal_ACDVTPreSetSolarCorByVx_MAP' */
MONPRM volatile float32 ACFanSpdSolarCor = 0.0F;/* '<S56>/cal_ACFanSpdSolarCor_MAP' */
MONPRM volatile float32 ACFanSpdSolarCorByEnv = 0.0F;
                                     /* '<S56>/cal_ACFanSpdSolarCorByEnv_MAP' */
MONPRM volatile boolean ACNvm_bACAutoSts = false;/* '<S3>/Data Type Conversion1' */
MONPRM volatile boolean ACNvm_bACOnOff = false;/* '<S3>/Data Type Conversion' */
MONPRM volatile uint8 ACNvm_eACCabinMode = ((uint8)0U);/* '<S3>/Index Vector4' */
MONPRM volatile uint8 ACNvm_eCabinBlower = ((uint8)0U);/* '<S3>/Index Vector5' */
MONPRM volatile uint8 ACNvm_eCabinSetTemp = ((uint8)0U);/* '<S3>/Index Vector2' */
MONPRM volatile uint8 ACNvm_eCainModeDoor = ((uint8)0U);/* '<S3>/Index Vector11' */
MONPRM volatile uint8 ACNvm_eCainRecDoor = ((uint8)0U);/* '<S3>/Index Vector10' */
MONPRM volatile float32 ACNvm_sACEnvTemp = -40.0F;/* '<S3>/Add' */
MONPRM volatile float32 ACNvm_sPCUInletTemp = -40.0F;/* '<S3>/Add1' */
MONPRM volatile float32 ACPTCDrDesCabinCor = 0.0F;/* '<S341>/cal_ACPTCDesCabinCor_CUR' */
MONPRM volatile float32 ACPTCDrDesEnvCor = 0.0F;/* '<S341>/cal_ACPTCDesEnvCor_MAP' */
MONPRM volatile float32 ACPTCDrDesFanCor = 0.0F;/* '<S341>/cal_ACPTCDesFanCor_CUR' */
MONPRM volatile float32 ACPTCPsDesCabinCor = 0.0F;/* '<S363>/cal_ACPTCPsDesCabinCor_CUR' */
MONPRM volatile float32 ACPTCPsDesEnvCor = 0.0F;/* '<S363>/cal_ACPTCPsDesEnvCor_MAP' */
MONPRM volatile float32 ACPTCPsDesFanCor = 0.0F;/* '<S363>/cal_ACPTCPsDesFanCor_CUR' */
MONPRM volatile float32 ACPTC_HeatedCond1 = 0.0F;/* '<S179>/Add3' */
MONPRM volatile float32 ACPTC_HeatingCond1 = 0.0F;/* '<S179>/Add' */
MONPRM volatile float32 ACPTC_HeatingCond2 = 0.0F;/* '<S179>/Add1' */
MONPRM volatile float32 ACPtc_CloseCond1 = 0.0F;/* '<S179>/Add2' */
MONPRM volatile float32 ACPwr_sPTCLmtPwrVal = 0.0F;/* '<S31>/Switch3' */
MONPRM volatile FaultStatus ACSen_eACCMHTSenSts = Normal;/* '<S1871>/Data Type Conversion' */
MONPRM volatile uint8 ACSen_eAirInletPer = ((uint8)0U);/* '<S1810>/Switch' */
MONPRM volatile FaultStatus ACSen_eCabinSenSts = Normal;/* '<S1756>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eChillerTSenSts = Normal;/* '<S1819>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eEVAPSurfTSenSts = Normal;/* '<S1837>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eEVAPTSenSts = Normal;/* '<S1827>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eEnvSenSts = Normal;/* '<S1089>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eFaceDuctSenSts = Normal;/* '<S1769>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eFootDuctSenSts = Normal;/* '<S1779>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eLPSenSts = Normal;/* '<S1744>/Data Type Conversion3' */
MONPRM volatile FaultStatus ACSen_eMOTORTSenSts = Normal;/* '<S1100>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eMixDoorSenSts = Normal;/* '<S1745>/Data Type Conversion3' */
MONPRM volatile FaultStatus ACSen_eModeSenSts = Normal;/* '<S1746>/Data Type Conversion3' */
MONPRM volatile FaultStatus ACSen_eOHXTSenSts = Normal;/* '<S1846>/Data Type Conversion' */
MONPRM volatile FaultStatus ACSen_eRecircSenSts = Normal;/* '<S1747>/Data Type Conversion3' */
MONPRM volatile FaultStatus ACSen_eSOLARSenSts = Normal;/* '<S1748>/Data Type Conversion3' */
MONPRM volatile FaultStatus ACSen_eWCCHPSenSts = Normal;/* '<S1754>/Data Type Conversion3' */
MONPRM volatile FaultStatus ACSen_eWCCHTSenSts = Normal;/* '<S1855>/Data Type Conversion' */
MONPRM volatile float32 ACSen_sACCMHiTempFilter = 0.0F;/* '<S1872>/Switch' */
MONPRM volatile float32 ACSen_sCabinTempFilter = 0.0F;/* '<S1757>/Switch' */
MONPRM volatile float32 ACSen_sChiTempFilter = 0.0F;/* '<S1818>/Switch' */
MONPRM volatile float32 ACSen_sEnvTAme = 0.0F;/* '<S1073>/cal_EnvTAme_CUR' */
MONPRM volatile float32 ACSen_sEnvTempCor = 0.0F;/* '<S1085>/Switch' */
MONPRM volatile float32 ACSen_sEnvTempFilter = 0.0F;/* '<S1095>/Switch' */
MONPRM volatile float32 ACSen_sEvapSurTemp = 0.0F;/* '<S1838>/Switch' */
MONPRM volatile float32 ACSen_sEvapTempFilter = 0.0F;/* '<S1828>/Switch' */
MONPRM volatile float32 ACSen_sFaceDuctTempFilter = 0.0F;/* '<S1770>/Switch' */
MONPRM volatile float32 ACSen_sFootDuctTempFilter = 0.0F;/* '<S1780>/Switch' */
MONPRM volatile float32 ACSen_sHiPressFilter = 0.0F;/* '<S1865>/Switch' */
MONPRM volatile float32 ACSen_sLoPressFilter = 0.0F;/* '<S1789>/Switch' */
MONPRM volatile float32 ACSen_sMixDoorPerc = 0.0F;/* '<S1796>/Switch' */
MONPRM volatile float32 ACSen_sModeMotorVol = 0.0F;/* '<S1803>/Switch' */
MONPRM volatile float32 ACSen_sMotTempFilter = 0.0F;/* '<S1098>/Switch' */
MONPRM volatile float32 ACSen_sOHXTempFilter = 0.0F;/* '<S1847>/Switch' */
MONPRM volatile float32 ACSen_sPressRateVal = 0.0F;/* '<S504>/Switch' */
MONPRM volatile float32 ACSen_sWCCHiTempFilter = 0.0F;/* '<S1857>/Switch' */
MONPRM volatile boolean ACTCrl_bEnvCOMPLmt = false;/* '<S500>/Switch1' */
MONPRM volatile boolean ACTCtl_bACCMCtlEnb = false;/* '<S460>/Switch' */
MONPRM volatile boolean ACTCtl_bAEXVDvtFlg = false;/* '<S682>/NOT' */
MONPRM volatile boolean ACTCtl_bAEXVEnb = false;/* '<S686>/Switch' */
MONPRM volatile boolean ACTCtl_bAEXVFaultFlg = false;/* '<S678>/OR' */
MONPRM volatile boolean ACTCtl_bAEXVInitFinishFlg = false;/* '<S695>/Compare' */
MONPRM volatile uint8 ACTCtl_bAEXVInitReq = ((uint8)0U);/* '<S696>/Switch' */
MONPRM volatile boolean ACTCtl_bAEXVPIEnble = false;/* '<S673>/AND' */
MONPRM volatile boolean ACTCtl_bAcPMPFaultFlg = false;/* '<S1036>/Switch' */
MONPRM volatile boolean ACTCtl_bAcPMPSpdFlt = false;/* '<S1022>/Switch1' */
MONPRM volatile boolean ACTCtl_bBCVlearnFlg = false;/* '<S664>/AND2' */
MONPRM volatile boolean ACTCtl_bBEXVDvtFlg = false;/* '<S753>/NOT' */
MONPRM volatile boolean ACTCtl_bBEXVEnb = false;/* '<S805>/Switch' */
MONPRM volatile boolean ACTCtl_bBEXVFaultFlg = false;/* '<S748>/OR' */
MONPRM volatile boolean ACTCtl_bBEXVInitFinishFlg = false;/* '<S763>/Compare' */
MONPRM volatile uint8 ACTCtl_bBEXVInitReq = ((uint8)0U);/* '<S764>/Switch' */
MONPRM volatile boolean ACTCtl_bBEXVPIEnble = false;/* '<S674>/AND' */
MONPRM volatile boolean ACTCtl_bBatPMPFaultFlg = false;/* '<S1052>/Switch' */
MONPRM volatile boolean ACTCtl_bBatPMPSpdFlt = false;/* '<S1023>/Switch1' */
MONPRM volatile uint8 ACTCtl_bBatTempDiff = ((uint8)0U);/* '<S651>/Switch' */
MONPRM volatile boolean ACTCtl_bCOMPDvtFlg = false;/* '<S453>/Relational Operator' */
MONPRM volatile boolean ACTCtl_bCOMPEnbDelay = false;/* '<S503>/Chart' */
MONPRM volatile boolean ACTCtl_bCOMPEnvpTPrtFlg = false;/* '<S457>/AND' */
MONPRM volatile boolean ACTCtl_bCOMPFaultClc = false;/* '<S497>/OR2' */
MONPRM volatile boolean ACTCtl_bCOMPForbidFlg = false;/* '<S449>/OR' */
MONPRM volatile boolean ACTCtl_bCOMPHPFrbFlg = false;/* '<S455>/Signal Copy3' */
MONPRM volatile boolean ACTCtl_bCOMPHPLmtFlg = false;/* '<S455>/Signal Copy2' */
MONPRM volatile uint8 ACTCtl_bCOMPIFreeFlag = ((uint8)0U);/* '<S481>/Merge' */
MONPRM volatile boolean ACTCtl_bCOMPLPFrbFlg = false;/* '<S455>/Signal Copy1' */
MONPRM volatile boolean ACTCtl_bCOMPLPLmtFlg = false;/* '<S455>/Signal Copy' */
MONPRM volatile boolean ACTCtl_bCOMPPIEnble = false;/* '<S456>/FFCal' */
MONPRM volatile boolean ACTCtl_bCOMPRealFault = false;/* '<S497>/OR1' */
MONPRM volatile boolean ACTCtl_bCOMPSpdDiffFlt = false;/* '<S451>/Chart' */
MONPRM volatile boolean ACTCtl_bCabinFltFlg = false;/* '<S1740>/Signal Copy1' */
MONPRM volatile boolean ACTCtl_bCtrlFPTCOnOrOffPwrDiff = false;/* '<S609>/Switch' */
MONPRM volatile boolean ACTCtl_bHPEXVDvtFlg = false;/* '<S824>/NOT' */
MONPRM volatile boolean ACTCtl_bHPEXVEnb = false;/* '<S836>/Switch' */
MONPRM volatile boolean ACTCtl_bHPEXVFaultFlg = false;/* '<S820>/OR' */
MONPRM volatile boolean ACTCtl_bHPEXVInitFinishFlg = false;/* '<S892>/Compare' */
MONPRM volatile uint8 ACTCtl_bHPEXVInitReq = ((uint8)0U);/* '<S893>/Switch' */
MONPRM volatile boolean ACTCtl_bHPEXVPIEnble = false;/* '<S675>/AND' */
MONPRM volatile boolean ACTCtl_bHiPressProFlg = false;/* '<S825>/Switch4' */
MONPRM volatile boolean ACTCtl_bLowPressProFlg = false;/* '<S825>/Switch5' */
MONPRM volatile boolean ACTCtl_bMCVlearnFlg = false;/* '<S642>/AND2' */
MONPRM volatile boolean ACTCtl_bMotPMPFaultFlg = false;/* '<S1066>/Switch' */
MONPRM volatile boolean ACTCtl_bMotPMPSpdFlt = false;/* '<S1024>/Chart' */
MONPRM volatile boolean ACTCtl_bOCOLmtFlg = false;/* '<S503>/AND1' */
MONPRM volatile boolean ACTCtl_bPTCOnOrOffPwrDiff = false;/* '<S592>/Switch' */
MONPRM volatile boolean ACTCtl_bPressProtectFlg = false;/* '<S504>/Multiport Switch' */
MONPRM volatile boolean ACTCtl_bPressRateFlg = false;/* '<S504>/Multiport Switch1' */
MONPRM volatile boolean ACTCtl_bSOVCmd = false;/* '<S446>/Multiport Switch' */
MONPRM volatile uint8 ACTCtl_eACPumpRefSpd = ((uint8)0U);/* '<S1022>/Multiport Switch' */
MONPRM volatile uint8 ACTCtl_eAcPMPSpdPerc = ((uint8)0U);/* '<S1035>/Switch' */
MONPRM volatile uint8 ACTCtl_eAcPMPSpdSet = ((uint8)0U);/* '<S1022>/Divide' */
MONPRM volatile uint8 ACTCtl_eBatPMPSpdSet = ((uint8)0U);/* '<S1023>/Divide' */
MONPRM volatile uint8 ACTCtl_eC3WVSLSts = ((uint8)0U);/* '<S660>/Switch' */
MONPRM volatile uint8 ACTCtl_eC3WVValue = ((uint8)0U);/* '<S639>/Switch' */
MONPRM volatile uint8 ACTCtl_eC5WVSLSts = ((uint8)0U);/* '<S670>/Switch' */
MONPRM volatile uint8 ACTCtl_eC5WVValue = ((uint8)0U);/* '<S640>/Switch' */
MONPRM volatile uint8 ACTCtl_eCOMPExhTPrtSts = ((uint8)0U);/* '<S457>/Chart' */
MONPRM volatile uint8 ACTCtl_eCOMPJudgeFlg = ((uint8)0U);/* '<S462>/Add' */
MONPRM volatile uint8 ACTCtl_eCOMPPrsPrtSts = ((uint8)0U);/* '<S455>/Add' */
MONPRM volatile uint8 ACTCtl_eCOMPSpdSecSts = ((uint8)0U);/* '<S533>/SecCal' */
MONPRM volatile uint8 ACTCtl_eCoolFanCtrl = ((uint8)0U);/* '<S915>/cal_CoolFanCtrl_MAP' */
MONPRM volatile uint8 ACTCtl_eEvapProSts = ((uint8)0U);/* '<S683>/EvapTemperature' */
MONPRM volatile uint8 ACTCtl_eFanPerc = ((uint8)0U);/* '<S921>/Switch' */
MONPRM volatile uint8 ACTCtl_eHeatFanCtrl = ((uint8)0U);/* '<S918>/cal_HeatFanCtrl_MAP' */
MONPRM volatile uint8 ACTCtl_eLessThanT1Sts = ((uint8)0U);/* '<S656>/Switch' */
MONPRM volatile uint8 ACTCtl_eMotPMPSpdSet = ((uint8)0U);/* '<S1024>/Divide' */
MONPRM volatile float32 ACTCtl_sACCMCtlFF = 0.0F;/* '<S456>/FFCal' */
MONPRM volatile float32 ACTCtl_sACCMCtlSpd = 0.0F;/* '<S451>/Switch2' */
MONPRM volatile float32 ACTCtl_sACCMI_Cor = 0.0F;/* '<S483>/Merge1' */
MONPRM volatile float32 ACTCtl_sACCMI_Sum = 0.0F;/* '<S480>/Switch1' */
MONPRM volatile float32 ACTCtl_sACCMPIVal = 0.0F;/* '<S481>/Merge' */
MONPRM volatile float32 ACTCtl_sACCMP_Cor = 0.0F;/* '<S482>/Merge' */
MONPRM volatile float32 ACTCtl_sAEXVActure = 0.0F;/* '<S673>/Signal Copy1' */
MONPRM volatile float32 ACTCtl_sAEXVCtrlBFF = 0.0F;/* '<S715>/cal_AEXVCtrlBFF_CUR' */
MONPRM volatile float32 ACTCtl_sAEXVCtrlFF = 0.0F;/* '<S677>/FFCal' */
MONPRM volatile float32 ACTCtl_sAEXVCtrlKi = 0.0F;/* '<S673>/Signal Copy3' */
MONPRM volatile float32 ACTCtl_sAEXVCtrlKp = 0.0F;/* '<S673>/Signal Copy2' */
MONPRM volatile float32 ACTCtl_sAEXVDvt = 0.0F;/* '<S682>/Switch1' */
MONPRM volatile float32 ACTCtl_sAEXVI_Cor = 0.0F;/* '<S700>/Merge1' */
MONPRM volatile float32 ACTCtl_sAEXVI_Sum = 0.0F;/* '<S697>/Switch1' */
MONPRM volatile float32 ACTCtl_sAEXVPI_Cor = 0.0F;/* '<S698>/Merge' */
MONPRM volatile float32 ACTCtl_sAEXVP_Cor = 0.0F;/* '<S699>/Merge' */
MONPRM volatile float32 ACTCtl_sAEXVPos = 0.0F;/* '<S741>/Switch2' */
MONPRM volatile float32 ACTCtl_sAEXVSetPoint = 0.0F;/* '<S673>/Signal Copy' */
MONPRM volatile float32 ACTCtl_sBEXVActure = 0.0F;/* '<S674>/Signal Copy1' */
MONPRM volatile float32 ACTCtl_sBEXVCtrlBFF = 0.0F;/* '<S783>/cal_BEXVCtrlBFF_CUR' */
MONPRM volatile float32 ACTCtl_sBEXVCtrlFF = 0.0F;/* '<S752>/FFCal' */
MONPRM volatile float32 ACTCtl_sBEXVCtrlKi = 0.0F;/* '<S674>/Signal Copy3' */
MONPRM volatile float32 ACTCtl_sBEXVCtrlKp = 0.0F;/* '<S674>/Signal Copy2' */
MONPRM volatile float32 ACTCtl_sBEXVDvt = 0.0F;/* '<S753>/Switch1' */
MONPRM volatile float32 ACTCtl_sBEXVI_Cor = 0.0F;/* '<S768>/Merge1' */
MONPRM volatile float32 ACTCtl_sBEXVI_Sum = 0.0F;/* '<S765>/Switch1' */
MONPRM volatile float32 ACTCtl_sBEXVPI_Cor = 0.0F;/* '<S766>/Merge' */
MONPRM volatile float32 ACTCtl_sBEXVP_Cor = 0.0F;/* '<S767>/Merge' */
MONPRM volatile float32 ACTCtl_sBEXVPos = 0.0F;/* '<S811>/Switch2' */
MONPRM volatile float32 ACTCtl_sBEXVSetPoint = 0.0F;/* '<S674>/Signal Copy' */
MONPRM volatile float32 ACTCtl_sBatHeatInletTrgT = 0.0F;/* '<S648>/Switch' */
MONPRM volatile float32 ACTCtl_sCOMPATNoiseBlwAndAccmSpd = 0.0F;/* '<S545>/cal_COMPATNoiseSpdLmt_MAP' */
MONPRM volatile float32 ACTCtl_sCOMPATNoiseLmtHVSSpd = 0.0F;
                                     /* '<S545>/cal_COMPATNoiseSpdLmtHVS_CUR' */
MONPRM volatile float32 ACTCtl_sCOMPATNoiseLmtSpd = 0.0F;/* '<S545>/Min' */
MONPRM volatile float32 ACTCtl_sCOMPActure = 0.0F;/* '<S440>/Signal Copy1' */
MONPRM volatile float32 ACTCtl_sCOMPCoolLmtSpd = 0.0F;/* '<S545>/Switch4' */
MONPRM volatile float32 ACTCtl_sCOMPCtrlAClsFF = 0.0F;/* '<S582>/cal_ACCMCtrlA2FF_MAP ' */
MONPRM volatile float32 ACTCtl_sCOMPCtrlKi = 0.0F;/* '<S440>/Signal Copy3' */
MONPRM volatile float32 ACTCtl_sCOMPCtrlKp = 0.0F;/* '<S440>/Signal Copy2' */
MONPRM volatile float32 ACTCtl_sCOMPDownSpd = 0.0F;/* '<S570>/Max1' */
MONPRM volatile float32 ACTCtl_sCOMPEnvLmtSpd = 0.0F;/* '<S546>/Switch' */
MONPRM volatile float32 ACTCtl_sCOMPFanlevelLmtSpd = 0.0F;/* '<S546>/cal_COMPFanLevelLmt_CUR' */
MONPRM volatile float32 ACTCtl_sCOMPHPLmtSpd = 0.0F;/* '<S545>/Switch' */
MONPRM volatile float32 ACTCtl_sCOMPLPLmtSpd = 0.0F;/* '<S545>/Switch2' */
MONPRM volatile float32 ACTCtl_sCOMPLmtMaxSpd = 0.0F;/* '<S450>/Min' */
MONPRM volatile float32 ACTCtl_sCOMPPCULimSpd = 0.0F;/* '<S545>/Multiport Switch' */
MONPRM volatile float32 ACTCtl_sCOMPSetPoint = 0.0F;/* '<S440>/Signal Copy' */
MONPRM volatile float32 ACTCtl_sChiSuperHeat = 0.0F;/* '<S676>/Add5' */
MONPRM volatile float32 ACTCtl_sChiSuperHeatAvg = 0.0F;/* '<S898>/Divide' */
MONPRM volatile float32 ACTCtl_sChiSuperHeatAvg1 = 0.0F;/* '<S907>/Sum1' */
MONPRM volatile float32 ACTCtl_sCondDep = 0.0F;/* '<S676>/Add' */
MONPRM volatile float32 ACTCtl_sCondDepAvg = 0.0F;/* '<S895>/Divide' */
MONPRM volatile float32 ACTCtl_sCondDepAvg1 = 0.0F;/* '<S901>/Sum1' */
MONPRM volatile float32 ACTCtl_sCondDepDiff = 0.0F;/* '<S715>/Add' */
MONPRM volatile float32 ACTCtl_sCoolCondDep = 0.0F;/* '<S676>/Add3' */
MONPRM volatile float32 ACTCtl_sCoolCondDepAvg = 0.0F;/* '<S896>/Divide' */
MONPRM volatile float32 ACTCtl_sCoolCondDepAvg1 = 0.0F;/* '<S903>/Sum1' */
MONPRM volatile float32 ACTCtl_sCtrlFPTCAuxHeatPwr = 0.0F;
                                    /* '<S587>/cal_CtrlFPTCAuxHeatPwrLmt_MAP' */
MONPRM volatile float32 ACTCtl_sDCoolBatTempDiff = 0.0F;/* '<S589>/Add2' */
MONPRM volatile float32 ACTCtl_sDCoolCabinTempDiff = 0.0F;/* '<S589>/Add3' */
MONPRM volatile float32 ACTCtl_sDvtCOMPCtrl = 0.0F;/* '<S453>/Switch1' */
MONPRM volatile float32 ACTCtl_sEvapSuperHeat = 0.0F;/* '<S676>/Add4' */
MONPRM volatile float32 ACTCtl_sEvapSuperHeatAvg = 0.0F;/* '<S897>/Divide' */
MONPRM volatile float32 ACTCtl_sEvapSuperHeatAvg1 = 0.0F;/* '<S905>/Sum1' */
MONPRM volatile float32 ACTCtl_sExhSuperHeat = 0.0F;/* '<S676>/Add2' */
MONPRM volatile float32 ACTCtl_sExhSuperHeatAvg = 0.0F;/* '<S899>/Divide' */
MONPRM volatile float32 ACTCtl_sExhSuperHeatAvg1 = 0.0F;/* '<S909>/Sum1' */
MONPRM volatile float32 ACTCtl_sHPEXVActure = 0.0F;/* '<S675>/Signal Copy1' */
MONPRM volatile float32 ACTCtl_sHPEXVCtrlADiff = 0.0F;/* '<S858>/Add' */
MONPRM volatile float32 ACTCtl_sHPEXVCtrlFF = 0.0F;/* '<S819>/FFCal' */
MONPRM volatile float32 ACTCtl_sHPEXVCtrlKi = 0.0F;/* '<S675>/Signal Copy3' */
MONPRM volatile float32 ACTCtl_sHPEXVCtrlKp = 0.0F;/* '<S675>/Signal Copy2' */
MONPRM volatile float32 ACTCtl_sHPEXVDvt = 0.0F;/* '<S824>/Switch1' */
MONPRM volatile float32 ACTCtl_sHPEXVI_Cor = 0.0F;/* '<S844>/Merge1' */
MONPRM volatile float32 ACTCtl_sHPEXVI_Sum = 0.0F;/* '<S841>/Switch1' */
MONPRM volatile float32 ACTCtl_sHPEXVPI_Cor = 0.0F;/* '<S842>/Merge' */
MONPRM volatile float32 ACTCtl_sHPEXVP_Cor = 0.0F;/* '<S843>/Merge' */
MONPRM volatile float32 ACTCtl_sHPEXVPos = 0.0F;/* '<S827>/Switch2' */
MONPRM volatile float32 ACTCtl_sHPEXVSetPoint = 0.0F;/* '<S822>/Switch' */
MONPRM volatile float32 ACTCtl_sHPEXVStepLmt = 0.0F;/* '<S828>/Switch' */
MONPRM volatile float32 ACTCtl_sPTCAuxHeatPwr = 0.0F;/* '<S582>/cal_PTCAuxHeatPwrLmt_MAP' */
MONPRM volatile float32 ACTCtl_sPTCBatHeatPwrLmt = 0.0F;/* '<S947>/cal_PTCBatHeatPwrLmt_CUR' */
MONPRM volatile uint8 ACTCtl_sPTCEnable = ((uint8)0U);/* '<S1013>/Switch' */
MONPRM volatile float32 ACTCtl_sPTCReqPower = 0.0F;/* '<S1020>/Switch' */
MONPRM volatile float32 ACTCtl_sPTCRequestTemp = 0.0F;/* '<S944>/Switch' */
MONPRM volatile float32 ACTCtl_sSOCHighPTCPwrLmt = 0.0F;/* '<S947>/cal_SOCHighPTCPwrLmt_CUR' */
MONPRM volatile float32 ACTCtl_sSuperHeat = 0.0F;/* '<S676>/Add1' */
MONPRM volatile float32 ACTCtl_sSuperHeatAvg = 0.0F;/* '<S900>/Divide' */
MONPRM volatile float32 ACTCtl_sSuperHeatAvg1 = 0.0F;/* '<S911>/Sum1' */
MONPRM volatile float32 ACTCtl_tCtrlADiff = 0.0F;/* '<S582>/Add1' */
MONPRM volatile float32 ACTCtl_tCtrlBDiff = 0.0F;/* '<S583>/Add' */
MONPRM volatile float32 ACTCtl_tCtrlCDiff = 0.0F;/* '<S584>/Add1' */
MONPRM volatile uint8 AC_BlowerFanSpeedMax = ((uint8)0U);/* '<S50>/MinMax' */
MONPRM volatile uint8 AC_BlowerFanSpeedMin = ((uint8)0U);/* '<S51>/Switch4' */
MONPRM volatile float32 AC_DVT2PTCErr = 0.0F;/* '<S50>/Add' */
MONPRM volatile float32 AC_DVTPreSetByEnv = 0.0F;/* '<S185>/cal_ACDVTPreSetByEnv_MAP' */
MONPRM volatile float32 AC_DrEvapDesFilter = 0.0F;
                                     /* '<S281>/cal_DrEvapDesFilterByDvt_CUR' */
MONPRM volatile uint8 AC_FanLeVel = ((uint8)0U);/* '<S42>/Merge' */
MONPRM volatile uint8 AC_FanLevelAct = ((uint8)0U);/* '<S42>/Merge' */
MONPRM volatile float32 AC_PidCabinT_UL = 0.0F;
                                    /* '<S187>/cal_DvtDesLmtByCabinTDiff_MAP' */
MONPRM volatile float32 AC_Ps2DrSetTempDvt = 0.0F;/* '<S182>/Sum2' */
MONPRM volatile float32 AC_PsEvapDesFilter = 0.0F;
                                     /* '<S306>/cal_PsEvapDesFilterByDvt_CUR' */
MONPRM volatile uint8 AC_rRecircInc = ((uint8)0U);/* '<S56>/Data Type Conversion' */
MONPRM volatile uint16 AC_rSolarRight = ((uint16)0U);/* '<S1813>/Switch' */
MONPRM volatile uint16 AC_rSunloadFlt = ((uint16)0U);/* '<S210>/Saturation' */
MONPRM volatile boolean AC_stExhaust = false;/* '<S4>/stExhaustFunCheck' */
MONPRM volatile boolean AC_stIGNON = false;/* '<S1291>/Switch1' */
MONPRM volatile float32 AC_tEnvInvent = 0.0F;/* '<S186>/TempRampBaseTimeAndStep' */
MONPRM volatile uint16 AC_tiAfterRun = ((uint16)0U);/* '<S1303>/Switch' */
MONPRM volatile uint8 AcPMP_HWVersion = ((uint8)0U);/* '<S16>/Signal Copy114' */
MONPRM volatile uint8 AcPMP_PartNumber = ((uint8)0U);/* '<S16>/Signal Copy113' */
MONPRM volatile uint8 AcPMP_ProjectCode1 = ((uint8)0U);/* '<S16>/Signal Copy110' */
MONPRM volatile uint8 AcPMP_ProjectCode2 = ((uint8)0U);/* '<S16>/Signal Copy111' */
MONPRM volatile boolean AcPMP_PumpDryRunningSta = false;/* '<S16>/Signal Copy105' */
MONPRM volatile uint8 AcPMP_PumpInputVolt = ((uint8)0U);/* '<S16>/Signal Copy108' */
MONPRM volatile uint8 AcPMP_PumpMotorSta = ((uint8)0U);/* '<S16>/Signal Copy104' */
MONPRM volatile uint8 AcPMP_PumpPowerSta = ((uint8)0U);/* '<S16>/Signal Copy106' */
MONPRM volatile uint8 AcPMP_PumpTempSta = ((uint8)0U);/* '<S16>/Signal Copy107' */
MONPRM volatile boolean AcPMP_RESP_ERROR = false;/* '<S16>/Signal Copy103' */
MONPRM volatile float32 AcPMP_RealRPM = 0.0F;/* '<S1281>/Gain' */
MONPRM volatile uint8 AcPMP_SWVersion_Main = ((uint8)0U);/* '<S16>/Signal Copy115' */
MONPRM volatile uint8 AcPMP_SWVersion_Patch = ((uint8)0U);/* '<S16>/Signal Copy117' */
MONPRM volatile uint8 AcPMP_SWVersion_Sub = ((uint8)0U);/* '<S16>/Signal Copy116' */
MONPRM volatile uint8 AcPMP_SupplierNumber = ((uint8)0U);/* '<S16>/Signal Copy112' */
MONPRM volatile uint8 BAT_EXV_CurrentInitState_B = ((uint8)0U);/* '<S18>/Signal Copy35' */
MONPRM volatile float32 BAT_EXV_CurrentPosition_B = 0.0F;/* '<S1283>/Gain' */
MONPRM volatile uint8 BAT_EXV_FaultState_B = ((uint8)0U);/* '<S18>/Signal Copy37' */
MONPRM volatile boolean BAT_EXV_ResponseError_B = false;/* '<S18>/Signal Copy34' */
MONPRM volatile boolean BAT_EXV_RunState_B = false;/* '<S18>/Signal Copy36' */
MONPRM volatile boolean BAT_EXV_SupplierLabel = false;/* '<S18>/Signal Copy40' */
MONPRM volatile uint8 BAT_EXV_TemperatureWarn_B = ((uint8)0U);/* '<S1283>/Data Type Conversion' */
MONPRM volatile uint8 BAT_EXV_VoltageState_B = ((uint8)0U);/* '<S18>/Signal Copy38' */
MONPRM volatile boolean BCV_ErrResp = false;/* '<S17>/Signal Copy73' */
MONPRM volatile uint8 BCV_FltSts = ((uint8)0U);/* '<S17>/Signal Copy66' */
MONPRM volatile uint8 BCV_Mode = ((uint8)0U);/* '<S17>/Signal Copy67' */
MONPRM volatile uint16 BCV_PosRec = ((uint16)0U);/* '<S17>/Signal Copy68' */
MONPRM volatile boolean BCV_RunSts = false;/* '<S17>/Signal Copy69' */
MONPRM volatile uint8 BCV_SpdLvl = ((uint8)0U);/* '<S17>/Signal Copy70' */
MONPRM volatile uint8 BCV_TempSts = ((uint8)0U);/* '<S17>/Signal Copy71' */
MONPRM volatile uint8 BCV_VoltSts = ((uint8)0U);/* '<S17>/Signal Copy72' */
MONPRM volatile float32 BMS_BatSOCAct_pct = 0.0F;/* '<S2>/Signal Copy1' */
MONPRM volatile float32 BMS_HVBatCellTempAve = 0.0F;/* '<S2>/Signal Copy159' */
MONPRM volatile float32 BMS_HVBatCellTempMax = 0.0F;/* '<S2>/Signal Copy160' */
MONPRM volatile float32 BMS_HVBatCellTempMin = 0.0F;/* '<S2>/Signal Copy161' */
MONPRM volatile float32 BMS_InletCooltActlTemp = 0.0F;/* '<S2>/Signal Copy147' */
MONPRM volatile boolean BatPMP_PumpDryRunningSta = false;/* '<S20>/Signal Copy91' */
MONPRM volatile uint8 BatPMP_PumpInputVolt = ((uint8)0U);/* '<S20>/Signal Copy94' */
MONPRM volatile uint8 BatPMP_PumpMotorSta = ((uint8)0U);/* '<S20>/Signal Copy90' */
MONPRM volatile uint8 BatPMP_PumpPowerSta = ((uint8)0U);/* '<S20>/Signal Copy92' */
MONPRM volatile uint8 BatPMP_PumpTempSta = ((uint8)0U);/* '<S20>/Signal Copy93' */
MONPRM volatile boolean BatPMP_RESP_ERROR = false;/* '<S20>/Signal Copy89' */
MONPRM volatile float32 BatPMP_RealRPM = 0.0F;/* '<S1284>/Gain' */
MONPRM volatile uint8 Bat_EXV_HWVersion = ((uint8)0U);/* '<S18>/Signal Copy46' */
MONPRM volatile uint8 Bat_EXV_PartNumber = ((uint8)0U);/* '<S18>/Signal Copy45' */
MONPRM volatile uint8 Bat_EXV_ProjectCode1 = ((uint8)0U);/* '<S18>/Signal Copy42' */
MONPRM volatile uint8 Bat_EXV_ProjectCode2 = ((uint8)0U);/* '<S18>/Signal Copy43' */
MONPRM volatile uint8 Bat_EXV_SWVersion_Main = ((uint8)0U);/* '<S18>/Signal Copy47' */
MONPRM volatile uint8 Bat_EXV_SWVersion_Patch = ((uint8)0U);/* '<S18>/Signal Copy49' */
MONPRM volatile uint8 Bat_EXV_SWVersion_Sub = ((uint8)0U);/* '<S18>/Signal Copy48' */
MONPRM volatile uint8 Bat_EXV_SupplierNumber = ((uint8)0U);/* '<S18>/Signal Copy44' */
MONPRM volatile boolean COMP_CANBusOff = false;/* '<S2>/Signal Copy118' */
MONPRM volatile boolean COMP_Commu_Error = false;/* '<S2>/Signal Copy120' */
MONPRM volatile boolean COMP_CurrentOffset = false;/* '<S2>/Signal Copy121' */
MONPRM volatile float32 COMP_EcompActSpd = 0.0F;/* '<S2>/Signal Copy122' */
MONPRM volatile uint8 COMP_EcompST = ((uint8)0U);/* '<S2>/Signal Copy123' */
MONPRM volatile float32 COMP_High_Voltage = 0.0F;/* '<S2>/Signal Copy124' */
MONPRM volatile uint8 COMP_HvError = ((uint8)0U);/* '<S2>/Signal Copy125' */
MONPRM volatile boolean COMP_IPM_Error = false;/* '<S2>/Signal Copy126' */
MONPRM volatile float32 COMP_InputCurrent = 0.0F;/* '<S2>/Signal Copy127' */
MONPRM volatile boolean COMP_LoseStep = false;/* '<S2>/Signal Copy128' */
MONPRM volatile uint8 COMP_LvError = ((uint8)0U);/* '<S2>/Signal Copy129' */
MONPRM volatile uint8 COMP_OverCurrent = ((uint8)0U);/* '<S2>/Signal Copy130' */
MONPRM volatile boolean COMP_OverDuty = false;/* '<S2>/Signal Copy131' */
MONPRM volatile boolean COMP_PI_Saturation = false;/* '<S2>/Signal Copy132' */
MONPRM volatile uint8 COMP_SelfCheckError = ((uint8)0U);/* '<S2>/Signal Copy134' */
MONPRM volatile boolean COMP_TempError = false;/* '<S2>/Signal Copy135' */
MONPRM volatile float32 COMP_Temperature = 0.0F;/* '<S2>/Signal Copy136' */
MONPRM volatile float32 CabinDesTempSolarCor = 0.0F;
                                     /* '<S185>/cal_CabinDesTempSolarCor_MAP' */
MONPRM volatile float32 CabinDesTempSolarCorECO = 0.0F;
                                  /* '<S185>/cal_CabinDesTempSolarCorECO_MAP' */
MONPRM volatile boolean CoAC_stColdStart = false;/* '<S1292>/Switch3' */
MONPRM volatile uint8 CoAC_stwork = ((uint8)0U);/* '<S30>/Switch1' */
MONPRM volatile float32 ColdPCUTempMinByEnv = 0.0F;
                                     /* '<S1072>/cal_ColdPCUTempMinByEnv_CUR' */
MONPRM volatile float32 ColdStartPCUTempMinByEnv = 0.0F;
                                /* '<S1299>/cal_ColdStartPCUTempMinByEnv_CUR' */
MONPRM volatile boolean ECUHighVoltInterlockSignal = false;/* '<S2>/Signal Copy137' */
MONPRM volatile float32 EE_PCUInletTemp = 0.0F;/* '<S1299>/Data Store Read1' */
MONPRM volatile uint8 EE_TimeDay = ((uint8)0U);/* '<S1300>/Data Store Read3' */
MONPRM volatile uint8 EE_TimeHour = ((uint8)0U);/* '<S1300>/Data Store Read' */
MONPRM volatile uint8 EE_TimeMin = ((uint8)0U);/* '<S1300>/Data Store Read2' */
MONPRM volatile float32 EE_tEnv = 0.0F;/* '<S1299>/Data Store Read' */
MONPRM volatile uint8 EXV_CurrentInitState = ((uint8)0U);/* '<S15>/Signal Copy97' */
MONPRM volatile float32 EXV_CurrentPosition = 0.0F;/* '<S1280>/Gain' */
MONPRM volatile uint8 EXV_FaultState = ((uint8)0U);/* '<S15>/Signal Copy99' */
MONPRM volatile boolean EXV_ResponseError = false;/* '<S15>/Signal Copy96' */
MONPRM volatile boolean EXV_RunState = false;/* '<S15>/Signal Copy98' */
MONPRM volatile uint8 EXV_TemperatureWarn = ((uint8)0U);/* '<S15>/Signal Copy101' */
MONPRM volatile uint8 EXV_VoltageState = ((uint8)0U);/* '<S15>/Signal Copy100' */
MONPRM volatile float32 Eva_CloseCond1 = 0.0F;/* '<S178>/Add2' */
MONPRM volatile float32 Eva_CooledCond1 = 0.0F;/* '<S178>/Add3' */
MONPRM volatile float32 Eva_CoolingCond1 = 0.0F;/* '<S178>/Add' */
MONPRM volatile float32 Eva_CoolingCond2 = 0.0F;/* '<S178>/Add1' */
MONPRM volatile float32 EvapDesTempDrCabinCor = 0.0F;
                                      /* '<S282>/cal_EvapDesTempCabinCor_CUR' */
MONPRM volatile float32 EvapDesTempDrEnvCor = 0.0F;/* '<S282>/cal_EvapDesTempEnvCor_MAP' */
MONPRM volatile float32 EvapDesTempDrFanCor = 0.0F;/* '<S282>/cal_EvapDesTempFanCor_CUR' */
MONPRM volatile float32 EvapDesTempPsCabinCor = 0.0F;
                                    /* '<S307>/cal_EvapDesTempPsCabinCor_CUR' */
MONPRM volatile float32 EvapDesTempPsEnvCor = 0.0F;
                                      /* '<S307>/cal_EvapDesTempPsEnvCor_MAP' */
MONPRM volatile float32 EvapDesTempPsFanCor = 0.0F;
                                      /* '<S307>/cal_EvapDesTempPsFanCor_CUR' */
MONPRM volatile uint16 GlbDa_LeftSolar = ((uint16)0U);/* '<S181>/Data Type Conversion1' */
MONPRM volatile uint16 GlbDa_LeftSolarAvr = ((uint16)0U);/* '<S56>/Add1' */
MONPRM volatile uint16 GlbDa_RightSolar = ((uint16)0U);/* '<S182>/Data Type Conversion' */
MONPRM volatile uint16 GlbDa_Solar = ((uint16)0U);/* '<S279>/Max1' */
MONPRM volatile float32 GlbDa_tCabinInvent = 0.0F;/* '<S176>/Switch2' */
MONPRM volatile uint16 GlbDa_uBat = ((uint16)1200U);/* '<S2>/Constant2' */
MONPRM volatile boolean HMICtl_bACAuto = false;/* '<S1183>/Switch' */
MONPRM volatile boolean HMICtl_bACDefrost = false;/* '<S1197>/Switch' */
MONPRM volatile boolean HMICtl_bACOnOff = false;/* '<S1209>/Switch' */
MONPRM volatile boolean HMICtl_bLeftSetHigh = false;/* '<S1163>/Switch' */
MONPRM volatile boolean HMICtl_bLeftSetLow = false;/* '<S1164>/Switch' */
MONPRM volatile uint8 HMICtl_eACSts = ((uint8)0U);/* '<S1221>/Switch' */
MONPRM volatile uint8 HMICtl_eBlwSts = ((uint8)0U);/* '<S1129>/Switch' */
MONPRM volatile uint8 HMICtl_eInner = ((uint8)0U);/* '<S1145>/Switch' */
MONPRM volatile uint8 HMICtl_eModeMotor = ((uint8)0U);/* '<S1152>/Switch' */
MONPRM volatile float32 HMICtl_sLeftSetPoint = 0.0F;/* '<S1165>/Switch' */
MONPRM volatile float32 HMICtl_sMixDoor = 0.0F;/* '<S1147>/Switch' */
MONPRM volatile float32 HP_EXV_CurrentPosition_B = 0.0F;/* '<S1285>/Gain' */
MONPRM volatile uint8 HP_EXV_FaultState_B = ((uint8)0U);/* '<S22>/Signal Copy23' */
MONPRM volatile uint8 HP_EXV_HWVersion = ((uint8)0U);/* '<S22>/Signal Copy30' */
MONPRM volatile uint8 HP_EXV_PartNumber = ((uint8)0U);/* '<S22>/Signal Copy29' */
MONPRM volatile uint8 HP_EXV_ProjectCode1 = ((uint8)0U);/* '<S22>/Signal Copy26' */
MONPRM volatile uint8 HP_EXV_ProjectCode2 = ((uint8)0U);/* '<S22>/Signal Copy27' */
MONPRM volatile boolean HP_EXV_ResponseError_B = false;/* '<S22>/Signal Copy21' */
MONPRM volatile boolean HP_EXV_RunState_B = false;/* '<S22>/Signal Copy22' */
MONPRM volatile uint8 HP_EXV_SWVersion_Main = ((uint8)0U);/* '<S22>/Signal Copy31' */
MONPRM volatile uint8 HP_EXV_SWVersion_Patch = ((uint8)0U);/* '<S22>/Signal Copy33' */
MONPRM volatile uint8 HP_EXV_SWVersion_Sub = ((uint8)0U);/* '<S22>/Signal Copy32' */
MONPRM volatile boolean HP_EXV_SupplierLabel = false;/* '<S22>/Signal Copy19' */
MONPRM volatile uint8 HP_EXV_SupplierNumber = ((uint8)0U);/* '<S22>/Signal Copy28' */
MONPRM volatile uint8 HP_EXV_VoltageState_B = ((uint8)0U);/* '<S22>/Signal Copy24' */
MONPRM volatile boolean HP_EXV_Warning_OverTemp = false;/* '<S22>/Signal Copy20' */
MONPRM volatile uint8 HP_EXV_initialize_status = ((uint8)0U);/* '<S22>/Signal Copy18' */
MONPRM volatile uint8 HU_LeftTempSet = ((uint8)0U);/* '<S2>/Signal Copy200' */
MONPRM volatile uint8 IOCtl_BloweFanSpeed = ((uint8)0U);/* '<S1242>/Switch' */
MONPRM volatile boolean IOCtl_PwrNmReqFlg = false;/* '<S1228>/Relational Operator' */
MONPRM volatile uint8 IOCtl_RecircTrgPos = ((uint8)0U);/* '<S1261>/Switch' */
MONPRM volatile boolean IOCtl_bModeMoveSts = false;/* '<S1234>/Signal Copy' */
MONPRM volatile float32 IOCtl_sMixDoorTrgPos = 0.0F;/* '<S1268>/Switch' */
MONPRM volatile float32 IOCtl_sModeMotorTrgPos = 0.0F;/* '<S1273>/Switch' */
MONPRM volatile boolean MCV_ErrResp = false;/* '<S24>/Signal Copy57' */
MONPRM volatile uint8 MCV_FltSts = ((uint8)0U);/* '<S24>/Signal Copy50' */
MONPRM volatile uint8 MCV_Mode = ((uint8)0U);/* '<S24>/Signal Copy51' */
MONPRM volatile uint16 MCV_PosRec = ((uint16)0U);/* '<S24>/Signal Copy52' */
MONPRM volatile boolean MCV_RunSts = false;/* '<S24>/Signal Copy53' */
MONPRM volatile uint8 MCV_SpdLvl = ((uint8)0U);/* '<S24>/Signal Copy54' */
MONPRM volatile uint8 MCV_TempSts = ((uint8)0U);/* '<S24>/Signal Copy55' */
MONPRM volatile uint8 MCV_VoltSts = ((uint8)0U);/* '<S24>/Signal Copy56' */
MONPRM volatile boolean MotPMP_PumpDryRunningSta = false;/* '<S25>/Signal Copy84' */
MONPRM volatile uint8 MotPMP_PumpInputVolt = ((uint8)0U);/* '<S25>/Signal Copy87' */
MONPRM volatile uint8 MotPMP_PumpMotorSta = ((uint8)0U);/* '<S25>/Signal Copy83' */
MONPRM volatile uint8 MotPMP_PumpPowerSta = ((uint8)0U);/* '<S25>/Signal Copy85' */
MONPRM volatile uint8 MotPMP_PumpTempSta = ((uint8)0U);/* '<S25>/Signal Copy86' */
MONPRM volatile boolean MotPMP_RESP_ERROR = false;/* '<S25>/Signal Copy82' */
MONPRM volatile float32 MotPMP_RealRPM = 0.0F;/* '<S1287>/Gain' */
MONPRM volatile float32 PCU_StartClntTemp = 0.0F;/* '<S1299>/Data Type Conversion' */
MONPRM volatile float32 PCUtempOffset2ShutByEnv = 0.0F;
                                 /* '<S1299>/cal_PCUtempOffset2ShutByEnv_CUR' */
MONPRM volatile boolean PWRCtl_bKL15swtSt = false;/* '<S2>/OR' */
MONPRM volatile uint8 PWRCtl_eBatChargSts = ((uint8)0U);/* '<S30>/CoBatCharg' */
MONPRM volatile PwrModes PWRCtl_eTMSStatus = PwrOff;/* '<S1296>/Switch' */
MONPRM volatile uint8 PWRCtl_eVCUPTSts = ((uint8)0U);/* '<S2>/Signal Copy183' */
MONPRM volatile float32 PWRCtl_sCOMPActlPwr = 0.0F;/* '<S31>/Divide1' */
MONPRM volatile float32 PWRCtl_sLmtPwrCOMP = 0.0F;/* '<S31>/Min' */
MONPRM volatile uint32 PWRCtl_uTMSRunTimer = 0U;/* '<S30>/Cal_RunTime' */
MONPRM volatile uint32 PWRCtl_uTMSRunTimer20ms = 0U;/* '<S33>/Cal_RunTime_20ms' */
MONPRM volatile float32 PidCabinX_IsumMax = 0.0F;
                                   /* '<S187>/cal_PidCabinX_IsumMaxByDVT_CUR' */
MONPRM volatile float32 PidCabinX_IsumMin = 0.0F;
                                   /* '<S187>/cal_PidCabinX_IsumMinByDVT_CUR' */
MONPRM volatile uint16 SENCtl_uACCMHighTempVol = ((uint16)0U);/* '<S1755>/C Caller' */
MONPRM volatile uint16 SENCtl_uCabinVoltage = ((uint16)0U);/* '<S1740>/C Caller' */
MONPRM volatile uint16 SENCtl_uChillTempVol = ((uint16)0U);/* '<S1749>/C Caller' */
MONPRM volatile uint16 SENCtl_uEVAPSurfTempVol = ((uint16)0U);/* '<S1751>/C Caller' */
MONPRM volatile uint16 SENCtl_uEVAPXTempVol = ((uint16)0U);/* '<S1750>/C Caller' */
MONPRM volatile uint16 SENCtl_uEnvVoltage = ((uint16)0U);/* '<S1074>/C Caller' */
MONPRM volatile uint16 SENCtl_uFaceDuctVal = ((uint16)0U);/* '<S1742>/C Caller' */
MONPRM volatile uint16 SENCtl_uFootDuctVal = ((uint16)0U);/* '<S1743>/C Caller' */
MONPRM volatile uint16 SENCtl_uMixDoorVol = ((uint16)0U);/* '<S1745>/C Caller' */
MONPRM volatile uint16 SENCtl_uModeDoorVol = ((uint16)0U);/* '<S1746>/C Caller' */
MONPRM volatile uint16 SENCtl_uMotInletTempVol = ((uint16)0U);/* '<S1075>/C Caller' */
MONPRM volatile uint16 SENCtl_uOHXTempVol = ((uint16)0U);/* '<S1752>/C Caller' */
MONPRM volatile uint16 SENCtl_uRecircDoorVol = ((uint16)0U);/* '<S1747>/C Caller' */
MONPRM volatile uint16 SENCtl_uSolorVol = ((uint16)0U);/* '<S1748>/C_Caller' */
MONPRM volatile uint16 SENCtl_uWCCHPVol = ((uint16)0U);/* '<S1754>/C Caller' */
MONPRM volatile uint16 SENCtl_uWCCHighTempVol = ((uint16)0U);/* '<S1753>/C Caller' */
MONPRM volatile uint16 SENCtl_uWCCLPVol = ((uint16)0U);/* '<S1744>/C Caller' */
MONPRM volatile float32 SEN_ACCMTHiRaw = 0.0F;/* '<S1755>/cal_ACCMTHi_CUR' */
MONPRM volatile float32 SEN_ChiTRaw = 0.0F;/* '<S1749>/cal_TChillOutRaw_CUR' */
MONPRM volatile float32 SEN_EvapTRaw = 0.0F;/* '<S1750>/cal_TEvapOutRaw_CUR' */
MONPRM volatile float32 SEN_LoPressRaw = 0.0F;/* '<S1744>/cal_LoPress_CUR' */
MONPRM volatile float32 SEN_MixDoorRaw = 0.0F;/* '<S1745>/cal_MixDoorPerc_CUR' */
MONPRM volatile float32 SEN_OHXTRaw = 0.0F;/* '<S1752>/cal_OHXTRaw_CUR' */
MONPRM volatile uint16 SEN_SolarRaw = ((uint16)0U);/* '<S1748>/cal_SolarValRaw_CUR' */
MONPRM volatile float32 SEN_TCabinRaw = 0.0F;/* '<S1740>/cal_TCabinRaw_CUR' */
MONPRM volatile float32 SEN_TDuctRaw = 0.0F;/* '<S1742>/cal_TDuctRaw_CUR' */
MONPRM volatile float32 SEN_TEnvRaw = 0.0F;/* '<S1074>/cal_TEnvRaw_CUR' */
MONPRM volatile float32 SEN_TEvapSurRaw = 0.0F;/* '<S1751>/cal_TEvapSur_CUR' */
MONPRM volatile float32 SEN_TFootDuctRaw = 0.0F;/* '<S1743>/cal_TDuctRaw_CUR' */
MONPRM volatile float32 SEN_TMotRaw = 0.0F;/* '<S1075>/cal_TMot_CUR' */
MONPRM volatile float32 SEN_WCCHiPressRaw = 0.0F;/* '<S1754>/cal_LCCOutHiPressRaw_CUR' */
MONPRM volatile float32 SEN_WCCTHiRaw = 0.0F;/* '<S1753>/cal_WCCTHiRaw_CUR' */
MONPRM volatile boolean SOMCtl_bB1toB31 = false;/* '<S1325>/Switch1' */
MONPRM volatile boolean SOMCtl_bBatB1TB41Flg = false;/* '<S1486>/OR2' */
MONPRM volatile boolean SOMCtl_bBatB1TB42Flg = false;/* '<S1499>/OR2' */
MONPRM volatile boolean SOMCtl_bBatBalEntBFlg = false;/* '<S1634>/AND1' */
MONPRM volatile boolean SOMCtl_bBatBalFlg = false;/* '<S1318>/Judge' */
MONPRM volatile boolean SOMCtl_bBatCoolFlg = false;/* '<S1397>/Switch' */
MONPRM volatile boolean SOMCtl_bBatHStrFlg = false;/* '<S1575>/Chart' */
MONPRM volatile boolean SOMCtl_bBatHeatB31tB1Flg = false;/* '<S1578>/AND3' */
MONPRM volatile boolean SOMCtl_bBatHeatB3tB1Flg = false;/* '<S1325>/Switch' */
MONPRM volatile boolean SOMCtl_bBatHeatChrgFlgAB = false;/* '<S1482>/AND2' */
MONPRM volatile boolean SOMCtl_bBatHeatChrgFlgCD = false;/* '<S1483>/NOT' */
MONPRM volatile boolean SOMCtl_bBatHeatFlg = false;/* '<S1480>/Switch' */
MONPRM volatile boolean SOMCtl_bBatHeatOffFlg = false;/* '<S1510>/Relational Operator' */
MONPRM volatile boolean SOMCtl_bBatHeatPwrLmtF = false;/* '<S1485>/Relational Operator' */
MONPRM volatile boolean SOMCtl_bBatHeatTempDiffE = false;/* '<S1492>/Compare' */
MONPRM volatile boolean SOMCtl_bBatLTRFlg = false;/* '<S1320>/Switch' */
MONPRM volatile boolean SOMCtl_bBatLTROffFlg = false;/* '<S1440>/AND7' */
MONPRM volatile boolean SOMCtl_bBatTSEntAFlg = false;/* '<S1358>/AND1' */
MONPRM volatile boolean SOMCtl_bBatTSEntBFlg = false;/* '<S1359>/AND1' */
MONPRM volatile boolean SOMCtl_bBatTSExitFlg = false;/* '<S1338>/AND1' */
MONPRM volatile boolean SOMCtl_bCalTempBatHeatFlg = false;/* '<S1481>/Merge' */
MONPRM volatile boolean SOMCtl_bDBatLTROffFlg = false;/* '<S1542>/AND7' */
MONPRM volatile boolean SOMCtl_bDCBatLTROnFlg = false;/* '<S1439>/AND1' */
MONPRM volatile boolean SOMCtl_bEntExtDefFlg = false;/* '<S1729>/AND' */
MONPRM volatile boolean SOMCtl_bExitExtDefTempFlg = false;/* '<S1734>/Compare' */
MONPRM volatile boolean SOMCtl_bExtDefFlg = false;/* '<S1732>/Switch' */
MONPRM volatile boolean SOMCtl_bMD1CLMSts = false;/* '<S1678>/Chart' */
MONPRM volatile boolean SOMCtl_bMD1ToMD2Flg = false;/* '<S1677>/C' */
MONPRM volatile boolean SOMCtl_bMD2DHMD1Flg = false;/* '<S1679>/MD2_DHMD1' */
MONPRM volatile boolean SOMCtl_bMD2ToMD1Flg = false;/* '<S1677>/OR7' */
MONPRM volatile boolean SOMCtl_bMD2ToMD3Flg = false;/* '<S1680>/B' */
MONPRM volatile boolean SOMCtl_bMD3DHMD2Flg = false;/* '<S1681>/MD3_DHMD2' */
MONPRM volatile boolean SOMCtl_bMD3ToMD2Flg = false;/* '<S1680>/A' */
MONPRM volatile boolean SOMCtl_bMD3ToMD4Flg = false;/* '<S1682>/B' */
MONPRM volatile boolean SOMCtl_bMD4ToMD3Flg = false;/* '<S1682>/A' */
MONPRM volatile boolean SOMCtl_bMotAndBatLTRFlg = false;/* '<S1324>/Switch' */
MONPRM volatile boolean SOMCtl_bMotHeatBatFlg = false;/* '<S1326>/Switch' */
MONPRM volatile boolean SOMCtl_bMotLTRAndBatBalOffFlg = false;/* '<S1633>/Relational Operator' */
MONPRM volatile boolean SOMCtl_bMotLTRAndBatBalOn1Flg = false;/* '<S1541>/Relational Operator' */
MONPRM volatile boolean SOMCtl_bMotLTRAndBatBalOn2Flg = false;/* '<S1541>/Relational Operator1' */
MONPRM volatile boolean SOMCtl_bMotorHeatBatOffFlg = false;/* '<S1613>/Relational Operator' */
MONPRM volatile boolean SOMCtl_bMotorHeatBatOnFlg = false;/* '<S1326>/Switch2' */
MONPRM volatile boolean SOMCtl_bMotorLTRAndBatBalFlg = false;/* '<S1327>/Switch' */
MONPRM volatile boolean SOMCtl_bNmlBatLTROnFlg = false;/* '<S1439>/Relational Operator' */
MONPRM volatile uint8 SOMCtl_eBatBalEntBFlg = ((uint8)0U);/* '<S1634>/Add' */
MONPRM volatile uint8 SOMCtl_eBatCoolB1tB21 = ((uint8)0U);/* '<S1402>/Add' */
MONPRM volatile uint8 SOMCtl_eBatCoolB1tB22 = ((uint8)0U);/* '<S1413>/Add' */
MONPRM volatile uint8 SOMCtl_eBatCoolB2tB1 = ((uint8)0U);/* '<S1423>/Add' */
MONPRM volatile uint8 SOMCtl_eBatHeatOffVal = ((uint8)0U);/* '<S1510>/Add' */
MONPRM volatile uint8 SOMCtl_eBatLTROnFlg = ((uint8)0U);/* '<S1637>/Add' */
MONPRM volatile BatModes SOMCtl_eBatMode = Off;/* '<S1475>/Switch' */
MONPRM volatile CabinMode SOMCtl_eCabinMode = CabinMode_MD_Off;/* '<S1727>/Switch' */
MONPRM volatile CabinMode SOMCtl_eCabinModePre = CabinMode_MD_Off;/* '<S1684>/Data Type Conversion2' */
MONPRM volatile uint8 SOMCtl_eHVPartMode = ((uint8)0U);/* '<S1735>/Switch' */
MONPRM volatile uint8 SOMCtl_eMotLTRAndBatBalOffFlg = ((uint8)0U);/* '<S1633>/Add' */
MONPRM volatile uint8 SOMCtl_eMotLTRAndBatBalOn1Flg = ((uint8)0U);/* '<S1541>/Add' */
MONPRM volatile uint8 SOMCtl_eMotLTRAndBatBalOn2Flg = ((uint8)0U);/* '<S1541>/Add1' */
MONPRM volatile uint8 SOMCtl_eMotorHeatBat2Flg = ((uint8)0U);/* '<S1611>/Add' */
MONPRM volatile uint8 SOMCtl_eMotorHeatBatFlg = ((uint8)0U);/* '<S1612>/Add' */
MONPRM volatile uint16 SOMCtl_eMotorHeatBatOffFlg = ((uint16)0U);/* '<S1613>/Add' */
MONPRM volatile uint8 SOMCtl_eNmlBatLTROnFlg = ((uint8)0U);/* '<S1439>/Add' */
MONPRM volatile RefModes SOMCtl_eRefModes = RefModes_Ref_Off;/* '<S1736>/Switch' */
MONPRM volatile WaterModes SOMCtl_eWaterMode = WaterOff;/* '<S1728>/Switch' */
MONPRM volatile float32 SOMCtl_sBatHeatPTCTrgT = 0.0F;/* '<S1533>/Switch' */
MONPRM volatile float32 SOMCtl_sBatHeatT1 = 0.0F;/* '<S1481>/Merge' */
MONPRM volatile float32 SOMCtl_sBatHeatT2 = 0.0F;/* '<S1481>/Merge' */
MONPRM volatile float32 SOMCtl_sBatHeatTrgTempComp = 0.0F;
                                      /* '<S1533>/cal_BatHeatTrgTempComp_CUR' */
MONPRM volatile float32 SOMCtl_sBatTrgTemp = 0.0F;/* '<S1330>/Switch' */
MONPRM volatile float32 SOMCtl_sF1Value = 0.0F;/* '<S1676>/Add' */
MONPRM volatile float32 SOMCtl_sF2Value = 0.0F;/* '<S1676>/Add1' */
MONPRM volatile boolean SOMCtrl_bBatLTRDelayFlg = false;/* '<S1440>/Delay' */
MONPRM volatile uint8 TMS_VersionNumber = ((uint8)22U);/* '<S8>/Constant1' */
MONPRM volatile float32 ThCo_rSetLeftMixDoor = 0.0F;/* '<S388>/Switch3' */
MONPRM volatile float32 ThCo_rSetRightMixDoor = 0.0F;/* '<S388>/Switch2' */
MONPRM volatile uint16 adc2_group0_0 = ((uint16)0U);/* '<S1739>/Signal Copy' */
MONPRM volatile uint16 adc2_group0_1 = ((uint16)0U);/* '<S1739>/Signal Copy1' */
MONPRM volatile uint16 adc2_group0_2 = ((uint16)0U);/* '<S1739>/Signal Copy2' */
MONPRM volatile uint16 adc2_group1_0 = ((uint16)0U);/* '<S1739>/Signal Copy3' */
MONPRM volatile uint16 adc2_group1_1 = ((uint16)0U);/* '<S1739>/Signal Copy4' */
MONPRM volatile uint16 adc2_group1_2 = ((uint16)0U);/* '<S1739>/Signal Copy5' */
MONPRM volatile uint16 adc2_group1_3 = ((uint16)0U);/* '<S1739>/Signal Copy6' */
MONPRM volatile uint16 adc2_group1_4 = ((uint16)0U);/* '<S1739>/Signal Copy7' */
MONPRM volatile uint16 adc2_group1_5 = ((uint16)0U);/* '<S1739>/Signal Copy8' */
MONPRM volatile uint16 adc2_group1_6 = ((uint16)0U);/* '<S1739>/Signal Copy9' */
MONPRM volatile uint16 adc2_group1_7 = ((uint16)0U);/* '<S1739>/Signal Copy10' */
MONPRM volatile uint16 adc2_group1_8 = ((uint16)0U);/* '<S1739>/Signal Copy11' */
MONPRM volatile uint16 adc2_group1_9 = ((uint16)0U);/* '<S1739>/Signal Copy12' */
MONPRM volatile uint16 adc2_group2_0 = ((uint16)0U);/* '<S1739>/Signal Copy17' */
MONPRM volatile uint16 adc2_group2_1 = ((uint16)0U);/* '<S1739>/Signal Copy18' */
MONPRM volatile uint16 adc2_group2_2 = ((uint16)0U);/* '<S1739>/Signal Copy19' */
MONPRM volatile uint16 adc2_group2_3 = ((uint16)0U);/* '<S1739>/Signal Copy13' */
MONPRM volatile uint16 adc2_group2_4 = ((uint16)0U);/* '<S1739>/Signal Copy14' */

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
