/*
 * File: monPrmsIpm.c
 *
 * Code generated for Simulink model 'AppSwcIpm'.
 *
 * Model version                  : 9.219
 * Simulink Coder version         : 9.8 (R2022b) 13-May-2022
 * C/C++ source code generated on : Wed Nov 13 16:55:17 2024
 *
 * Target selection: autosar.tlc
 * Embedded hardware selection: NXP->Cortex-M4
 * Code generation objectives: Unspecified
 * Validation result: Not run
 */

#include "monPrmsIpm.h"
#include "AppSwcIpm.h"

/* Exported data definition */

/* Volatile memory section */
#include "XcpTest_types.h"

/* Definition for custom storage class: Volatile */
MONPRM volatile boolean VIPM_ACCMLostComm_flg = false;/* '<S384>/Switch14' */
MONPRM volatile boolean VIPM_APPVerMaxVld_flg = false;/* '<S15>/Logical Operator3' */
MONPRM volatile uint8 VIPM_APPVerMax_enum = ((uint8)0U);/* '<S15>/Switch4' */
MONPRM volatile boolean VIPM_APPVerMinVld_flg = false;/* '<S16>/Logical Operator3' */
MONPRM volatile uint8 VIPM_APPVerMin_enum = ((uint8)0U);/* '<S16>/Switch4' */
MONPRM volatile boolean VIPM_BACCANBusOff_flg = false;/* '<S384>/Switch2' */
MONPRM volatile boolean VIPM_BMSACChrgAtclStaVld_flg = false;/* '<S324>/Logical Operator3' */
MONPRM volatile EnumBMSACChrgSt VIPM_BMSACChrgAtclSta_enum =
  EnumBMSACChrgSt_ChrgOff;             /* '<S324>/Switch4' */
MONPRM volatile boolean VIPM_BMSActExchgCurntVld_flg = false;/* '<S306>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSActExchgCurnt_A = 0.0F;/* '<S306>/MinMax1' */
MONPRM volatile boolean VIPM_BMSBatCapctyVld_flg = false;/* '<S169>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BMSBatCapcty_Ah = ((uint8)0U);/* '<S169>/Switch4' */
MONPRM volatile boolean VIPM_BMSBatSOCActVld_flg = false;/* '<S315>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSBatSOCAct_pct = 0.0F;/* '<S315>/MinMax1' */
MONPRM volatile boolean VIPM_BMSBatSOCRptVld_flg = false;/* '<S316>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSBatSOCRpt_pct = 0.0F;/* '<S316>/MinMax1' */
MONPRM volatile boolean VIPM_BMSBatSOHVld_flg = false;/* '<S317>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSBatSOH_pct = 0.0F;/* '<S317>/MinMax1' */
MONPRM volatile boolean VIPM_BMSCellVoltMaxVld_flg = false;/* '<S343>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSCellVoltMax_mV = 0.0F;/* '<S343>/MinMax1' */
MONPRM volatile boolean VIPM_BMSCellVoltMinVld_flg = false;/* '<S344>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSCellVoltMin_mV = 0.0F;/* '<S344>/MinMax1' */
MONPRM volatile boolean VIPM_BMSChrgInterlockStaVld_flg = false;/* '<S307>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BMSChrgInterlockSta_enum = ((uint8)0U);/* '<S307>/Switch4' */
MONPRM volatile boolean VIPM_BMSDCSActOprtModeVld_flg = false;/* '<S304>/Logical Operator3' */
MONPRM volatile EnumBMSDCSMd VIPM_BMSDCSActOprtMode_enum = EnumBMSDCSMd_OFF;/* '<S304>/Switch4' */
MONPRM volatile boolean VIPM_BMSDCSChrgReqVld_flg = false;/* '<S323>/Logical Operator3' */
MONPRM volatile boolean VIPM_BMSDCSChrgReq_flg = false;/* '<S323>/Switch4' */
MONPRM volatile boolean VIPM_BMSDCSInletConnectStaVld_flg = false;/* '<S305>/Logical Operator3' */
MONPRM volatile boolean VIPM_BMSDCSInletConnectSta_flg = false;/* '<S305>/Switch4' */
MONPRM volatile boolean VIPM_BMSDchrgInterlockStaVld_flg = false;/* '<S308>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BMSDchrgInterlockSta_enum = ((uint8)0U);/* '<S308>/Switch4' */
MONPRM volatile boolean VIPM_BMSEmgcySdnReqVld_flg = false;/* '<S309>/Logical Operator3' */
MONPRM volatile boolean VIPM_BMSEmgcySdnReq_flg = false;/* '<S309>/Switch4' */
MONPRM volatile boolean VIPM_BMSHVBatActVoltVld_flg = false;/* '<S318>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSHVBatActVolt_V = 0.0F;/* '<S318>/MinMax1' */
MONPRM volatile boolean VIPM_BMSHVBatCellTempAveVld_flg = false;/* '<S124>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSHVBatCellTempAve_C = 0.0F;/* '<S124>/MinMax1' */
MONPRM volatile boolean VIPM_BMSHVBatCellTempMaxVld_flg = false;/* '<S125>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSHVBatCellTempMax_C = 0.0F;/* '<S125>/MinMax1' */
MONPRM volatile boolean VIPM_BMSHVBatCellTempMinVld_flg = false;/* '<S126>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSHVBatCellTempMin_C = 0.0F;/* '<S126>/MinMax1' */
MONPRM volatile boolean VIPM_BMSInletCooltActlTempVld_flg = false;/* '<S325>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSInletCooltActlTemp_C = 0.0F;/* '<S325>/MinMax1' */
MONPRM volatile boolean VIPM_BMSIsoResistVld_flg = false;/* '<S326>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSIsoResist_MOhm = 0.0F;/* '<S326>/MinMax1' */
MONPRM volatile boolean VIPM_BMSLostComm_flg = false;/* '<S384>/Switch4' */
MONPRM volatile boolean VIPM_BMSMaxChrgCurntACVld_flg = false;/* '<S327>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSMaxChrgCurntAC_A = 0.0F;/* '<S327>/MinMax1' */
MONPRM volatile boolean VIPM_BMSMaxChrgVoltACVld_flg = false;/* '<S328>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSMaxChrgVoltAC_V = 0.0F;/* '<S328>/MinMax1' */
MONPRM volatile boolean VIPM_BMSMaxConChrgCurntVld_flg = false;/* '<S335>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSMaxConChrgCurnt_A = 0.0F;/* '<S335>/MinMax1' */
MONPRM volatile boolean VIPM_BMSMaxConDisCurntVld_flg = false;/* '<S336>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSMaxConDisCurnt_A = 0.0F;/* '<S336>/MinMax1' */
MONPRM volatile boolean VIPM_BMSMaxInsChrgCurntVld_flg = false;/* '<S337>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSMaxInsChrgCurnt_A = 0.0F;/* '<S337>/MinMax1' */
MONPRM volatile boolean VIPM_BMSMaxInsDisCurntVld_flg = false;/* '<S338>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSMaxInsDisCurnt_A = 0.0F;/* '<S338>/MinMax1' */
MONPRM volatile boolean VIPM_BMSOutlCooltActlTempVld_flg = false;/* '<S329>/Logical Operator3' */
MONPRM volatile float32 VIPM_BMSOutlCooltActlTemp_C = 0.0F;/* '<S329>/MinMax1' */
MONPRM volatile boolean VIPM_BMSPackIDVld_flg = false;/* '<S170>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BMSPackID_enum = ((uint8)0U);/* '<S170>/Switch4' */
MONPRM volatile boolean VIPM_BMSPwrTrainConnectStaVld_flg = false;/* '<S310>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BMSPwrTrainConnectSta_enum = ((uint8)0U);/* '<S310>/Switch4' */
MONPRM volatile boolean VIPM_BMSRunStaVld_flg = false;/* '<S311>/Logical Operator3' */
MONPRM volatile EnumBMSRunSt VIPM_BMSRunSta_enum = EnumBMSRunSt_Invld;/* '<S311>/Switch4' */
MONPRM volatile boolean VIPM_BMSSysFailStaVld_flg = false;/* '<S312>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BMSSysFailSta_enum = ((uint8)0U);/* '<S312>/Switch4' */
MONPRM volatile boolean VIPM_BMSThermrunawayWrnVld_flg = false;/* '<S313>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BMSThermrunawayWrn_enum = ((uint8)0U);/* '<S313>/Switch4' */
MONPRM volatile boolean VIPM_BMS_2_BatState_CRCFlt_flg = false;/* '<S383>/Logical Operator14' */
MONPRM volatile boolean VIPM_BODCANBusOff_flg = false;/* '<S384>/Switch1' */
MONPRM volatile boolean VIPM_BootVerVld_flg = false;/* '<S17>/Logical Operator3' */
MONPRM volatile uint8 VIPM_BootVer_enum = ((uint8)0U);/* '<S17>/Switch4' */
MONPRM volatile boolean VIPM_CCPACAutoKeyVld_flg = false;/* '<S350>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPACAutoKey_flg = false;/* '<S350>/Switch4' */
MONPRM volatile boolean VIPM_CCPACSwKeyVld_flg = false;/* '<S351>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPACSwKey_flg = false;/* '<S351>/Switch4' */
MONPRM volatile boolean VIPM_CCPAVASOffKeyVld_flg = false;/* '<S352>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPAVASOffKey_flg = false;/* '<S352>/Switch4' */
MONPRM volatile boolean VIPM_CCPAVHKeyVld_flg = false;/* '<S353>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPAVHKey_flg = false;/* '<S353>/Switch4' */
MONPRM volatile boolean VIPM_CCPAirInletModeKeyVld_flg = false;/* '<S354>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPAirInletModeKey_flg = false;/* '<S354>/Switch4' */
MONPRM volatile boolean VIPM_CCPBlwngModeNextKeyVld_flg = false;/* '<S355>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPBlwngModeNextKey_flg = false;/* '<S355>/Switch4' */
MONPRM volatile boolean VIPM_CCPBlwngModePrevKeyVld_flg = false;/* '<S356>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPBlwngModePrevKey_flg = false;/* '<S356>/Switch4' */
MONPRM volatile boolean VIPM_CCPBlwrLvlAddKeyVld_flg = false;/* '<S357>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPBlwrLvlAddKey_flg = false;/* '<S357>/Switch4' */
MONPRM volatile boolean VIPM_CCPBlwrLvlDecKeyVld_flg = false;/* '<S358>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPBlwrLvlDecKey_flg = false;/* '<S358>/Switch4' */
MONPRM volatile boolean VIPM_CCPCenLckKeyVld_flg = false;/* '<S359>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPCenLckKey_flg = false;/* '<S359>/Switch4' */
MONPRM volatile boolean VIPM_CCPESCOffKeyVld_flg = false;/* '<S360>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPESCOffKey_flg = false;/* '<S360>/Switch4' */
MONPRM volatile boolean VIPM_CCPFrntWindDefrstKeyVld_flg = false;/* '<S361>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPFrntWindDefrstKey_flg = false;/* '<S361>/Switch4' */
MONPRM volatile boolean VIPM_CCPHDCKeyVld_flg = false;/* '<S362>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPHDCKey_flg = false;/* '<S362>/Switch4' */
MONPRM volatile boolean VIPM_CCPHzrdKeyVld_flg = false;/* '<S363>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPHzrdKey_flg = false;/* '<S363>/Switch4' */
MONPRM volatile boolean VIPM_CCPLostComm_flg = false;/* '<S384>/Switch20' */
MONPRM volatile boolean VIPM_CCPModeKeyVld_flg = false;/* '<S364>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPModeKey_flg = false;/* '<S364>/Switch4' */
MONPRM volatile boolean VIPM_CCPPwrRecupLvlKeyVld_flg = false;/* '<S365>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPPwrRecupLvlKey_flg = false;/* '<S365>/Switch4' */
MONPRM volatile boolean VIPM_CCPRrViewMirrHeatgKeyVld_flg = false;/* '<S366>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPRrViewMirrHeatgKey_flg = false;/* '<S366>/Switch4' */
MONPRM volatile boolean VIPM_CCPTPMSKeyVld_flg = false;/* '<S367>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPTPMSKey_flg = false;/* '<S367>/Switch4' */
MONPRM volatile boolean VIPM_CCPTempAddKeyVld_flg = false;/* '<S368>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPTempAddKey_flg = false;/* '<S368>/Switch4' */
MONPRM volatile boolean VIPM_CCPTempDecKeyVld_flg = false;/* '<S369>/Logical Operator3' */
MONPRM volatile boolean VIPM_CCPTempDecKey_flg = false;/* '<S369>/Switch4' */
MONPRM volatile boolean VIPM_CCP_PanelStatus_CRCFlt_flg = false;/* '<S383>/Logical Operator3' */
MONPRM volatile boolean VIPM_CDCBackLadjvalVld_flg = false;/* '<S75>/Logical Operator3' */
MONPRM volatile uint8 VIPM_CDCBackLadjval_enum = ((uint8)0U);/* '<S75>/Switch4' */
MONPRM volatile boolean VIPM_CDCLostComm_flg = false;/* '<S384>/Switch16' */
MONPRM volatile boolean VIPM_CHACANBusOff_flg = false;/* '<S384>/Switch3' */
MONPRM volatile boolean VIPM_COMPCANBusOffVld_flg = false;/* '<S24>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPCANBusOff_flg = false;/* '<S24>/Switch4' */
MONPRM volatile boolean VIPM_COMPCommuErrorVld_flg = false;/* '<S25>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPCommuError_flg = false;/* '<S25>/Switch4' */
MONPRM volatile boolean VIPM_COMPCurrOfstVld_flg = false;/* '<S26>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPCurrOfst_flg = false;/* '<S26>/Switch4' */
MONPRM volatile boolean VIPM_COMPEcompActSpdVld_flg = false;/* '<S27>/Logical Operator3' */
MONPRM volatile float32 VIPM_COMPEcompActSpd_rpm = 0.0F;/* '<S27>/MinMax1' */
MONPRM volatile boolean VIPM_COMPEcompSTVld_flg = false;/* '<S28>/Logical Operator3' */
MONPRM volatile uint8 VIPM_COMPEcompST_enum = ((uint8)0U);/* '<S28>/Switch4' */
MONPRM volatile boolean VIPM_COMPHiVoltVld_flg = false;/* '<S29>/Logical Operator3' */
MONPRM volatile float32 VIPM_COMPHiVolt_V = 0.0F;/* '<S29>/MinMax1' */
MONPRM volatile boolean VIPM_COMPHvErrVld_flg = false;/* '<S30>/Logical Operator3' */
MONPRM volatile uint8 VIPM_COMPHvErr_enum = ((uint8)0U);/* '<S30>/Switch4' */
MONPRM volatile boolean VIPM_COMPIPMErrVld_flg = false;/* '<S31>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPIPMErr_flg = false;/* '<S31>/Switch4' */
MONPRM volatile boolean VIPM_COMPInCurrVld_flg = false;/* '<S32>/Logical Operator3' */
MONPRM volatile float32 VIPM_COMPInCurr_A = 0.0F;/* '<S32>/MinMax1' */
MONPRM volatile boolean VIPM_COMPLoseStepVld_flg = false;/* '<S33>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPLoseStep_flg = false;/* '<S33>/Switch4' */
MONPRM volatile boolean VIPM_COMPLvErrVld_flg = false;/* '<S34>/Logical Operator3' */
MONPRM volatile uint8 VIPM_COMPLvErr_enum = ((uint8)0U);/* '<S34>/Switch4' */
MONPRM volatile boolean VIPM_COMPOverDutyVld_flg = false;/* '<S35>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPOverDuty_flg = false;/* '<S35>/Switch4' */
MONPRM volatile boolean VIPM_COMPOvrCurrVld_flg = false;/* '<S36>/Logical Operator3' */
MONPRM volatile uint8 VIPM_COMPOvrCurr_enum = ((uint8)0U);/* '<S36>/Switch4' */
MONPRM volatile boolean VIPM_COMPPISaturationVld_flg = false;/* '<S37>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPPISaturation_flg = false;/* '<S37>/Switch4' */
MONPRM volatile boolean VIPM_COMPSelfChkErrVld_flg = false;/* '<S38>/Logical Operator3' */
MONPRM volatile uint8 VIPM_COMPSelfChkErr_enum = ((uint8)0U);/* '<S38>/Switch4' */
MONPRM volatile boolean VIPM_COMPTempErrVld_flg = false;/* '<S39>/Logical Operator3' */
MONPRM volatile boolean VIPM_COMPTempErr_flg = false;/* '<S39>/Switch4' */
MONPRM volatile boolean VIPM_COMPTempVld_flg = false;/* '<S40>/Logical Operator3' */
MONPRM volatile float32 VIPM_COMPTemp_C = 0.0F;/* '<S40>/MinMax1' */
MONPRM volatile boolean VIPM_COMP_AC_CRCFlt_flg = false;/* '<S383>/Logical Operator4' */
MONPRM volatile boolean VIPM_CRRRBSDWarnLtVld_flg = false;/* '<S267>/Logical Operator3' */
MONPRM volatile uint8 VIPM_CRRRBSDWarnLt_enum = ((uint8)0U);/* '<S267>/Switch4' */
MONPRM volatile boolean VIPM_CRRRBSDWarnRtVld_flg = false;/* '<S268>/Logical Operator3' */
MONPRM volatile uint8 VIPM_CRRRBSDWarnRt_enum = ((uint8)0U);/* '<S268>/Switch4' */
MONPRM volatile boolean VIPM_CRRRDOWWarnLtVld_flg = false;/* '<S269>/Logical Operator3' */
MONPRM volatile uint8 VIPM_CRRRDOWWarnLt_enum = ((uint8)0U);/* '<S269>/Switch4' */
MONPRM volatile boolean VIPM_CRRRDOWWarnRtVld_flg = false;/* '<S270>/Logical Operator3' */
MONPRM volatile uint8 VIPM_CRRRDOWWarnRt_enum = ((uint8)0U);/* '<S270>/Switch4' */
MONPRM volatile boolean VIPM_CRRRLostComm_flg = false;/* '<S384>/Switch7' */
MONPRM volatile boolean VIPM_CRRRRCTAWarnLtVld_flg = false;/* '<S271>/Logical Operator3' */
MONPRM volatile uint8 VIPM_CRRRRCTAWarnLt_enum = ((uint8)0U);/* '<S271>/Switch4' */
MONPRM volatile boolean VIPM_CRRRRCTAWarnRtVld_flg = false;/* '<S272>/Logical Operator3' */
MONPRM volatile uint8 VIPM_CRRRRCTAWarnRt_enum = ((uint8)0U);/* '<S272>/Switch4' */
MONPRM volatile boolean VIPM_CRRR_A_CRCFlt_flg = false;/* '<S383>/Logical Operator7' */
MONPRM volatile boolean VIPM_ClientNumVld_flg = false;/* '<S18>/Logical Operator3' */
MONPRM volatile uint8 VIPM_ClientNum_enum = ((uint8)0U);/* '<S18>/Switch4' */
MONPRM volatile boolean VIPM_ECUHiVoltInterlockSigVld_flg = false;/* '<S41>/Logical Operator3' */
MONPRM volatile boolean VIPM_ECUHiVoltInterlockSig_flg = false;/* '<S41>/Switch4' */
MONPRM volatile boolean VIPM_EHBAVHAppldStVld_flg = false;/* '<S273>/Logical Operator3' */
MONPRM volatile EnumAVHSt VIPM_EHBAVHAppldSt_enum = EnumAVHSt_Off;/* '<S273>/Switch4' */
MONPRM volatile boolean VIPM_EHBBLAVld_flg = false;/* '<S274>/Logical Operator3' */
MONPRM volatile boolean VIPM_EHBBLA_flg = false;/* '<S274>/Switch4' */
MONPRM volatile boolean VIPM_EHBBrkPedlValPercVld_flg = false;/* '<S177>/Logical Operator3' */
MONPRM volatile float32 VIPM_EHBBrkPedlValPerc_pct = 0.0F;/* '<S177>/MinMax1' */
MONPRM volatile boolean VIPM_EHBBrkPwrRecupTarWhlTqStsVld_flg = false;/* '<S178>/Logical Operator3' */
MONPRM volatile EnumRegenTgtTqStat VIPM_EHBBrkPwrRecupTarWhlTqSts_enum =
  EnumRegenTgtTqStat_NotInit;          /* '<S178>/Switch4' */
MONPRM volatile boolean VIPM_EHBBrkPwrRecupTarWhlTqVld_flg = false;/* '<S179>/Logical Operator3' */
MONPRM volatile float32 VIPM_EHBBrkPwrRecupTarWhlTq_Nm = 0.0F;/* '<S179>/MinMax1' */
MONPRM volatile boolean VIPM_EHBCDDActvVld_flg = false;/* '<S180>/Logical Operator3' */
MONPRM volatile boolean VIPM_EHBCDDActv_flg = false;/* '<S180>/Switch4' */
MONPRM volatile boolean VIPM_EHBEPBActuatorStLVld_flg = false;/* '<S275>/Logical Operator3' */
MONPRM volatile EnumEPBState VIPM_EHBEPBActuatorStL_enum =
  EnumEPBState_Releasing;              /* '<S275>/Switch4' */
MONPRM volatile boolean VIPM_EHBEPBActuatorStRVld_flg = false;/* '<S181>/Logical Operator3' */
MONPRM volatile EnumEPBState VIPM_EHBEPBActuatorStR_enum =
  EnumEPBState_Releasing;              /* '<S181>/Switch4' */
MONPRM volatile boolean VIPM_EHBEPBDynAppStVld_flg = false;/* '<S182>/Logical Operator3' */
MONPRM volatile uint8 VIPM_EHBEPBDynAppSt_enum = ((uint8)0U);/* '<S182>/Switch4' */
MONPRM volatile boolean VIPM_EHBEPBSwitchStsVld_flg = false;/* '<S276>/Logical Operator3' */
MONPRM volatile EnumEPBSwSt VIPM_EHBEPBSwitchSts_enum = EnumEPBSwSt_Neutral;/* '<S276>/Switch4' */
MONPRM volatile boolean VIPM_EHBEPBSysStVld_flg = false;/* '<S277>/Logical Operator3' */
MONPRM volatile EnumEPBSysSt VIPM_EHBEPBSysSt_enum = EnumEPBSysSt_NotInit;/* '<S277>/Switch4' */
MONPRM volatile boolean VIPM_EHBFltLvlVld_flg = false;/* '<S183>/Logical Operator3' */
MONPRM volatile uint8 VIPM_EHBFltLvl_enum = ((uint8)0U);/* '<S183>/Switch4' */
MONPRM volatile boolean VIPM_EHBHDCFucFaultVld_flg = false;/* '<S278>/Logical Operator3' */
MONPRM volatile boolean VIPM_EHBHDCFucFault_flg = false;/* '<S278>/Switch4' */
MONPRM volatile boolean VIPM_EHBLostComm_flg = false;/* '<S384>/Switch18' */
MONPRM volatile boolean VIPM_EHBReqBrkLiOnVld_flg = false;/* '<S184>/Logical Operator3' */
MONPRM volatile boolean VIPM_EHBReqBrkLiOn_flg = false;/* '<S184>/Switch4' */
MONPRM volatile boolean VIPM_EHB_B_CRCFlt_flg = false;/* '<S383>/Logical Operator8' */
MONPRM volatile boolean VIPM_EPSLostComm_flg = false;/* '<S384>/Switch9' */
MONPRM volatile boolean VIPM_EPSRotSpdVld_flg = false;/* '<S186>/Logical Operator3' */
MONPRM volatile float32 VIPM_EPSRotSpd_degps = 0.0F;/* '<S186>/MinMax1' */
MONPRM volatile boolean VIPM_EPSSteerWhlAngCaldVld_flg = false;/* '<S187>/Logical Operator3' */
MONPRM volatile boolean VIPM_EPSSteerWhlAngCald_flg = false;/* '<S187>/Switch4' */
MONPRM volatile boolean VIPM_EPSSteerWhlAngFailrVld_flg = false;/* '<S188>/Logical Operator3' */
MONPRM volatile boolean VIPM_EPSSteerWhlAngFailr_flg = false;/* '<S188>/Switch4' */
MONPRM volatile boolean VIPM_EPSSteerWhlAngVld_flg = false;/* '<S189>/Logical Operator3' */
MONPRM volatile float32 VIPM_EPSSteerWhlAng_deg = 0.0F;/* '<S189>/MinMax1' */
MONPRM volatile boolean VIPM_EPS_2_StrWhlAng_CRCFlt_flg = false;/* '<S383>/Logical Operator9' */
MONPRM volatile boolean VIPM_EPTCANBusOff_flg = false;/* '<S384>/Switch' */
MONPRM volatile boolean VIPM_ESCABSActvStaVld_flg = false;/* '<S192>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCABSActvSta_flg = false;/* '<S192>/Switch4' */
MONPRM volatile boolean VIPM_ESCCDPActvVld_flg = false;/* '<S193>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCCDPActv_flg = false;/* '<S193>/Switch4' */
MONPRM volatile boolean VIPM_ESCEBDActvVld_flg = false;/* '<S194>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCEBDActv_flg = false;/* '<S194>/Switch4' */
MONPRM volatile boolean VIPM_ESCESPActvStaVld_flg = false;/* '<S195>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCESPActvSta_flg = false;/* '<S195>/Switch4' */
MONPRM volatile boolean VIPM_ESCESSActvVld_flg = false;/* '<S196>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCESSActv_flg = false;/* '<S196>/Switch4' */
MONPRM volatile boolean VIPM_ESCFltLvlVld_flg = false;/* '<S197>/Logical Operator3' */
MONPRM volatile uint8 VIPM_ESCFltLvl_enum = ((uint8)0U);/* '<S197>/Switch4' */
MONPRM volatile boolean VIPM_ESCLUnOrLockfeedbackVld_flg = false;/* '<S370>/Logical Operator3' */
MONPRM volatile uint64 VIPM_ESCLUnOrLockfeedback_nu = (0ULL);/* '<S370>/Switch4' */
MONPRM volatile boolean VIPM_ESCLatAccSnsrValVld_flg = false;/* '<S204>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCLatAccSnsrVal_g = 0.0F;/* '<S204>/MinMax1' */
MONPRM volatile boolean VIPM_ESCLongAccSnsrValVld_flg = false;/* '<S205>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCLongAccSnsrVal_g = 0.0F;/* '<S205>/MinMax1' */
MONPRM volatile boolean VIPM_ESCLostComm_flg = false;/* '<S384>/Switch5' */
MONPRM volatile boolean VIPM_ESCMstrCylPresrVld_flg = false;/* '<S206>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCMstrCylPresr_bar = 0.0F;/* '<S206>/MinMax1' */
MONPRM volatile boolean VIPM_ESCReqBrkLghtOnVld_flg = false;/* '<S198>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCReqBrkLghtOn_flg = false;/* '<S198>/Switch4' */
MONPRM volatile boolean VIPM_ESCSlopPctVld_flg = false;/* '<S199>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCSlopPct_pct = 0.0F;/* '<S199>/MinMax1' */
MONPRM volatile boolean VIPM_ESCTCSActvStaVld_flg = false;/* '<S200>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCTCSActvSta_flg = false;/* '<S200>/Switch4' */
MONPRM volatile boolean VIPM_ESCVehSpdVld_flg = false;/* '<S201>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCVehSpd_kph = 0.0F;/* '<S201>/MinMax1' */
MONPRM volatile boolean VIPM_ESCVehStandStillStaVld_flg = false;/* '<S207>/Logical Operator3' */
MONPRM volatile uint8 VIPM_ESCVehStandStillSta_enum = ((uint8)0U);/* '<S207>/Switch4' */
MONPRM volatile boolean VIPM_ESCWhlDirctnFLVld_flg = false;/* '<S208>/Logical Operator3' */
MONPRM volatile uint8 VIPM_ESCWhlDirctnFL_enum = ((uint8)0U);/* '<S208>/Switch4' */
MONPRM volatile boolean VIPM_ESCWhlDirctnFRVld_flg = false;/* '<S209>/Logical Operator3' */
MONPRM volatile uint8 VIPM_ESCWhlDirctnFR_enum = ((uint8)0U);/* '<S209>/Switch4' */
MONPRM volatile boolean VIPM_ESCWhlDirctnRLVld_flg = false;/* '<S210>/Logical Operator3' */
MONPRM volatile uint8 VIPM_ESCWhlDirctnRL_enum = ((uint8)0U);/* '<S210>/Switch4' */
MONPRM volatile boolean VIPM_ESCWhlDirctnRRVld_flg = false;/* '<S211>/Logical Operator3' */
MONPRM volatile uint8 VIPM_ESCWhlDirctnRR_enum = ((uint8)0U);/* '<S211>/Switch4' */
MONPRM volatile boolean VIPM_ESCWhlSpdKphFLVld_flg = false;/* '<S212>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCWhlSpdKphFL_kph = 0.0F;/* '<S212>/MinMax1' */
MONPRM volatile boolean VIPM_ESCWhlSpdKphFRVld_flg = false;/* '<S213>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCWhlSpdKphFR_kph = 0.0F;/* '<S213>/MinMax1' */
MONPRM volatile boolean VIPM_ESCWhlSpdKphRLVld_flg = false;/* '<S214>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCWhlSpdKphRL_kph = 0.0F;/* '<S214>/MinMax1' */
MONPRM volatile boolean VIPM_ESCWhlSpdKphRRVld_flg = false;/* '<S215>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCWhlSpdKphRR_kph = 0.0F;/* '<S215>/MinMax1' */
MONPRM volatile boolean VIPM_ESCWhlTqDecReqActvVld_flg = false;/* '<S216>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCWhlTqDecReqActv_flg = false;/* '<S216>/Switch4' */
MONPRM volatile boolean VIPM_ESCWhlTqDecReqValVld_flg = false;/* '<S217>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCWhlTqDecReqVal_Nm = 0.0F;/* '<S217>/MinMax1' */
MONPRM volatile boolean VIPM_ESCWhlTqIncReqActvVld_flg = false;/* '<S218>/Logical Operator3' */
MONPRM volatile boolean VIPM_ESCWhlTqIncReqActv_flg = false;/* '<S218>/Switch4' */
MONPRM volatile boolean VIPM_ESCWhlTqIncReqValVld_flg = false;/* '<S219>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCWhlTqIncReqVal_Nm = 0.0F;/* '<S219>/MinMax1' */
MONPRM volatile boolean VIPM_ESCYawRateVld_flg = false;/* '<S220>/Logical Operator3' */
MONPRM volatile float32 VIPM_ESCYawRate_degps = 0.0F;/* '<S220>/MinMax1' */
MONPRM volatile boolean VIPM_ESC_7_FuncStatus_CRCFlt_flg = false;/* '<S383>/Logical Operator10' */
MONPRM volatile boolean VIPM_FCMACCSdnModeVld_flg = false;/* '<S279>/Logical Operator3' */
MONPRM volatile uint8 VIPM_FCMACCSdnMode_enum = ((uint8)0U);/* '<S279>/Switch4' */
MONPRM volatile boolean VIPM_FCMACCWhlDeceVld_flg = false;/* '<S280>/Logical Operator3' */
MONPRM volatile float32 VIPM_FCMACCWhlDece_mps2 = 0.0F;/* '<S280>/MinMax1' */
MONPRM volatile boolean VIPM_FCMACCWhlTqReqActvVld_flg = false;/* '<S281>/Logical Operator3' */
MONPRM volatile boolean VIPM_FCMACCWhlTqReqActv_flg = false;/* '<S281>/Switch4' */
MONPRM volatile boolean VIPM_FCMACCWhlTqReqValVld_flg = false;/* '<S282>/Logical Operator3' */
MONPRM volatile float32 VIPM_FCMACCWhlTqReqVal_Nm = 0.0F;/* '<S282>/MinMax1' */
MONPRM volatile boolean VIPM_FCMAEBReqVld_flg = false;/* '<S283>/Logical Operator3' */
MONPRM volatile boolean VIPM_FCMAEBReq_flg = false;/* '<S283>/Switch4' */
MONPRM volatile boolean VIPM_FCMAccModeVld_flg = false;/* '<S284>/Logical Operator3' */
MONPRM volatile EnumACCMode VIPM_FCMAccMode_enum = EnumACCMode_Off;/* '<S284>/Switch4' */
MONPRM volatile boolean VIPM_FCMAccReqDriveOffVld_flg = false;/* '<S285>/Logical Operator3' */
MONPRM volatile boolean VIPM_FCMAccReqDriveOff_flg = false;/* '<S285>/Switch4' */
MONPRM volatile boolean VIPM_FCMAccReqStandstillVld_flg = false;/* '<S286>/Logical Operator3' */
MONPRM volatile boolean VIPM_FCMAccReqStandstill_flg = false;/* '<S286>/Switch4' */
MONPRM volatile boolean VIPM_FCMAccTarAccrnReqActvVld_flg = false;/* '<S287>/Logical Operator3' */
MONPRM volatile boolean VIPM_FCMAccTarAccrnReqActv_flg = false;/* '<S287>/Switch4' */
MONPRM volatile boolean VIPM_FCMAccTarAccrnVld_flg = false;/* '<S288>/Logical Operator3' */
MONPRM volatile float32 VIPM_FCMAccTarAccrn_mps2 = 0.0F;/* '<S288>/MinMax1' */
MONPRM volatile boolean VIPM_FCMAccTgtAxReqVld_flg = false;/* '<S289>/Logical Operator3' */
MONPRM volatile boolean VIPM_FCMAccTgtAxReq_flg = false;/* '<S289>/Switch4' */
MONPRM volatile boolean VIPM_FCMAccTgtAxVld_flg = false;/* '<S290>/Logical Operator3' */
MONPRM volatile float32 VIPM_FCMAccTgtAx_mps2 = 0.0F;/* '<S290>/MinMax1' */
MONPRM volatile boolean VIPM_FCMEPBReqVld_flg = false;/* '<S291>/Logical Operator3' */
MONPRM volatile uint8 VIPM_FCMEPBReq_enum = ((uint8)0U);/* '<S291>/Switch4' */
MONPRM volatile boolean VIPM_FCMLostComm_flg = false;/* '<S384>/Switch6' */
MONPRM volatile boolean VIPM_FCMTrnLampReqVld_flg = false;/* '<S292>/Logical Operator3' */
MONPRM volatile uint8 VIPM_FCMTrnLampReq_enum = ((uint8)0U);/* '<S292>/Switch4' */
MONPRM volatile boolean VIPM_FCM_B_CRCFlt_flg = false;/* '<S383>/Logical Operator11' */
MONPRM volatile boolean VIPM_HUACAutoCtlVld_flg = false;/* '<S76>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUACAutoCtl_enum = ((uint8)0U);/* '<S76>/Switch4' */
MONPRM volatile boolean VIPM_HUACPwrCtlVld_flg = false;/* '<S77>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUACPwrCtl_enum = ((uint8)0U);/* '<S77>/Switch4' */
MONPRM volatile boolean VIPM_HUACUnlckVentSetVld_flg = false;/* '<S78>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUACUnlckVentSet_enum = ((uint8)0U);/* '<S78>/Switch4' */
MONPRM volatile boolean VIPM_HUAirInletModeSetVld_flg = false;/* '<S79>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUAirInletModeSet_enum = ((uint8)0U);/* '<S79>/Switch4' */
MONPRM volatile boolean VIPM_HUBlwrModeSetVld_flg = false;/* '<S80>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUBlwrModeSet_enum = ((uint8)0U);/* '<S80>/Switch4' */
MONPRM volatile boolean VIPM_HUChgWiprMtMdSwSetVld_flg = false;/* '<S81>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUChgWiprMtMdSwSet_enum = ((uint8)0U);/* '<S81>/Switch4' */
MONPRM volatile boolean VIPM_HUChrgngReqVld_flg = false;/* '<S82>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUChrgngReq_enum = ((uint8)0U);/* '<S82>/Switch4' */
MONPRM volatile boolean VIPM_HUChrgngmodeVld_flg = false;/* '<S83>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUChrgngmode_enum = ((uint8)0U);/* '<S83>/Switch4' */
MONPRM volatile boolean VIPM_HUCstRecupModeSelVld_flg = false;/* '<S84>/Logical Operator3' */
MONPRM volatile EnumRegenModeSelct VIPM_HUCstRecupModeSel_enum =
  EnumRegenModeSelct_NoCmd;            /* '<S84>/Switch4' */
MONPRM volatile boolean VIPM_HUDrvModeSelVld_flg = false;/* '<S85>/Logical Operator3' */
MONPRM volatile EnumDrvModeSelct VIPM_HUDrvModeSel_enum = EnumDrvModeSelct_NoCmd;/* '<S85>/Switch4' */
MONPRM volatile boolean VIPM_HUDrvPwrSetVld_flg = false;/* '<S86>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUDrvPwrSet_cnt = ((uint8)0U);/* '<S86>/Switch4' */
MONPRM volatile boolean VIPM_HUFlwrMeHmCtrlVld_flg = false;/* '<S87>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUFlwrMeHmCtrl_enum = ((uint8)0U);/* '<S87>/Switch4' */
MONPRM volatile boolean VIPM_HUFrntFanSpdSetVld_flg = false;/* '<S88>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUFrntFanSpdSet_enum = ((uint8)0U);/* '<S88>/Switch4' */
MONPRM volatile boolean VIPM_HUHybEcoModeSetVld_flg = false;/* '<S89>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUHybEcoModeSet_enum = ((uint8)0U);/* '<S89>/Switch4' */
MONPRM volatile boolean VIPM_HUIllmndEntryStsVld_flg = false;/* '<S90>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUIllmndEntrySts_enum = ((uint8)0U);/* '<S90>/Switch4' */
MONPRM volatile boolean VIPM_HUIllmndLckStsVld_flg = false;/* '<S91>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUIllmndLckSts_enum = ((uint8)0U);/* '<S91>/Switch4' */
MONPRM volatile boolean VIPM_HUIllmndUnlckStsVld_flg = false;/* '<S92>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUIllmndUnlckSts_enum = ((uint8)0U);/* '<S92>/Switch4' */
MONPRM volatile boolean VIPM_HULckHornOnStVld_flg = false;/* '<S93>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HULckHornOnSt_enum = ((uint8)0U);/* '<S93>/Switch4' */
MONPRM volatile boolean VIPM_HULeftTempSetVld_flg = false;/* '<S94>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HULeftTempSet_enum = ((uint8)0U);/* '<S94>/Switch4' */
MONPRM volatile boolean VIPM_HUMaiDrvrSeatHeatVld_flg = false;/* '<S95>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUMaiDrvrSeatHeat_enum = ((uint8)0U);/* '<S95>/Switch4' */
MONPRM volatile boolean VIPM_HUManlDefrstCtlVld_flg = false;/* '<S96>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUManlDefrstCtl_enum = ((uint8)0U);/* '<S96>/Switch4' */
MONPRM volatile boolean VIPM_HUOvrspdCntrlLckSetVld_flg = false;/* '<S97>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUOvrspdCntrlLckSet_enum = ((uint8)0U);/* '<S97>/Switch4' */
MONPRM volatile boolean VIPM_HUParkAutoUnlckSetVld_flg = false;/* '<S98>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUParkAutoUnlckSet_enum = ((uint8)0U);/* '<S98>/Switch4' */
MONPRM volatile boolean VIPM_HUPeristalsisModeEnblVld_flg = false;/* '<S99>/Logical Operator3' */
MONPRM volatile EnumCrpModeEnbl VIPM_HUPeristalsisModeEnbl_enum =
  EnumCrpModeEnbl_NoCmd;               /* '<S99>/Switch4' */
MONPRM volatile boolean VIPM_HUPwrOffReqVld_flg = false;/* '<S100>/Logical Operator3' */
MONPRM volatile boolean VIPM_HUPwrOffReq_flg = false;/* '<S100>/Switch4' */
MONPRM volatile boolean VIPM_HURecupPwrSetVld_flg = false;/* '<S101>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HURecupPwrSet_pct = ((uint8)0U);/* '<S101>/Switch4' */
MONPRM volatile boolean VIPM_HURrMirrHeatVld_flg = false;/* '<S102>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HURrMirrHeat_enum = ((uint8)0U);/* '<S102>/Switch4' */
MONPRM volatile boolean VIPM_HUSteerWhlHeatVld_flg = false;/* '<S103>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUSteerWhlHeat_enum = ((uint8)0U);/* '<S103>/Switch4' */
MONPRM volatile boolean VIPM_HUTPMSRstReqVld_flg = false;/* '<S104>/Logical Operator3' */
MONPRM volatile boolean VIPM_HUTPMSRstReq_flg = false;/* '<S104>/Switch4' */
MONPRM volatile boolean VIPM_HUTrnkLckSwCtrlVld_flg = false;/* '<S105>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUTrnkLckSwCtrl_enum = ((uint8)0U);/* '<S105>/Switch4' */
MONPRM volatile boolean VIPM_HUVehMaxCurrVld_flg = false;/* '<S106>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUVehMaxCurr_A = ((uint8)0U);/* '<S106>/Switch4' */
MONPRM volatile boolean VIPM_HUWiprIntlTmSetVld_flg = false;/* '<S107>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HUWiprIntlTmSet_enum = ((uint8)0U);/* '<S107>/Switch4' */
MONPRM volatile boolean VIPM_HU_B_CRCFlt_flg = false;/* '<S383>/Logical Operator' */
MONPRM volatile boolean VIPM_HVCHCurrVld_flg = false;/* '<S55>/Logical Operator3' */
MONPRM volatile float32 VIPM_HVCHCurr_A = 0.0F;/* '<S55>/MinMax1' */
MONPRM volatile boolean VIPM_HVCHFltCodVld_flg = false;/* '<S56>/Logical Operator3' */
MONPRM volatile uint16 VIPM_HVCHFltCod_enum = ((uint16)0U);/* '<S56>/Switch4' */
MONPRM volatile boolean VIPM_HVCHHVStVld_flg = false;/* '<S46>/Logical Operator3' */
MONPRM volatile boolean VIPM_HVCHHVSt_flg = false;/* '<S46>/Switch4' */
MONPRM volatile boolean VIPM_HVCHHVVoltsVld_flg = false;/* '<S57>/Logical Operator3' */
MONPRM volatile float32 VIPM_HVCHHVVolts_V = 0.0F;/* '<S57>/MinMax1' */
MONPRM volatile boolean VIPM_HVCHInletTempVld_flg = false;/* '<S47>/Logical Operator3' */
MONPRM volatile float32 VIPM_HVCHInletTemp_C = 0.0F;/* '<S47>/MinMax1' */
MONPRM volatile boolean VIPM_HVCHOutlTempVld_flg = false;/* '<S48>/Logical Operator3' */
MONPRM volatile float32 VIPM_HVCHOutlTemp_C = 0.0F;/* '<S48>/MinMax1' */
MONPRM volatile boolean VIPM_HVCHPCBTempVld_flg = false;/* '<S49>/Logical Operator3' */
MONPRM volatile float32 VIPM_HVCHPCBTemp_C = 0.0F;/* '<S49>/MinMax1' */
MONPRM volatile boolean VIPM_HVCHPwrVld_flg = false;/* '<S58>/Logical Operator3' */
MONPRM volatile float32 VIPM_HVCHPwr_kW = 0.0F;/* '<S58>/MinMax1' */
MONPRM volatile boolean VIPM_HVCHStVld_flg = false;/* '<S50>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HVCHSt_enum = ((uint8)0U);/* '<S50>/Switch4' */
MONPRM volatile boolean VIPM_HVCHWorkModeVld_flg = false;/* '<S51>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HVCHWorkMode_enum = ((uint8)0U);/* '<S51>/Switch4' */
MONPRM volatile boolean VIPM_HVCHWorkStVld_flg = false;/* '<S59>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HVCHWorkSt_enum = ((uint8)0U);/* '<S59>/Switch4' */
MONPRM volatile boolean VIPM_HVCH_Status1_CRCFlt_flg = false;/* '<S383>/Logical Operator5' */
MONPRM volatile boolean VIPM_HwVerMaxVld_flg = false;/* '<S19>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HwVerMax_enum = ((uint8)0U);/* '<S19>/Switch4' */
MONPRM volatile boolean VIPM_HwVerMinVld_flg = false;/* '<S20>/Logical Operator3' */
MONPRM volatile uint8 VIPM_HwVerMin_enum = ((uint8)0U);/* '<S20>/Switch4' */
MONPRM volatile boolean VIPM_ICULostComm_flg = false;/* '<S384>/Switch11' */
MONPRM volatile boolean VIPM_ICUTotOdoVld_flg = false;/* '<S73>/Logical Operator3' */
MONPRM volatile float32 VIPM_ICUTotOdo_km = 0.0F;/* '<S73>/MinMax1' */
MONPRM volatile boolean VIPM_ICU_Info_CRCFlt_flg = false;/* '<S383>/Logical Operator1' */
MONPRM volatile boolean VIPM_INV1ActModeVld_flg = false;/* '<S234>/Logical Operator3' */
MONPRM volatile EnumINVActMd VIPM_INV1ActMode_enum = EnumINVActMd_Invld;/* '<S234>/Switch4' */
MONPRM volatile boolean VIPM_INV1ActTorqVld_flg = false;/* '<S235>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV1ActTorq_Nm = 0.0F;/* '<S235>/MinMax1' */
MONPRM volatile boolean VIPM_INV1AntithftAuthRsltVld_flg = false;/* '<S236>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INV1AntithftAuthRslt_enum = ((uint8)0U);/* '<S236>/Switch4' */
MONPRM volatile boolean VIPM_INV1MotSpdVld_flg = false;/* '<S237>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV1MotSpd_rpm = 0.0F;/* '<S237>/MinMax1' */
MONPRM volatile boolean VIPM_INV1PreChrgAllwdVld_flg = false;/* '<S238>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INV1PreChrgAllwd_enum = ((uint8)0U);/* '<S238>/Switch4' */
MONPRM volatile boolean VIPM_INV1PreprogmFlgVld_flg = false;/* '<S239>/Logical Operator3' */
MONPRM volatile boolean VIPM_INV1PreprogmFlg_flg = false;/* '<S239>/Switch4' */
MONPRM volatile boolean VIPM_INV1ShutdownAllwdVld_flg = false;/* '<S240>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INV1ShutdownAllwd_enum = ((uint8)0U);/* '<S240>/Switch4' */
MONPRM volatile boolean VIPM_INV2IgbtMaxTempVld_flg = false;/* '<S243>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV2IgbtMaxTemp_C = 0.0F;/* '<S243>/MinMax1' */
MONPRM volatile boolean VIPM_INV2InpCurntVld_flg = false;/* '<S244>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV2InpCurnt_A = 0.0F;/* '<S244>/MinMax1' */
MONPRM volatile boolean VIPM_INV2InpVoltVld_flg = false;/* '<S245>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV2InpVolt_V = 0.0F;/* '<S245>/MinMax1' */
MONPRM volatile boolean VIPM_INV2MotorMaxTempVld_flg = false;/* '<S246>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV2MotorMaxTemp_C = 0.0F;/* '<S246>/MinMax1' */
MONPRM volatile boolean VIPM_INV3DrvTqAllwdMaxVld_flg = false;/* '<S250>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV3DrvTqAllwdMax_Nm = 0.0F;/* '<S250>/MinMax1' */
MONPRM volatile boolean VIPM_INV3RecupTqAllwdMaxVld_flg = false;/* '<S251>/Logical Operator3' */
MONPRM volatile float32 VIPM_INV3RecupTqAllwdMax_Nm = 0.0F;/* '<S251>/MinMax1' */
MONPRM volatile boolean VIPM_INV4FltLvlVld_flg = false;/* '<S254>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INV4FltLvl_enum = ((uint8)0U);/* '<S254>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngData02Vld_flg = false;/* '<S130>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngData02_nu = ((uint8)0U);/* '<S130>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngData03Vld_flg = false;/* '<S131>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngData03_nu = ((uint8)0U);/* '<S131>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngData04Vld_flg = false;/* '<S132>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngData04_nu = ((uint8)0U);/* '<S132>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngData05Vld_flg = false;/* '<S133>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngData05_nu = ((uint8)0U);/* '<S133>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngData06Vld_flg = false;/* '<S134>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngData06_nu = ((uint8)0U);/* '<S134>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngData07Vld_flg = false;/* '<S135>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngData07_nu = ((uint8)0U);/* '<S135>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngStsVld_flg = false;/* '<S136>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngSts_enum = ((uint8)0U);/* '<S136>/Switch4' */
MONPRM volatile boolean VIPM_INVLrngSubIDVld_flg = false;/* '<S137>/Logical Operator3' */
MONPRM volatile uint8 VIPM_INVLrngSubID_cnt = ((uint8)0U);/* '<S137>/Switch4' */
MONPRM volatile boolean VIPM_INV_1_Value_CRCFlt_flg = false;/* '<S383>/Logical Operator15' */
MONPRM volatile boolean VIPM_IPUDCCActOprtModeVld_flg = false;/* '<S138>/Logical Operator3' */
MONPRM volatile EnumDCCActMd VIPM_IPUDCCActOprtMode_enum = EnumDCCActMd_Init;/* '<S138>/Switch4' */
MONPRM volatile boolean VIPM_IPUDCCHiVoltActCurntVld_flg = false;/* '<S145>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUDCCHiVoltActCurnt_A = 0.0F;/* '<S145>/MinMax1' */
MONPRM volatile boolean VIPM_IPUDCCHiVoltActVoltVld_flg = false;/* '<S146>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUDCCHiVoltActVolt_V = 0.0F;/* '<S146>/MinMax1' */
MONPRM volatile boolean VIPM_IPUDCCLoVoltActCurntVld_flg = false;/* '<S139>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUDCCLoVoltActCurnt_A = 0.0F;/* '<S139>/MinMax1' */
MONPRM volatile boolean VIPM_IPUDCCLoVoltActVoltVld_flg = false;/* '<S140>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUDCCLoVoltActVolt_V = 0.0F;/* '<S140>/MinMax1' */
MONPRM volatile boolean VIPM_IPUDCCSysFailStaVld_flg = false;/* '<S141>/Logical Operator3' */
MONPRM volatile uint8 VIPM_IPUDCCSysFailSta_enum = ((uint8)0U);/* '<S141>/Switch4' */
MONPRM volatile boolean VIPM_IPUDeviceIntTempVld_flg = false;/* '<S160>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUDeviceIntTemp_C = 0.0F;/* '<S160>/MinMax1' */
MONPRM volatile boolean VIPM_IPUHVILFailStVld_flg = false;/* '<S142>/Logical Operator3' */
MONPRM volatile boolean VIPM_IPUHVILFailSt_flg = false;/* '<S142>/Switch4' */
MONPRM volatile boolean VIPM_IPULostComm_flg = false;/* '<S384>/Switch17' */
MONPRM volatile boolean VIPM_IPUOBCACMaxPwrAllowVld_flg = false;/* '<S161>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUOBCACMaxPwrAllow_kW = 0.0F;/* '<S161>/MinMax1' */
MONPRM volatile boolean VIPM_IPUOBCActOprtModeVld_flg = false;/* '<S149>/Logical Operator3' */
MONPRM volatile EnumOBCActMd VIPM_IPUOBCActOprtMode_enum = EnumOBCActMd_Init;/* '<S149>/Switch4' */
MONPRM volatile boolean VIPM_IPUOBCConnectMainStaVld_flg = false;/* '<S150>/Logical Operator3' */
MONPRM volatile boolean VIPM_IPUOBCConnectMainSta_flg = false;/* '<S150>/Switch4' */
MONPRM volatile boolean VIPM_IPUOBCHVDCActCurVld_flg = false;/* '<S151>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUOBCHVDCActCur_A = 0.0F;/* '<S151>/MinMax1' */
MONPRM volatile boolean VIPM_IPUOBCHVDCActVolVld_flg = false;/* '<S152>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUOBCHVDCActVol_V = 0.0F;/* '<S152>/MinMax1' */
MONPRM volatile boolean VIPM_IPUOBCInletActPwrVld_flg = false;/* '<S153>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUOBCInletActPwr_kW = 0.0F;/* '<S153>/MinMax1' */
MONPRM volatile boolean VIPM_IPUOBCInletConnectStaVld_flg = false;/* '<S154>/Logical Operator3' */
MONPRM volatile EnumOBCPlugSt VIPM_IPUOBCInletConnectSta_enum =
  EnumOBCPlugSt_NoPlug;                /* '<S154>/Switch4' */
MONPRM volatile boolean VIPM_IPUOBCReqVld_flg = false;/* '<S155>/Logical Operator3' */
MONPRM volatile EnumOBCReq VIPM_IPUOBCReq_enum = EnumOBCReq_NoReq;/* '<S155>/Switch4' */
MONPRM volatile boolean VIPM_IPUOBCS2StateVld_flg = false;/* '<S162>/Logical Operator3' */
MONPRM volatile boolean VIPM_IPUOBCS2State_flg = false;/* '<S162>/Switch4' */
MONPRM volatile boolean VIPM_IPUOBCSysFailStaVld_flg = false;/* '<S156>/Logical Operator3' */
MONPRM volatile uint8 VIPM_IPUOBCSysFailSta_enum = ((uint8)0U);/* '<S156>/Switch4' */
MONPRM volatile boolean VIPM_IPUOBCTempIntVld_flg = false;/* '<S163>/Logical Operator3' */
MONPRM volatile float32 VIPM_IPUOBCTempInt_C = 0.0F;/* '<S163>/MinMax1' */
MONPRM volatile boolean VIPM_IPUOBCWakeUpModeVld_flg = false;/* '<S164>/Logical Operator3' */
MONPRM volatile EnumOBCWakeUpMd VIPM_IPUOBCWakeUpMode_enum =
  EnumOBCWakeUpMd_Invld;               /* '<S164>/Switch4' */
MONPRM volatile boolean VIPM_IPU_DCC_1_State_CRCFlt_flg = false;/* '<S383>/Logical Operator16' */
MONPRM volatile boolean VIPM_MCULostComm_flg = false;/* '<S384>/Switch13' */
MONPRM volatile boolean VIPM_PPLostComm_flg = false;/* '<S384>/Switch8' */
MONPRM volatile boolean VIPM_PP_InformAndStatus_CRCFlt_flg = false;/* '<S383>/Logical Operator12' */
MONPRM volatile boolean VIPM_PTCLostComm_flg = false;/* '<S384>/Switch15' */
MONPRM volatile boolean VIPM_SCSFrntWiprSwtStVld_flg = false;/* '<S371>/Logical Operator3' */
MONPRM volatile uint8 VIPM_SCSFrntWiprSwtSt_enum = ((uint8)0U);/* '<S371>/Switch4' */
MONPRM volatile boolean VIPM_SCSFrntWshrSwtStVld_flg = false;/* '<S372>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSFrntWshrSwtSt_flg = false;/* '<S372>/Switch4' */
MONPRM volatile boolean VIPM_SCSGrShftLvrPstnReqVld_flg = false;/* '<S259>/Logical Operator3' */
MONPRM volatile EnumGrShftLvrPstnReq VIPM_SCSGrShftLvrPstnReq_enum =
  EnumGrShftLvrPstnReq_Invalid;        /* '<S259>/Switch4' */
MONPRM volatile boolean VIPM_SCSHiBeamSwStVld_flg = false;/* '<S373>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSHiBeamSwSt_flg = false;/* '<S373>/Switch4' */
MONPRM volatile boolean VIPM_SCSLampAutoStVld_flg = false;/* '<S374>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSLampAutoSt_flg = false;/* '<S374>/Switch4' */
MONPRM volatile boolean VIPM_SCSLeTrnLmpSwStVld_flg = false;/* '<S375>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSLeTrnLmpSwSt_flg = false;/* '<S375>/Switch4' */
MONPRM volatile boolean VIPM_SCSLoBeamSwStVld_flg = false;/* '<S376>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSLoBeamSwSt_flg = false;/* '<S376>/Switch4' */
MONPRM volatile boolean VIPM_SCSLostComm_flg = false;/* '<S384>/Switch19' */
MONPRM volatile boolean VIPM_SCSOvrVehBeamSwStVld_flg = false;/* '<S377>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSOvrVehBeamSwSt_flg = false;/* '<S377>/Switch4' */
MONPRM volatile boolean VIPM_SCSPstnLghtSwStVld_flg = false;/* '<S378>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSPstnLghtSwSt_flg = false;/* '<S378>/Switch4' */
MONPRM volatile boolean VIPM_SCSRght11SwVld_flg = false;/* '<S260>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSRght11Sw_flg = false;/* '<S260>/Switch4' */
MONPRM volatile boolean VIPM_SCSRght12SwVld_flg = false;/* '<S261>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSRght12Sw_flg = false;/* '<S261>/Switch4' */
MONPRM volatile boolean VIPM_SCSRght13SwVld_flg = false;/* '<S262>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSRght13Sw_flg = false;/* '<S262>/Switch4' */
MONPRM volatile boolean VIPM_SCSRghtSwVldtyVld_flg = false;/* '<S263>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSRghtSwVldty_flg = false;/* '<S263>/Switch4' */
MONPRM volatile boolean VIPM_SCSRiTrnLmpSwStVld_flg = false;/* '<S379>/Logical Operator3' */
MONPRM volatile boolean VIPM_SCSRiTrnLmpSwSt_flg = false;/* '<S379>/Switch4' */
MONPRM volatile boolean VIPM_SCS_RiSwitchSts_CRCFlt_flg = false;/* '<S383>/Logical Operator6' */
MONPRM volatile boolean VIPM_SRSCrashOutputStsVld_flg = false;/* '<S381>/Logical Operator3' */
MONPRM volatile uint8 VIPM_SRSCrashOutputSts_enum = ((uint8)0U);/* '<S381>/Switch4' */
MONPRM volatile boolean VIPM_SRSDrvSeatbeltBkldVld_flg = false;/* '<S382>/Logical Operator3' */
MONPRM volatile boolean VIPM_SRSDrvSeatbeltBkld_flg = false;/* '<S382>/Switch4' */
MONPRM volatile boolean VIPM_SRSLostComm_flg = false;/* '<S384>/Switch10' */
MONPRM volatile boolean VIPM_SRS_1_Status_CRCFlt_flg = false;/* '<S383>/Logical Operator13' */
MONPRM volatile boolean VIPM_TBOXACRemtCtrlFlgVld_flg = false;/* '<S108>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXACRemtCtrlFlg_enum = ((uint8)0U);/* '<S108>/Switch4' */
MONPRM volatile boolean VIPM_TBOXACTempSetVld_flg = false;/* '<S109>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXACTempSet_enum = ((uint8)0U);/* '<S109>/Switch4' */
MONPRM volatile boolean VIPM_TBOXBJSTimeDayVld_flg = false;/* '<S64>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXBJSTimeDay_nu = ((uint8)0U);/* '<S64>/Switch4' */
MONPRM volatile boolean VIPM_TBOXBJSTimeHourVld_flg = false;/* '<S65>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXBJSTimeHour_nu = ((uint8)0U);/* '<S65>/Switch4' */
MONPRM volatile boolean VIPM_TBOXBJSTimeMinVld_flg = false;/* '<S66>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXBJSTimeMin_nu = ((uint8)0U);/* '<S66>/Switch4' */
MONPRM volatile boolean VIPM_TBOXBJSTimeMonthVld_flg = false;/* '<S67>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXBJSTimeMonth_nu = ((uint8)0U);/* '<S67>/Switch4' */
MONPRM volatile boolean VIPM_TBOXBJSTimeSecVld_flg = false;/* '<S68>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXBJSTimeSec_nu = ((uint8)0U);/* '<S68>/Switch4' */
MONPRM volatile boolean VIPM_TBOXBJSTimeYearVld_flg = false;/* '<S69>/Logical Operator3' */
MONPRM volatile uint16 VIPM_TBOXBJSTimeYear_nu = ((uint16)0U);/* '<S69>/Switch4' */
MONPRM volatile boolean VIPM_TBOXLostComm_flg = false;/* '<S384>/Switch12' */
MONPRM volatile boolean VIPM_TBOXRmtPwrLckVld_flg = false;/* '<S110>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXRmtPwrLck_enum = ((uint8)0U);/* '<S110>/Switch4' */
MONPRM volatile boolean VIPM_TBOXVCUCCMSpdLimLvlVld_flg = false;/* '<S111>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBOXVCUCCMSpdLimLvl_enum = ((uint8)0U);/* '<S111>/Switch4' */
MONPRM volatile boolean VIPM_TBOXVCUChrgngCondsVld_flg = false;/* '<S112>/Logical Operator3' */
MONPRM volatile boolean VIPM_TBOXVCUChrgngConds_flg = false;/* '<S112>/Switch4' */
MONPRM volatile boolean VIPM_TBOXVCUOprtLicVld_flg = false;/* '<S113>/Logical Operator3' */
MONPRM volatile boolean VIPM_TBOXVCUOprtLic_flg = false;/* '<S113>/Switch4' */
MONPRM volatile boolean VIPM_TBOXVCUVerVld_flg = false;/* '<S114>/Logical Operator3' */
MONPRM volatile boolean VIPM_TBOXVCUVer_flg = false;/* '<S114>/Switch4' */
MONPRM volatile boolean VIPM_TBOX_BJS_Time_CRCFlt_flg = false;/* '<S383>/Logical Operator2' */
MONPRM volatile boolean VIPM_TBoxOpenVentnVld_flg = false;/* '<S115>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBoxOpenVentn_enum = ((uint8)0U);/* '<S115>/Switch4' */
MONPRM volatile boolean VIPM_TBoxRmtCarSearchVld_flg = false;/* '<S116>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBoxRmtCarSearch_enum = ((uint8)0U);/* '<S116>/Switch4' */
MONPRM volatile boolean VIPM_TBoxRmtLckVld_flg = false;/* '<S117>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TBoxRmtLck_enum = ((uint8)0U);/* '<S117>/Switch4' */
MONPRM volatile boolean VIPM_TboxRmtDefrstCtlVld_flg = false;/* '<S118>/Logical Operator3' */
MONPRM volatile uint8 VIPM_TboxRmtDefrstCtl_enum = ((uint8)0U);/* '<S118>/Switch4' */

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
