/*
 * SEMIDRIVE Copyright Statement
 * Copyright (c) SEMIDRIVE. All rights reserved
 *
 * This software and all rights therein are owned by SEMIDRIVE, and are
 * protected by copyright law and other relevant laws, regulations and
 * protection. Without SEMIDRIVE's prior written consent and/or related rights,
 * please do not use this software or any potion thereof in any form or by any
 * means. You may not reproduce, modify or distribute this software except in
 * compliance with the License. Unless required by applicable law or agreed to
 * in writing, software distributed under the License is distributed on
 * an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 * You should have received a copy of the License along with this program.
 * If not, see <http://www.semidrive.com/licenses/>.
 */

/**
 * @file  sdrv_dmac.c
 * @brief Semidrive. Dma
 */

#ifdef __cplusplus
extern "C" {
#endif

#include "sdrv_dmac.h"
#include "debug.h"
#include "Mcu.h"

/* PRQA S 0791 EOF */
/* sdrv dmac dma core config register */
#define SDRV_DMAC_CORE_CFG_REG (0x0u)
#define SDRV_DMAC_CORE_CFG_EN_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_CFG_EN_FIELD_SIZE (1u)

/* sdrv dmac generic timer pre-divider register */
#define SDRV_DMAC_CORE_GTMRPD_REG (0x4u)
#define SDRV_DMAC_CORE_GTMRPD_PD_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_GTMRPD_PD_FIELD_SIZE (16u)
#define SDRV_DMAC_CORE_GTMRPD_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_GTMRPD_LOCK_FIELD_SIZE (1u)

/* sdrv dmac generic timer0 register */
#define SDRV_DMAC_CORE_GTIMER0_REG (0x8u)
#define SDRV_DMAC_CORE_GTMR0_OV_VAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_GTMR0_OV_VAL_FIELD_SIZE (16u)
#define SDRV_DMAC_CORE_GTMR0_EN_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_GTMR0_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_GTMR0_MOD_FIELD_OFFSET (17u)
#define SDRV_DMAC_CORE_GTMR0_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_GTMR0_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_GTMR0_LOCK_FIELD_SIZE (1u)

/* sdrv dmac generic timer1 register */
#define SDRV_DMAC_CORE_GTIMER1_REG (0xCu)
#define SDRV_DMAC_CORE_GTMR1_OV_VAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_GTMR1_OV_VAL_FIELD_SIZE (16u)
#define SDRV_DMAC_CORE_GTMR1_EN_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_GTMR1_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_GTMR1_MOD_FIELD_OFFSET (17u)
#define SDRV_DMAC_CORE_GTMR1_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_GTMR1_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_GTMR1_LOCK_FIELD_SIZE (1u)

/* sdrv dmac generic timer2 register */
#define SDRV_DMAC_CORE_GTIMER2_REG (0x10u)
#define SDRV_DMAC_CORE_GTMR2_OV_VAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_GTMR2_OV_VAL_FIELD_SIZE (16u)
#define SDRV_DMAC_CORE_GTMR2_EN_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_GTMR2_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_GTMR2_MOD_FIELD_OFFSET (17u)
#define SDRV_DMAC_CORE_GTMR2_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_GTMR2_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_GTMR2_LOCK_FIELD_SIZE (1u)

/* sdrv dmac generic timer3 register */
#define SDRV_DMAC_CORE_GTIMER3_REG (0x14u)
#define SDRV_DMAC_CORE_GTMR3_OV_VAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_GTMR3_OV_VAL_FIELD_SIZE (16u)
#define SDRV_DMAC_CORE_GTMR3_EN_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_GTMR3_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_GTMR3_MOD_FIELD_OFFSET (17u)
#define SDRV_DMAC_CORE_GTMR3_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_GTMR3_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_GTMR3_LOCK_FIELD_SIZE (1u)

/* sdrv dmac channel arbitration scheme register */
#define SDRV_DMAC_CORE_CH_ARBIT_SCM_REG (0x18u)
#define SDRV_DMAC_CORE_CH_ARBIT_AXI_W_SCM_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_CH_ARBIT_AXI_W_SCM_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_CH_ARBIT_AXI_R_SCM_FIELD_OFFSET (8u)
#define SDRV_DMAC_CORE_CH_ARBIT_AXI_R_SCM_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_CH_ARBIT_AHB_SCM_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_CH_ARBIT_AHB_SCM_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_CH_ARBIT_FIFO_SCM_FIELD_OFFSET (24u)
#define SDRV_DMAC_CORE_CH_ARBIT_FIFO_SCM_FIELD_SIZE (1u)

/* sdrv dmac fatal control register */
#define SDRV_DMAC_CORE_FATAL_CTRL_REG (0x88u)
#define SDRV_DMAC_CORE_FTL_CTRL_FATAL_CTRL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_FTL_CTRL_FATAL_CTRL_FIELD_SIZE (31u)
#define SDRV_DMAC_CORE_FTL_CTRL_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_FTL_CTRL_LOCK_FIELD_SIZE (1u)

/* sdrv dmac error control register */
#define SDRV_DMAC_CORE_ERR_CTRL_REG (0x94u)
#define SDRV_DMAC_CORE_ERR_CTRL_ERR_CTRL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_ERR_CTRL_ERR_CTRL_FIELD_SIZE (31u)
#define SDRV_DMAC_CORE_ERR_CTRL_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_ERR_CTRL_LOCK_FIELD_SIZE (1u)

/* sdrv dmac warn control register */
#define SDRV_DMAC_CORE_WARN_CTRL_REG (0x98u)
#define SDRV_DMAC_CORE_WARN_CTRL_WARN_CTRL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_WARN_CTRL_WARN_CTRL_FIELD_SIZE (31u)
#define SDRV_DMAC_CORE_WARN_CTRL_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_WARN_CTRL_LOCK_FIELD_SIZE (1u)

/* sdrv dmac dma control register */
#define SDRV_DMAC_CORE_DMA_CTRL_REG (0x9Cu)
#define SDRV_DMAC_CORE_DMA_CTRL_SRST_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_DMA_CTRL_SRST_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_DMA_CTRL_LP_REQ_FIELD_OFFSET (1u)
#define SDRV_DMAC_CORE_DMA_CTRL_LP_REQ_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_DMA_CTRL_LP_ACPT_FIELD_OFFSET (3u)
#define SDRV_DMAC_CORE_DMA_CTRL_LP_ACPT_FIELD_SIZE (1u)

/* sdrv dmac error injection control register */
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_REG (0xA0u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_EN_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_INT_FIELD_OFFSET (1u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_INT_FIELD_SIZE (3u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_INSIG_ERR_INJ_FIELD_OFFSET (4u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_INSIG_ERR_INJ_FIELD_SIZE (2u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_ERR_INJ_CTRL_LOCK_FIELD_SIZE (1u)

/* sdrv dmac lock step error control register */
#define SDRV_DMAC_CORE_LOCK_STEP_ERR_CTRL_REG (0xA4u)
#define SDRV_DMAC_CORE_LOCK_STEP_ERR_CTRL_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_LOCK_STEP_ERR_CTRL_INJ_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_LOCK_STEP_ERR_CTRL_INJ_SEL_FIELD_OFFSET (1u)
#define SDRV_DMAC_CORE_LOCK_STEP_ERR_CTRL_INJ_SEL_FIELD_SIZE (31u)

/* sdrv dmac APB error injection register */
#define SDRV_DMAC_CORE_APB_ERR_INJ_REG (0xA8u)
#define SDRV_DMAC_CORE_APB_ERR_WECC_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_APB_ERR_WECC_INJ_FIELD_SIZE (7u)

/* sdrv dmac APB wdata error injection register */
#define SDRV_DMAC_CORE_APB_WDATA_INJ_REG (0xACu)
#define SDRV_DMAC_CORE_APB_WDATA_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_APB_WDATA_INJ_FIELD_SIZE (32u)

/* sdrv dmac AXI read ECC error injection register */
#define SDRV_DMAC_CORE_AXI_RECC_INJ_REG (0xB0u)
#define SDRV_DMAC_CORE_AXI_RECC_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_AXI_RECC_INJ_FIELD_SIZE (8u)

/* sdrv dmac AXI rdata error injection register */
#define SDRV_DMAC_CORE_AXI_RDATA_INJ_REG (0xB4u)
#define SDRV_DMAC_CORE_AXI_RDATA_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_AXI_RDATA_INJ_FIELD_SIZE (32u)

/* sdrv dmac AXI rdata error injection cont register */
#define SDRV_DMAC_CORE_AXI_RDATA_INJ_CONT_REG (0xB8u)
#define SDRV_DMAC_CORE_AXI_RDATA_INJ_CONT_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_AXI_RDATA_INJ_CONT_INJ_FIELD_SIZE (32u)

/* sdrv dmac AHB read ECC error injection register */
#define SDRV_DMAC_CORE_AHB_RECC_INJ_REG (0xBCu)
#define SDRV_DMAC_CORE_AHB_RECC_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_AHB_RECC_INJ_FIELD_SIZE (7u)

/* sdrv dmac AHB rdata error injection register */
#define SDRV_DMAC_CORE_AHB_RDATA_INJ_REG (0xC0u)
#define SDRV_DMAC_CORE_AHB_RDATA_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_AHB_RDATA_INJ_FIELD_SIZE (32u)

/* sdrv dmac local buffer data error injection register */
#define SDRV_DMAC_CORE_LB_DATAERR_MASK_REG (0xC4u)
#define SDRV_DMAC_CORE_LB_DATAERR_MASK_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_LB_DATAERR_MASK_FIELD_SIZE (32u)

/* sdrv dmac local buffer error injection mask register */
#define SDRV_DMAC_CORE_LB_CODEERR_MASK_REG (0xC8u)
#define SDRV_DMAC_CORE_LB_CODEERR_MASK_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_LB_CODEERR_MASK_FIELD_SIZE (32u)

/* sdrv dmac lock step status register */
#define SDRV_DMAC_CORE_LOCK_STEP_STAT_REG (0xCCu)
#define SDRV_DMAC_CORE_AW_LS_ERR_STAT_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_AW_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_AR_LS_ERR_STAT_FIELD_OFFSET (1u)
#define SDRV_DMAC_CORE_AR_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_B_LS_ERR_STAT_FIELD_OFFSET (2u)
#define SDRV_DMAC_CORE_B_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_R_LS_ERR_STAT_FIELD_OFFSET (3u)
#define SDRV_DMAC_CORE_R_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_W_LS_ERR_STAT_FIELD_OFFSET (4u)
#define SDRV_DMAC_CORE_W_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_CH_LS_ERR_STAT_FIELD_OFFSET (5u)
#define SDRV_DMAC_CORE_CH_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_LBC_LS_ERR_STAT_FIELD_OFFSET (6u)
#define SDRV_DMAC_CORE_LBC_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_PER_LS_ERR_STAT_FIELD_OFFSET (7u)
#define SDRV_DMAC_CORE_PER_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_AHB_LS_ERR_STAT_FIELD_OFFSET (8u)
#define SDRV_DMAC_CORE_AHB_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_APB_LS_ERR_STAT_FIELD_OFFSET (9u)
#define SDRV_DMAC_CORE_APB_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_MISC_LS_ERR_STAT_FIELD_OFFSET (10u)
#define SDRV_DMAC_CORE_MISC_LS_ERR_STAT_FIELD_SIZE (1u)

/* sdrv dmac AHB peripheral address control register */
#define SDRV_DMAC_CORE_PPBASE_ADDR_CTRL_REG (0xF0u)
#define SDRV_DMAC_CORE_PPBASE_ADDR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_PPBASE_ADDR_FIELD_SIZE (16u)
#define SDRV_DMAC_CORE_PPBASE_SIZE_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_PPBASE_SIZE_FIELD_SIZE (8u)
#define SDRV_DMAC_CORE_PPBASE_PPOW_FIELD_OFFSET (24u)
#define SDRV_DMAC_CORE_PPBASE_PPOW_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_PPBASE_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_PPBASE_LOCK_FIELD_SIZE (1u)

/* sdrv dmac local buffer address control register */
#define SDRV_DMAC_CORE_LBC_ADDR_CTRL_REG (0xF4u)
#define SDRV_DMAC_CORE_LBC_ADDR_BASEADDR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_LBC_ADDR_BASEADDR_FIELD_SIZE (16u)
#define SDRV_DMAC_CORE_LBC_ADDR_BASESIZE_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_LBC_ADDR_BASESIZE_FIELD_SIZE (8u)
#define SDRV_DMAC_CORE_LBC_ADDR_OW_FIELD_OFFSET (24u)
#define SDRV_DMAC_CORE_LBC_ADDR_OW_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_LBC_ADDR_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_LBC_ADDR_LOCK_FIELD_SIZE (1u)

/* sdrv dmac dma interrupt enable register */
#define SDRV_DMAC_CORE_DMA_INT_EN_REG (0x7E0u)
#define SDRV_DMAC_CORE_INT_PWDATA_UNCERR_EN_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_INT_PWDATA_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PCTL0_UNCERR_EN_FIELD_OFFSET (1u)
#define SDRV_DMAC_CORE_INT_PCTL0_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PCTL1_UNCERR_EN_FIELD_OFFSET (2u)
#define SDRV_DMAC_CORE_INT_PCTL1_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PADDR_UNCERR_EN_FIELD_OFFSET (3u)
#define SDRV_DMAC_CORE_INT_PADDR_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_UNCERR_EN_FIELD_OFFSET (4u)
#define SDRV_DMAC_CORE_INT_HRDATA_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRESP_UNCERR_EN_FIELD_OFFSET (5u)
#define SDRV_DMAC_CORE_INT_HRESP_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RVLD_UNCERR_EN_FIELD_OFFSET (6u)
#define SDRV_DMAC_CORE_INT_RVLD_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RID_UNCERR_EN_FIELD_OFFSET (7u)
#define SDRV_DMAC_CORE_INT_RID_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_REOBI_UNCERR_EN_FIELD_OFFSET (8u)
#define SDRV_DMAC_CORE_INT_REOBI_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RDATA_UNCERR_EN_FIELD_OFFSET (9u)
#define SDRV_DMAC_CORE_INT_RDATA_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RCTL_UNCERR_EN_FIELD_OFFSET (10u)
#define SDRV_DMAC_CORE_INT_RCTL_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_ARRDY_UNCERR_EN_FIELD_OFFSET (11u)
#define SDRV_DMAC_CORE_INT_ARRDY_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_AWRDY_UNCERR_EN_FIELD_OFFSET (12u)
#define SDRV_DMAC_CORE_INT_AWRDY_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BCTL_UNCERR_EN_FIELD_OFFSET (13u)
#define SDRV_DMAC_CORE_INT_BCTL_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BID_UNCERR_EN_FIELD_OFFSET (14u)
#define SDRV_DMAC_CORE_INT_BID_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BVLD_UNCERR_EN_FIELD_OFFSET (15u)
#define SDRV_DMAC_CORE_INT_BVLD_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_WRDY_UNCERR_EN_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_INT_WRDY_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LBC_UNCERR_EN_FIELD_OFFSET (17u)
#define SDRV_DMAC_CORE_INT_LBC_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LBC_CORERR_EN_FIELD_OFFSET (18u)
#define SDRV_DMAC_CORE_INT_LBC_CORERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CH_UNCERR_EN_FIELD_OFFSET (19u)
#define SDRV_DMAC_CORE_INT_CH_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_FIFO_UNCERR_EN_FIELD_OFFSET (20u)
#define SDRV_DMAC_CORE_INT_FIFO_UNCERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CH_CORERR_EN_FIELD_OFFSET (21u)
#define SDRV_DMAC_CORE_INT_CH_CORERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_FIFO_CORERR_EN_FIELD_OFFSET (22u)
#define SDRV_DMAC_CORE_INT_FIFO_CORERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PWDATA_CORERR_EN_FIELD_OFFSET (23u)
#define SDRV_DMAC_CORE_INT_PWDATA_CORERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RDATA_CORERR_EN_FIELD_OFFSET (24u)
#define SDRV_DMAC_CORE_INT_RDATA_CORERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_CORERR_EN_FIELD_OFFSET (25u)
#define SDRV_DMAC_CORE_INT_HRDATA_CORERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PWDATA_FATAL_EN_FIELD_OFFSET (26u)
#define SDRV_DMAC_CORE_INT_PWDATA_FATAL_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_FATAL_EN_FIELD_OFFSET (27u)
#define SDRV_DMAC_CORE_INT_HRDATA_FATAL_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_AXI_R_MTOR_FATAL_EN_FIELD_OFFSET (28u)
#define SDRV_DMAC_CORE_INT_AXI_R_MTOR_FATAL_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LS_ERR_EN_FIELD_OFFSET (29u)
#define SDRV_DMAC_CORE_INT_LS_ERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CORE1_MTOR_ERR_EN_FIELD_OFFSET (30u)
#define SDRV_DMAC_CORE_INT_CORE1_MTOR_ERR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_INPUT_SIG_ERR_EN_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_INT_INPUT_SIG_ERR_EN_FIELD_SIZE (1u)

/* sdrv dmac interrupt clear register */
#define SDRV_DMAC_CORE_INT_CLR_REG (0x7E4u)
#define SDRV_DMAC_CORE_INT_PWDATA_UNCERR_CLR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_INT_PWDATA_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PCTL0_UNCERR_CLR_FIELD_OFFSET (1u)
#define SDRV_DMAC_CORE_INT_PCTL0_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PCTL1_UNCERR_CLR_FIELD_OFFSET (2u)
#define SDRV_DMAC_CORE_INT_PCTL1_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PADDR_UNCERR_CLR_FIELD_OFFSET (3u)
#define SDRV_DMAC_CORE_INT_PADDR_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_UNCERR_CLR_FIELD_OFFSET (4u)
#define SDRV_DMAC_CORE_INT_HRDATA_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRESP_UNCERR_CLR_FIELD_OFFSET (5u)
#define SDRV_DMAC_CORE_INT_HRESP_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RVLD_UNCERR_CLR_FIELD_OFFSET (6u)
#define SDRV_DMAC_CORE_INT_RVLD_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RID_UNCERR_CLR_FIELD_OFFSET (7u)
#define SDRV_DMAC_CORE_INT_RID_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_REOBI_UNCERR_CLR_FIELD_OFFSET (8u)
#define SDRV_DMAC_CORE_INT_REOBI_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RDATA_UNCERR_CLR_FIELD_OFFSET (9u)
#define SDRV_DMAC_CORE_INT_RDATA_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RCTL_UNCERR_CLR_FIELD_OFFSET (10u)
#define SDRV_DMAC_CORE_INT_RCTL_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_ARRDY_UNCERR_CLR_FIELD_OFFSET (11u)
#define SDRV_DMAC_CORE_INT_ARRDY_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_AWRDY_UNCERR_CLR_FIELD_OFFSET (12u)
#define SDRV_DMAC_CORE_INT_AWRDY_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BCTL_UNCERR_CLR_FIELD_OFFSET (13u)
#define SDRV_DMAC_CORE_INT_BCTL_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BID_UNCERR_CLR_FIELD_OFFSET (14u)
#define SDRV_DMAC_CORE_INT_BID_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BVLD_UNCERR_CLR_FIELD_OFFSET (15u)
#define SDRV_DMAC_CORE_INT_BVLD_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_WRDY_UNCERR_CLR_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_INT_WRDY_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LBC_UNCERR_CLR_FIELD_OFFSET (17u)
#define SDRV_DMAC_CORE_INT_LBC_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LBC_CORERR_CLR_FIELD_OFFSET (18u)
#define SDRV_DMAC_CORE_INT_LBC_CORERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CH_UNCERR_CLR_FIELD_OFFSET (19u)
#define SDRV_DMAC_CORE_INT_CH_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_FIFO_UNCERR_CLR_FIELD_OFFSET (20u)
#define SDRV_DMAC_CORE_INT_FIFO_UNCERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CH_CORERR_CLR_FIELD_OFFSET (21u)
#define SDRV_DMAC_CORE_INT_CH_CORERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_FIFO_CORERR_CLR_FIELD_OFFSET (22u)
#define SDRV_DMAC_CORE_INT_FIFO_CORERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PWDATA_CORERR_CLR_FIELD_OFFSET (23u)
#define SDRV_DMAC_CORE_INT_PWDATA_CORERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RDATA_CORERR_CLR_FIELD_OFFSET (24u)
#define SDRV_DMAC_CORE_INT_RDATA_CORERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_CORERR_CLR_FIELD_OFFSET (25u)
#define SDRV_DMAC_CORE_INT_HRDATA_CORERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PWDATA_FATAL_CLR_FIELD_OFFSET (26u)
#define SDRV_DMAC_CORE_INT_PWDATA_FATAL_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_FATAL_CLR_FIELD_OFFSET (27u)
#define SDRV_DMAC_CORE_INT_HRDATA_FATAL_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_AXI_R_MTOR_FATAL_CLR_FIELD_OFFSET (28u)
#define SDRV_DMAC_CORE_INT_AXI_R_MTOR_FATAL_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LS_ERR_CLR_FIELD_OFFSET (29u)
#define SDRV_DMAC_CORE_INT_LS_ERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CORE1_MTOR_ERR_CLR_FIELD_OFFSET (30u)
#define SDRV_DMAC_CORE_INT_CORE1_MTOR_ERR_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_INPUT_SIG_ERR_CLR_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_INT_INPUT_SIG_ERR_CLR_FIELD_SIZE (1u)

/* sdrv dmac interrupt status register */
#define SDRV_DMAC_CORE_INT_STAT_REG (0x7E8u)
#define SDRV_DMAC_CORE_INT_PWDATA_UNCERR_STAT_FIELD_OFFSET (0u)
#define SDRV_DMAC_CORE_INT_PWDATA_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PCTL0_UNCERR_STAT_FIELD_OFFSET (1u)
#define SDRV_DMAC_CORE_INT_PCTL0_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PCTL1_UNCERR_STAT_FIELD_OFFSET (2u)
#define SDRV_DMAC_CORE_INT_PCTL1_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PADDR_UNCERR_STAT_FIELD_OFFSET (3u)
#define SDRV_DMAC_CORE_INT_PADDR_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_UNCERR_STAT_FIELD_OFFSET (4u)
#define SDRV_DMAC_CORE_INT_HRDATA_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRESP_UNCERR_STAT_FIELD_OFFSET (5u)
#define SDRV_DMAC_CORE_INT_HRESP_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RVLD_UNCERR_STAT_FIELD_OFFSET (6u)
#define SDRV_DMAC_CORE_INT_RVLD_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RID_UNCERR_STAT_FIELD_OFFSET (7u)
#define SDRV_DMAC_CORE_INT_RID_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_REOBI_UNCERR_STAT_FIELD_OFFSET (8u)
#define SDRV_DMAC_CORE_INT_REOBI_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RDATA_UNCERR_STAT_FIELD_OFFSET (9u)
#define SDRV_DMAC_CORE_INT_RDATA_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RCTL_UNCERR_STAT_FIELD_OFFSET (10u)
#define SDRV_DMAC_CORE_INT_RCTL_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_ARRDY_UNCERR_STAT_FIELD_OFFSET (11u)
#define SDRV_DMAC_CORE_INT_ARRDY_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_AWRDY_UNCERR_STAT_FIELD_OFFSET (12u)
#define SDRV_DMAC_CORE_INT_AWRDY_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BCTL_UNCERR_STAT_FIELD_OFFSET (13u)
#define SDRV_DMAC_CORE_INT_BCTL_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BID_UNCERR_STAT_FIELD_OFFSET (14u)
#define SDRV_DMAC_CORE_INT_BID_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_BVLD_UNCERR_STAT_FIELD_OFFSET (15u)
#define SDRV_DMAC_CORE_INT_BVLD_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_WRDY_UNCERR_STAT_FIELD_OFFSET (16u)
#define SDRV_DMAC_CORE_INT_WRDY_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LBC_UNCERR_STAT_FIELD_OFFSET (17u)
#define SDRV_DMAC_CORE_INT_LBC_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LBC_CORERR_STAT_FIELD_OFFSET (18u)
#define SDRV_DMAC_CORE_INT_LBC_CORERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CH_UNCERR_STAT_FIELD_OFFSET (19u)
#define SDRV_DMAC_CORE_INT_CH_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_FIFO_UNCERR_STAT_FIELD_OFFSET (20u)
#define SDRV_DMAC_CORE_INT_FIFO_UNCERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CH_CORERR_STAT_FIELD_OFFSET (21u)
#define SDRV_DMAC_CORE_INT_CH_CORERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_FIFO_CORERR_STAT_FIELD_OFFSET (22u)
#define SDRV_DMAC_CORE_INT_FIFO_CORERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PWDATA_CORERR_STAT_FIELD_OFFSET (23u)
#define SDRV_DMAC_CORE_INT_PWDATA_CORERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_RDATA_CORERR_STAT_FIELD_OFFSET (24u)
#define SDRV_DMAC_CORE_INT_RDATA_CORERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_CORERR_STAT_FIELD_OFFSET (25u)
#define SDRV_DMAC_CORE_INT_HRDATA_CORERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_PWDATA_FATAL_STAT_FIELD_OFFSET (26u)
#define SDRV_DMAC_CORE_INT_PWDATA_FATAL_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_HRDATA_FATAL_STAT_FIELD_OFFSET (27u)
#define SDRV_DMAC_CORE_INT_HRDATA_FATAL_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_AXI_R_MTOR_FATAL_STAT_FIELD_OFFSET (28u)
#define SDRV_DMAC_CORE_INT_AXI_R_MTOR_FATAL_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_LS_ERR_STAT_FIELD_OFFSET (29u)
#define SDRV_DMAC_CORE_INT_LS_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_CORE1_MTOR_ERR_STAT_FIELD_OFFSET (30u)
#define SDRV_DMAC_CORE_INT_CORE1_MTOR_ERR_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CORE_INT_INPUT_SIG_ERR_STAT_FIELD_OFFSET (31u)
#define SDRV_DMAC_CORE_INT_INPUT_SIG_ERR_STAT_FIELD_SIZE (1u)

#define SDRV_DMAC_CORE_CONT_DMA_INT_EN_REG (0x7F0u)
#define SDRV_DMAC_CORE_CONT_DMA_INT_CLR_REG (0x7F4u)
#define SDRV_DMAC_CORE_CONT_DMA_INT_STAT_REG (0x7F8u)

/* offset/size/bitmask seems not used */
#define SDRV_DMAC_CHANNEL_CONFIG_REG (0x00u)
#define SDRV_DMAC_CH_CFG_STOP_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_CFG_STOP_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_CFG_FLUSH_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_CFG_FLUSH_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_CFG_REQUEST_FLUSH_FIELD_OFFSET (2u)
#define SDRV_DMAC_CH_CFG_REQUEST_FLUSH_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_CFG_HALT_FIELD_OFFSET (3u)
#define SDRV_DMAC_CH_CFG_HALT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_CFG_EN_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_CFG_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_CFG_RESUME_FIELD_OFFSET (5u)
#define SDRV_DMAC_CH_CFG_RESUME_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_CFG_ABORT_FIELD_OFFSET (6u)
#define SDRV_DMAC_CH_CFG_ABORT_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_PORT_CONFIG_REG (0x04u)
#define SDRV_DMAC_CH_PORT_CFG_WQOS_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_PORT_CFG_WQOS_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_PORT_CFG_WOT_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_PORT_CFG_WOT_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_PORT_CFG_RQOS_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_PORT_CFG_RQOS_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_PORT_CFG_ROT_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_PORT_CFG_ROT_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_PORT_CFG_CSEL_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_PORT_CFG_CSEL_FIELD_SIZE (8u)
#define SDRV_DMAC_CH_PORT_CFG_PSPDIS_FIELD_OFFSET (28u)
#define SDRV_DMAC_CH_PORT_CFG_PSPDIS_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_PORT_CFG_LOCK_FIELD_OFFSET (31u)
#define SDRV_DMAC_CH_PORT_CFG_LOCK_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_STRIDE_CONFIG_REG (0x08u)
#define SDRV_DMAC_CH_STRIDE_CFG_SRC_FINE_STR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_STRIDE_CFG_SRC_FINE_STR_FIELD_SIZE (16u)
#define SDRV_DMAC_CH_STRIDE_CFG_DST_FIEN_STR_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_STRIDE_CFG_DST_FINE_STR_FIELD_SIZE (16u)

#define SDRV_DMAC_CH_FIREWALL_UP_BOUNDARY_REG (0x0Cu)
#define SDRV_DMAC_CH_FW_UP_BNDY_LOCK_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_FW_UP_BNDY_LOCK_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_FW_UP_BNDY_EN_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_FW_UP_BNDY_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_FW_UP_BNDY_ADDR_FIELD_OFFSET (2u)
#define SDRV_DMAC_CH_FW_UP_BNDY_ADDR_FIELD_SIZE (30u)

#define SDRV_DMAC_CH_FIREWALL_DOWN_BOUNDARY_REG (0x10u)
#define SDRV_DMAC_CH_FW_DOWN_BNDY_LOCK_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_FW_DOWN_BNDY_LOCK_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_FW_DOWN_BNDY_EN_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_FW_DOWN_BNDY_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_FW_DOWN_BNDY_ADDR_FIELD_OFFSET (2u)
#define SDRV_DMAC_CH_FW_DOWN_BNDY_ADDR_FIELD_SIZE (30u)

#define SDRV_DMAC_CH_PATTERN_MATCH_CONFIG_REG (0x14u)
#define SDRV_DMAC_CH_PATTERN_MATCH_CFG_PATTERN_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_PATTERN_MATCH_CFG_PATTERN_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_PATTERN_MASK_CONFIG_REG (0x18u)
#define SDRV_DMAC_CH_PATTERN_MASK_CFG_MASK_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_PATTERN_MASK_CFG_MASK_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_SECOND_OPERATION_DATA_REG (0x1Cu)
#define SDRV_DMAC_CH_SECOND_OP_DATA_OPD2_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SECOND_OP_DATA_OPD2_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_SOURCE_ADDRESS_REG (0x20u)
#define SDRV_DMAC_CH_SRC_ADDR_SRC_ADR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SRC_ADDR_SRC_ADR_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_DESTINATION_ADDRESS_REG (0x24u)
#define SDRV_DMAC_CH_DST_ADDR_DST_ADR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DST_ADDR_DST_ADR_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_TRANSACTION_CTRL_REG (0x28u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_BL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_BL_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_BSIZE_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_BSIZE_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_PSEL_FIELD_OFFSET (7u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_PSEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_BST_TYPE_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_BST_TYPE_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_STR_POL_FIELD_OFFSET (9u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_STR_POL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_PORT_FIELD_OFFSET (10u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_PORT_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_CACHE_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_SRC_CACHE_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_BL_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_BL_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_BSIZE_FIELD_OFFSET (20u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_BSIZE_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_PSEL_FIELD_OFFSET (23u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_PSEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_BST_TYPE_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_BST_TYPE_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_STR_POL_FIELD_OFFSET (25u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_STR_POL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_PORT_FIELD_OFFSET (26u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_PORT_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_CACHE_FIELD_OFFSET (28u)
#define SDRV_DMAC_CH_TRANSACTION_CTRL_DST_CACHE_FIELD_SIZE (4u)

#define SDRV_DMAC_CH_DATA_BLOCK_CONFIG_REG (0x2Cu)
/* loop mode 0 */
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_FIELD_SIZE (24u)
/* loop mode 1 - unifixed */
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP1_BS_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP1_BS_FIELD_SIZE (12u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP1_LPCNT_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP1_LPCNT_FIELD_SIZE (12u)
/* loop mode 2 - fixed */
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP2_LPSIZ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP2_LPSIZ_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP2_TTSIZFIELD_OFFSET (4u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_SIZE_LP2_TTSIZFIELD_SIZE (20u)

#define SDRV_DMAC_CH_DATA_BLK_CFG_LP_MOD_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_LP_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_SWT_EVT_CTR_FIELD_OFFSET (26u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_SWT_EVT_CTR_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_SRC_STR_EN_FIELD_OFFSET (28u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_SRC_STR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_DST_STR_EN_FIELD_OFFSET (29u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_DST_STR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_MOD_FIELD_OFFSET (30u)
#define SDRV_DMAC_CH_DATA_BLK_CFG_BUF_MOD_FIELD_SIZE (2u)

#define SDRV_DMAC_CH_OPERATION_MODE_REG (0x30u)
#define SDRV_DMAC_CH_OP_MOD_FLOW_CTR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_OP_MOD_FLOW_CTR_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_OP_MOD_TR_MOD_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_OP_MOD_TR_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_OP_MOD_MAD_CRC_MOD_FIELD_OFFSET (6u)
#define SDRV_DMAC_CH_OP_MOD_MAD_CRC_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_OP_MOD_DATA_CRC_MOD_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_OP_MOD_DATA_CRC_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_OP_MOD_DATA_CRC_SEL_FIELD_OFFSET (10u)
#define SDRV_DMAC_CH_OP_MOD_DATA_CRC_SEL_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_OP_MOD_PTN_DET_MOD_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_OP_MOD_PTN_DET_MOD_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_OP_MOD_ACK_ASSERT_FIELD_OFFSET (15u)
#define SDRV_DMAC_CH_OP_MOD_ACK_ADDERT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_OP_MOD_FST_MAD_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_OP_MOD_FST_MAD_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_OP_MOD_LST_MAD_FIELD_OFFSET (17u)
#define SDRV_DMAC_CH_OP_MOD_LST_MAD_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_OP_MOD_SRC_STR_SEL_FIELD_OFFSET (18u)
#define SDRV_DMAC_CH_OP_MOD_SRC_STR_SEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_OP_MOD_SRC_CORSE_STR_FIELD_OFFSET (19u)
#define SDRV_DMAC_CH_OP_MOD_SRC_CORSE_STR_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_OP_MOD_DST_STR_SEL_FIELD_OFFSET (23u)
#define SDRV_DMAC_CH_OP_MOD_DST_STR_SEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_OP_MOD_DST_CORSE_STR_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_OP_MOD_DST_CORSE_STR_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_OP_MOD_HALT_EN_FIELD_OFFSET (28u)
#define SDRV_DMAC_CH_OP_MOD_HALT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_OP_MOD_MAD_INTR_FIELD_OFFSET (29u)
#define SDRV_DMAC_CH_OP_MOD_MAD_INTR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_OP_MOD_TIG_MOD_FIELD_OFFSET (30u)
#define SDRV_DMAC_CH_OP_MOD_TIG_MOD_FIELD_SIZE (2u)

#define SDRV_DMAC_CH_OPERATION_DATA_REG (0x34u)
#define SDRV_DMAC_CH_OP_DATA_OPD_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_OP_DATA_OPD_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_MAD_CRC_REG (0x38u)
#define SDRV_DMAC_CH_MAD_CRC_MADCRC_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_MAD_CRC_MADCRC_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_LINK_ADDRESS_REG (0x3Cu)
#define SDRV_DMAC_CH_LINK_ADDR_LLI_ADR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_LINK_ADDR_LLI_ADR_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_SHADOW_SOURCE_ADDRESS_REG (0x40u)
#define SDRV_DMAC_CH_SHD_SRC_ADDR_SHD_SRC_ADR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_SRC_ADDR_SHD_SRC_ADR_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_SHADOW_DESTINATION_ADDRESS_REG (0x44u)
#define SDRV_DMAC_CH_SHD_DST_ADDR_SHD_DST_ADR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_DST_ADDR_SHD_DST_ADR_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_SHADOW_TRANSACTION_CONTROL_REG (0x48u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_BL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_BL_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_BSIZE_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_BSIZE_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_PSEL_FIELD_OFFSET (7u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_PSEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_BST_TYPE_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_BST_TYPE_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_STR_POL_FIELD_OFFSET (9u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_STR_POL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_PORT_FIELD_OFFSET (10u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_PORT_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_CACHE_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_SRC_CACHE_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_BL_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_BL_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_BSIZE_FIELD_OFFSET (20u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_BSIZE_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_PSEL_FIELD_OFFSET (23u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_PSEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_BST_TYPE_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_BST_TYPE_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_STR_POL_FIELD_OFFSET (25u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_STR_POL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_PORT_FIELD_OFFSET (26u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_PORT_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_CACHE_FIELD_OFFSET (28u)
#define SDRV_DMAC_CH_SHD_TRANSACTION_CTRL_SHD_DST_CACHE_FIELD_SIZE (4u)

#define SDRV_DMAC_CH_SHADOW_DATA_BLOCK_REG (0x4Cu)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_BUF_SIZE_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_BUF_SIZE_FIELD_SIZE (24u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_LP_MOD_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_LP_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_SWT_EVT_CTR_FIELD_OFFSET (26u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_SWT_EVT_CTR_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_SRC_STR_EN_FIELD_OFFSET (28u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_SRC_STR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_DST_STR_EN_FIELD_OFFSET (29u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_DST_STR_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_BUF_MOD_FIELD_OFFSET (30u)
#define SDRV_DMAC_CH_SHD_DATA_BLK_CFG_SHD_BUF_MOD_FIELD_SIZE (2u)

#define SDRV_DMAC_CH_SHADOW_OPERATION_MODE_REG (0x50u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_FLOW_CTR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_FLOW_CTR_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_TR_MOD_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_TR_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_MAD_CRC_MOD_FIELD_OFFSET (6u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_MAD_CRC_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DATA_CRC_MOD_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DATA_CRC_MOD_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DATA_CRC_SEL_FIELD_OFFSET (10u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DATA_CRC_SEL_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_PTN_DET_MOD_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_PTN_DET_MOD_FIELD_SIZE (3u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_ACK_ASSERT_FIELD_OFFSET (15u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_ACK_ADDERT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_FST_MAD_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_FST_MAD_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_LST_MAD_FIELD_OFFSET (17u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_LST_MAD_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_SRC_STR_SEL_FIELD_OFFSET (18u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_SRC_STR_SEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_SRC_CORSE_STR_FIELD_OFFSET (19u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_SRC_CORSE_STR_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DST_STR_SEL_FIELD_OFFSET (23u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DST_STR_SEL_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DST_CORSE_STR_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_DST_CORSE_STR_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_HALT_EN_FIELD_OFFSET (28u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_HALT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_MAD_INTR_FIELD_OFFSET (29u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_MAD_INTR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_TIG_MOD_FIELD_OFFSET (30u)
#define SDRV_DMAC_CH_SHD_OP_MOD_SHD_TIG_MOD_FIELD_SIZE (2u)

#define SDRV_DMAC_CH_SHADOW_OPERATION_DATA_REG (0x54u)
#define SDRV_DMAC_CH_SHD_OP_DATA_SHD_OPD_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_OP_DATA_SHD_OPD_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_SHADOW_MAD_CRC_REG (0x58u)
#define SDRV_DMAC_CH_SHD_MAD_CRC_SHD_MADCRC_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_MAD_CRC_SHD_MADCRC_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_SHADOW_LINK_ADDRESS_REG (0x5Cu)
#define SDRV_DMAC_CH_SHD_LINK_ADDR_SHD_LADR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SHD_LINK_ADDR_SHD_LADR_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_FIREWALL_TIME_REG (0x60u)
#define SDRV_DMAC_CH_FW_TIME_CH_TO_VAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_FW_TIME_CH_TO_VAL_FIELD_SIZE (16u)
#define SDRV_DMAC_CH_FW_TIME_CH_TO_EN_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_FW_TIME_CH_TO_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_FW_TIME_GTMR_SEL_FIELD_OFFSET (17u)
#define SDRV_DMAC_CH_FW_TIME_GTMR_SEL_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_FW_TIME_FW_IN_PERM_FIELD_OFFSET (20u)
#define SDRV_DMAC_CH_FW_TIME_FW_IN_PERM_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_FW_TIME_FW_OUT_PERM_FIELD_OFFSET (22u)
#define SDRV_DMAC_CH_FW_TIME_FW_OUT_PERM_FIELD_SIZE (2u)
#define SDRV_DMAC_CH_FW_TIME_CH_PRE_DIVIDER_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_FW_TIME_CH_PRE_DIVIDER_FIELD_SIZE (4u)

#define SDRV_DMAC_CH_PROGRAMM_SEQUENCE_CTRL_REG (0x64u)
#define SDRV_DMAC_CH_PROG_SEQ_CTRL_PS_CNT_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_PROG_SEQ_CTRL_PS_CNT_FIELD_SIZE (8u)

#define SDRV_DMAC_CH_SOFTWARE_HANDSHAKE_REG (0x68u)
#define SDRV_DMAC_CH_SW_HS_REQ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_SW_HS_REQ_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_CHANNEL_TURBO_REG (0x6Cu)
#define SDRV_DMAC_CH_CHANNEL_TURBO_CH_TURBO_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_CHANNEL_TURBO_CH_TURBO_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_CHANNEL_TURBO_PREAD_MOD_FIELD_OFFSET (2u)
#define SDRV_DMAC_CH_CHANNEL_TURBO_PREAD_MOD_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_DMA_CH_LOW_POWER_REG (0x70u)
#define SDRV_DMAC_CH_DMA_CH_LOW_POWER_LP_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DMA_CH_LOW_POWER_LP_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_INTERRUPT_ENABLE_REG (0x74u)
#define SDRV_DMAC_CH_INT_EN_HS_E2E_COR_ERR_INT_EN_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_INT_EN_HS_E2E_COR_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_HS_E2E_UNC_ERR_INT_EN_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_INT_EN_HS_E2E_UNC_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_CH_FIFO_ECC_COR_ERR_INT_EN_FIELD_OFFSET (2u)
#define SDRV_DMAC_CH_INT_EN_CH_FIFO_ECC_COR_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_CH_FIFO_ECC_UNC_ERR_INT_EN_FIELD_OFFSET (3u)
#define SDRV_DMAC_CH_INT_EN_CH_FIFO_ECC_UNC_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_AHB_RD_ERR_INT_EN_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_INT_EN_AHB_RD_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_AHB_WR_ERR_INT_EN_FIELD_OFFSET (5u)
#define SDRV_DMAC_CH_INT_EN_AHB_WR_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_AXI_RD_ERR_INT_EN_FIELD_OFFSET (6u)
#define SDRV_DMAC_CH_INT_EN_AXI_RD_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_AXI_WR_ERR_INT_EN_FIELD_OFFSET (7u)
#define SDRV_DMAC_CH_INT_EN_AXI_WR_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_CH_LINK_ERR_INT_EN_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_INT_EN_CH_LINK_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_MAD_CRC_ERR_INT_EN_FIELD_OFFSET (9u)
#define SDRV_DMAC_CH_INT_EN_MAD_CRC_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_FW_RD_ERR_INT_EN_FIELD_OFFSET (10u)
#define SDRV_DMAC_CH_INT_EN_FW_RD_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_FW_WR_ERR_INT_EN_FIELD_OFFSET (11u)
#define SDRV_DMAC_CH_INT_EN_FW_WR_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_DATA_CRC_ERR_INT_EN_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_INT_EN_DATA_CRC_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_PTERN_DET_INT_EN_FIELD_OFFSET (13u)
#define SDRV_DMAC_CH_INT_EN_PTERN_DET_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_LST_MAD_DONE_INT_EN_FIELD_OFFSET (14u)
#define SDRV_DMAC_CH_INT_EN_LST_MAD_DONE_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_EVRY_MAD_DONE_INT_EN_FIELD_OFFSET (15u)
#define SDRV_DMAC_CH_INT_EN_EVRY_MAD_DONE_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_CH_STOP_INT_EN_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_INT_EN_CH_STOP_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_CH_FLUSH_INT_EN_FIELD_OFFSET (17u)
#define SDRV_DMAC_CH_INT_EN_CH_FLUSH_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_REQ_FLUSH_INT_EN_FIELD_OFFSET (18u)
#define SDRV_DMAC_CH_INT_EN_REQ_FLUSH_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_CH_HALT_INT_EN_FIELD_OFFSET (19u)
#define SDRV_DMAC_CH_INT_EN_CH_HALT_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_CH_ABORT_INT_EN_FIELD_OFFSET (20u)
#define SDRV_DMAC_CH_INT_EN_CH_ABORT_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_REQ_TO_INT_EN_FIELD_OFFSET (21u)
#define SDRV_DMAC_CH_INT_EN_REQ_TO_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_SWT_EVT_INT_EN_FIELD_OFFSET (22u)
#define SDRV_DMAC_CH_INT_EN_SWT_EVT_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_HS_COMP_INT_EN_FIELD_OFFSET (23u)
#define SDRV_DMAC_CH_INT_EN_HS_COMP_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_PTERN_POL_MISMATCH_INT_EN_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_INT_EN_PTERN_POL_MISMATCH_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_HS_E2E_FATAL_ERR_INT_EN_FIELD_OFFSET (25u)
#define SDRV_DMAC_CH_INT_EN_HS_E2E_FATAL_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_AXI_OT_UTID_ERR_INT_EN_FIELD_OFFSET (26u)
#define SDRV_DMAC_CH_INT_EN_AXI_OT_UTID_ERR_INT_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_EN_PROG_SEQ_ERR_INT_EN_FIELD_OFFSET (27u)
#define SDRV_DMAC_CH_INT_EN_PROG_SEQ_ERR_INT_EN_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_INTERRUPT_CLEAR_REG (0x78u)
#define SDRV_DMAC_CH_INT_CLR_HS_E2E_COR_ERR_INT_CLR_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_INT_CLR_HS_E2E_COR_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_HS_E2E_UNC_ERR_INT_CLR_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_INT_CLR_HS_E2E_UNC_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_CH_FIFO_ECC_COR_ERR_INT_CLR_FIELD_OFFSET (2u)
#define SDRV_DMAC_CH_INT_CLR_CH_FIFO_ECC_COR_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_CH_FIFO_ECC_UNC_ERR_INT_CLR_FIELD_OFFSET (3u)
#define SDRV_DMAC_CH_INT_CLR_CH_FIFO_ECC_UNC_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_AHB_RD_ERR_INT_CLR_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_INT_CLR_AHB_RD_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_AHB_WR_ERR_INT_CLR_FIELD_OFFSET (5u)
#define SDRV_DMAC_CH_INT_CLR_AHB_WR_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_AXI_RD_ERR_INT_CLR_FIELD_OFFSET (6u)
#define SDRV_DMAC_CH_INT_CLR_AXI_RD_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_AXI_WR_ERR_INT_CLR_FIELD_OFFSET (7u)
#define SDRV_DMAC_CH_INT_CLR_AXI_WR_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_CH_LINK_ERR_INT_CLR_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_INT_CLR_CH_LINK_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_MAD_CRC_ERR_INT_CLR_FIELD_OFFSET (9u)
#define SDRV_DMAC_CH_INT_CLR_MAD_CRC_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_FW_RD_ERR_INT_CLR_FIELD_OFFSET (10u)
#define SDRV_DMAC_CH_INT_CLR_FW_RD_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_FW_WR_ERR_INT_CLR_FIELD_OFFSET (11u)
#define SDRV_DMAC_CH_INT_CLR_FW_WR_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_DATA_CRC_ERR_INT_CLR_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_INT_CLR_DATA_CRC_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_PTERN_DET_INT_CLR_FIELD_OFFSET (13u)
#define SDRV_DMAC_CH_INT_CLR_PTERN_DET_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_LST_MAD_DONE_INT_CLR_FIELD_OFFSET (14u)
#define SDRV_DMAC_CH_INT_CLR_LST_MAD_DONE_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_EVRY_MAD_DONE_INT_CLR_FIELD_OFFSET (15u)
#define SDRV_DMAC_CH_INT_CLR_EVRY_MAD_DONE_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_CH_STOP_INT_CLR_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_INT_CLR_CH_STOP_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_CH_FLUSH_INT_CLR_FIELD_OFFSET (17u)
#define SDRV_DMAC_CH_INT_CLR_CH_FLUSH_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_REQ_FLUSH_INT_CLR_FIELD_OFFSET (18u)
#define SDRV_DMAC_CH_INT_CLR_REQ_FLUSH_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_CH_HALT_INT_CLR_FIELD_OFFSET (19u)
#define SDRV_DMAC_CH_INT_CLR_CH_HALT_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_CH_ABORT_INT_CLR_FIELD_OFFSET (20u)
#define SDRV_DMAC_CH_INT_CLR_CH_ABORT_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_REQ_TO_INT_CLR_FIELD_OFFSET (21u)
#define SDRV_DMAC_CH_INT_CLR_REQ_TO_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_SWT_EVT_INT_CLR_FIELD_OFFSET (22u)
#define SDRV_DMAC_CH_INT_CLR_SWT_EVT_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_HS_COMP_INT_CLR_FIELD_OFFSET (23u)
#define SDRV_DMAC_CH_INT_CLR_HS_COMP_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_PTERN_POL_MISMATCH_INT_CLR_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_INT_CLR_PTERN_POL_MISMATCH_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_HS_E2E_FATAL_ERR_INT_CLR_FIELD_OFFSET (25u)
#define SDRV_DMAC_CH_INT_CLR_HS_E2E_FATAL_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_AXI_OT_UTID_ERR_INT_CLR_FIELD_OFFSET (26u)
#define SDRV_DMAC_CH_INT_CLR_AXI_OT_UTID_ERR_INT_CLR_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_CLR_PROG_SEQ_ERR_INT_CLR_FIELD_OFFSET (27u)
#define SDRV_DMAC_CH_INT_CLR_PROG_SEQ_ERR_INT_CLR_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_INTERRUPT_STATUS_REG (0x7Cu)
#define SDRV_DMAC_CH_INT_STAT_HS_E2E_COR_ERR_INT_STAT_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_INT_STAT_HS_E2E_COR_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_HS_E2E_UNC_ERR_INT_STAT_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_INT_STAT_HS_E2E_UNC_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_CH_FIFO_ECC_COR_ERR_INT_STAT_FIELD_OFFSET (2u)
#define SDRV_DMAC_CH_INT_STAT_CH_FIFO_ECC_COR_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_CH_FIFO_ECC_UNC_ERR_INT_STAT_FIELD_OFFSET (3u)
#define SDRV_DMAC_CH_INT_STAT_CH_FIFO_ECC_UNC_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_AHB_RD_ERR_INT_STAT_FIELD_OFFSET (4u)
#define SDRV_DMAC_CH_INT_STAT_AHB_RD_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_AHB_WR_ERR_INT_STAT_FIELD_OFFSET (5u)
#define SDRV_DMAC_CH_INT_STAT_AHB_WR_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_AXI_RD_ERR_INT_STAT_FIELD_OFFSET (6u)
#define SDRV_DMAC_CH_INT_STAT_AXI_RD_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_AXI_WR_ERR_INT_STAT_FIELD_OFFSET (7u)
#define SDRV_DMAC_CH_INT_STAT_AXI_WR_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_CH_LINK_ERR_INT_STAT_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_INT_STAT_CH_LINK_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_MAD_CRC_ERR_INT_STAT_FIELD_OFFSET (9u)
#define SDRV_DMAC_CH_INT_STAT_MAD_CRC_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_FW_RD_ERR_INT_STAT_FIELD_OFFSET (10u)
#define SDRV_DMAC_CH_INT_STAT_FW_RD_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_FW_WR_ERR_INT_STAT_FIELD_OFFSET (11u)
#define SDRV_DMAC_CH_INT_STAT_FW_WR_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_DATA_CRC_ERR_INT_STAT_FIELD_OFFSET (12u)
#define SDRV_DMAC_CH_INT_STAT_DATA_CRC_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_PTERN_DET_INT_STAT_FIELD_OFFSET (13u)
#define SDRV_DMAC_CH_INT_STAT_PTERN_DET_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_LST_MAD_DONE_INT_STAT_FIELD_OFFSET (14u)
#define SDRV_DMAC_CH_INT_STAT_LST_MAD_DONE_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_EVRY_MAD_DONE_INT_STAT_FIELD_OFFSET (15u)
#define SDRV_DMAC_CH_INT_STAT_EVRY_MAD_DONE_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_CH_STOP_INT_STAT_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_INT_STAT_CH_STOP_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_CH_FLUSH_INT_STAT_FIELD_OFFSET (17u)
#define SDRV_DMAC_CH_INT_STAT_CH_FLUSH_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_REQ_FLUSH_INT_STAT_FIELD_OFFSET (18u)
#define SDRV_DMAC_CH_INT_STAT_REQ_FLUSH_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_CH_HALT_INT_STAT_FIELD_OFFSET (19u)
#define SDRV_DMAC_CH_INT_STAT_CH_HALT_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_CH_ABORT_INT_STAT_FIELD_OFFSET (20u)
#define SDRV_DMAC_CH_INT_STAT_CH_ABORT_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_REQ_TO_INT_STAT_FIELD_OFFSET (21u)
#define SDRV_DMAC_CH_INT_STAT_REQ_TO_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_SWT_EVT_INT_STAT_FIELD_OFFSET (22u)
#define SDRV_DMAC_CH_INT_STAT_SWT_EVT_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_HS_COMP_INT_STAT_FIELD_OFFSET (23u)
#define SDRV_DMAC_CH_INT_STAT_HS_COMP_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_PTERN_POL_MISMATCH_INT_STAT_FIELD_OFFSET (24u)
#define SDRV_DMAC_CH_INT_STAT_PTERN_POL_MISMATCH_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_HS_E2E_FATAL_ERR_INT_STAT_FIELD_OFFSET (25u)
#define SDRV_DMAC_CH_INT_STAT_HS_E2E_FATAL_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_AXI_OT_UTID_ERR_INT_STAT_FIELD_OFFSET (26u)
#define SDRV_DMAC_CH_INT_STAT_AXI_OT_UTID_ERR_INT_STAT_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_STAT_PROG_SEQ_ERR_INT_STAT_FIELD_OFFSET (27u)
#define SDRV_DMAC_CH_INT_STAT_PROG_SEQ_ERR_INT_STAT_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_DATA_RD_CRC_INITIAL_VALUE_REG (0x80u)
#define SDRV_DMAC_CH_DATA_RD_CRC_INIT_VAL_INITVAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DATA_RD_CRC_INIT_VAL_INITVAL_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_DATA_WR_CRC_INITIAL_VALUE_REG (0x84u)
#define SDRV_DMAC_CH_DATA_WR_CRC_INIT_VAL_INITVAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DATA_WR_CRC_INIT_VAL_INITVAL_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_MAD_CRC_INITIAL_VALUE_REG (0x88u)
#define SDRV_DMAC_CH_MAD_CRC_INIT_VAL_INITVAL_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_MAD_CRC_INIT_VAL_INITVAL_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_STATUS_REG (0x8Cu)
#define SDRV_DMAC_CH_STAT_CH_CTRL_FSM_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_STAT_CH_CTRL_FSM_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_STAT_CH_SRC_FSM_FIELD_OFFSET (8u)
#define SDRV_DMAC_CH_STAT_CH_SRC_FSM_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_STAT_CH_DST_FSM_FIELD_OFFSET (16u)
#define SDRV_DMAC_CH_STAT_CH_DST_FSM_FIELD_SIZE (4u)

#define SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG1 (0x90u)
#define SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG1_REG_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG1_REG_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG2 (0x94u)
#define SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG2_REG_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG2_REG_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_DATA_TRANSFER_REG (0x98u)
#define SDRV_DMAC_CH_DATA_TR_DATA_NUM_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_DATA_TR_DATA_NUM_FIELD_SIZE (32u)

#define SDRV_DMAC_CH_INTERRUPT_ERROR_INJECT_REG (0x9Cu)
#define SDRV_DMAC_CH_INT_ERR_INJ_ERR_INJ_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_INT_ERR_INJ_ERR_INJ_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_INT_ERR_INJ_ERR_INJ_EN_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_INT_ERR_INJ_ERR_INJ_EN_FIELD_SIZE (1u)

#define SDRV_DMAC_CH_HANDSHAKE_ERROR_INJECT_REG (0x100u)
#define SDRV_DMAC_CH_HS_ERR_INJ_HS_EJ_EN_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_HS_ERR_INJ_HS_EJ_EN_FIELD_SIZE (1u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_BW_CODE_INJ_FIELD_OFFSET (1u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_BW_CODE_INJ_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_BW_DATA_INJ_FIELD_OFFSET (5u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_BW_DATA_INJ_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_FW_CODE_NJ_FIELD_OFFSET (9u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_FW_CODE_NJ_FIELD_SIZE (4u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_FW_DATA_INJ_FIELD_OFFSET (13u)
#define SDRV_DMAC_CH_HS_ERR_INJ_DMA_FW_DATA_INJ_FIELD_SIZE (4u)

#define SDRV_DMAC_CH_LINK_STATUS_1_REG (0x104u)
#define SDRV_DMAC_CH_LINK_STAT1_CH_LINK_REQ_OUT_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_LINK_STAT1_CH_LINK_REQ_OUT_FIELD_SIZE (24u)

#define SDRV_DMAC_CH_LINK_STATUS_2_REG (0x108u)
#define SDRV_DMAC_CH_LINK_STAT2_CH_LINK_REQ_IN_FIELD_OFFSET (0u)
#define SDRV_DMAC_CH_LINK_STAT2_CH_LINK_REQ_IN_FIELD_SIZE (24u)

/* loop mode 0 */
#define LP0_SIZE(n) (n - 1)
#define GET_LP0_SIZE(n) (n + 1)
/* loop mode 1 */
#define LP1_SIZE(n) ((n - 1) & 0xfff)
#define LP1_CNT(n) ((n - 1) << 12)
#define GET_LP1_SIZE(n) ((n & 0xfff) + 1)
#define GET_LP1_CNT(n) (((n & 0xfff000) >> 12) + 1)
/* loop mode 2 */
#define LP2_TT(n) (((n - 1) << 4) & 0xfffff0)

#define GET_LP2_LPSIZE(n) (1 << (n & 0xf))
#define GET_LP2_TT(n) (((n & 0xfffff0) >> 4) + 1)
#define DMA_CHANNEL_BASE_OFFSET (0x10000)
#define DMAC_CH_BASE(base, chann)                                              \
    (0x2000 * (chann) + (base) + DMA_CHANNEL_BASE_OFFSET)
#define DMAC_LOCAL_BUFFER_OFF (0x8000)
#define DMAC_LOCAL_BUFFER_MAX_BYTES (4096)

typedef union {
    struct {
        uint32 stop : 1;
        uint32 flush : 1;
        uint32 req_flush : 1;
        uint32 halt : 1;
        uint32 en : 1;
        uint32 resume : 1;
        uint32 ablort : 1;
        uint32 reserved : 25;
    };
    uint32 v;
} dmac_ch_cfg_t;

typedef union {
    struct {
        uint32 wqos : 4;
        uint32 wot : 4;
        uint32 rqos : 4;
        uint32 rot : 4;
        uint32 csel : 8;
        uint32 reserved : 4;
        uint32 pspdis : 1;
        uint32 reserved1 : 2;
        uint32 lock : 1;
    };
    uint32 v;
} dmac_ch_port_cfg_t;

typedef union {
    struct {
        uint32 src_fine_stride : 16;
        uint32 dst_fine_stride : 16;
    };
    uint32 v;
} dmac_ch_stride_cfg_t;

typedef union {
    struct {
        uint32 lock : 1;
        uint32 fw_up_en : 1;
        uint32 fw_addr_up : 30;
    };
    uint32 v;
} dmac_ch_fw_up_boundary_t;

typedef union {
    struct {
        uint32 lock : 1;
        uint32 fw_dw_en : 1;
        uint32 fw_addr_dw : 30;
    };
    uint32 v;
} dmac_ch_fw_dw_boundary_t;

typedef union {
    struct {
        uint32 pattern : 32;
    };
    uint32 v;
} dmac_ch_patn_match_cfg_t;

typedef union {
    struct {
        uint32 mask : 32;
    };
    uint32 v;
} dmac_ch_patn_mask_cfg_t;

typedef union {
    struct {
        uint32 opd2 : 32;
    };
    uint32 v;
} dmac_ch_op2_data_t;

typedef union {
    struct {
        uint32 ch_timeout_value : 16;
        uint32 ch_timeout_en : 1;
        uint32 gtmr_sel : 2;
        uint32 reserved : 1;
        uint32 fw_in_perm : 2;
        uint32 fw_out_perm : 2;
        uint32 ch_pre_divider : 4;
        uint32 reserved1 : 4;
    };
    uint32 v;
} dmac_ch_fw_time_t;

typedef union {
    struct {
        uint32 ps_cnt : 8;
        uint32 reserved : 24;
    };
    uint32 v;
} dmac_ch_ps_ctrl_t;

typedef union {
    struct {
        uint32 req : 1;
        uint32 reserved : 31;
    };
    uint32 v;
} dmac_ch_swhs_t;

typedef union {
    struct {
        uint32 ch_turbo : 1;
        uint32 reserved : 1;
        uint32 pre_rd_md : 1;
        uint32 reserved1 : 29;
    };
    uint32 v;
} dmac_ch_turbo_t;

typedef union {
    struct {
        uint32 lpower : 1;
        uint32 reserved : 31;
    };
    uint32 v;
} dmac_ch_lp_t;

typedef union {
    struct {
        uint32 hs_e2e_cor_err : 1;
        uint32 hs_e2e_unc_err : 1;
        uint32 ch_fifo_ecc_cor_err : 1;
        uint32 ch_fifo_ecc_unc_err : 1;
        uint32 ahb_rd_err : 1;
        uint32 ahb_wr_err : 1;
        uint32 axi_rd_err : 1;
        uint32 axi_wr_err : 1;
        uint32 ch_link_err : 1;
        uint32 mad_crc_err : 1;
        uint32 fw_rd_err : 1;
        uint32 fw_wr_err : 1;
        uint32 data_crc_err : 1;
        uint32 patn_det : 1;
        uint32 last_mad_done : 1;
        uint32 first_mad_done : 1;
        uint32 ch_stop : 1;
        uint32 ch_flush : 1;
        uint32 req_flush : 1;
        uint32 ch_halt : 1;
        uint32 ch_abort : 1;
        uint32 req_timeout : 1;
        uint32 swt_evt : 1;
        uint32 hs_comp : 1;
        uint32 patn_poll_mismatch : 1;
        uint32 hs_e2e_fatal : 1;
        uint32 axi_ot_tuid_err : 1;
        uint32 ps_err : 1;
        uint32 reserved : 1;
    };
    uint32 v;
} dmac_ch_int_t;

typedef union {
    struct {
        uint32 init_value : 32;
    };
    uint32 v;
} dmac_ch_crc_init_t;

typedef union {
    struct {
        uint32 ctrl_fsm : 4;
        uint32 reserved : 4;
        uint32 src_fsm : 4;
        uint32 reserved1 : 4;
        uint32 dst_fsm : 4;
        uint32 reserved2 : 12;
    };
    uint32 v;
} dmac_ch_status_t;

typedef union {
    struct {
        uint32 reg : 32;
    };
    uint32 v;
} dmac_ch_reg_fc_t;

typedef union {
    struct {
        uint32 num : 32;
    };
    uint32 v;
} dmac_ch_data_xfer_t;

typedef union {
    struct {
        uint32 err_inj : 1;
        uint32 en : 1;
        uint32 reserved : 1;
    };
    uint32 v;
} dmac_ch_int_err_inj_t;

typedef union {
    struct {
        uint32 hs_ej_en : 1;
        uint32 dma_bw_cod_inj : 4;
        uint32 dma_bw_data_inj : 4;
        uint32 dma_fw_cod_inj : 4;
        uint32 dma_fw_data_inj : 4;
        uint32 reserved : 15;
    };
    uint32 v;
} dmac_ch_hs_err_inj_t;

typedef union {
    struct {
        uint32 req : 24;
        uint32 reserved : 8;
    };
    uint32 v;
} dmac_ch_link_status_t;

/* link list mad config */
typedef union {
    struct {
        uint32 src;
    };
    uint32 v;
} dmac_ch_src_t;

typedef union {
    struct {
        uint32 dst;
    };
    uint32 v;
} dmac_ch_dst_t;

typedef union {
    struct {
        uint32 src_bst_len : 4;
        uint32 src_beat_size : 3;
        uint32 src_port_sel : 1;
        uint32 src_bst_type : 1;
        uint32 src_stride_pol : 1;
        uint32 src_protect : 2;
        uint32 src_cache : 4;
        uint32 dst_bst_len : 4;
        uint32 dst_beat_size : 3;
        uint32 dst_port_sel : 1;
        uint32 dst_bst_type : 1;
        uint32 dst_stride_pol : 1;
        uint32 dst_protect : 2;
        uint32 dst_cache : 4;
    };
    uint32 v;
} dmac_ch_tr_ctrl_t;

typedef union {
    struct {
        uint32 buf_size : 24;
        uint32 lop_mode : 2;
        uint32 swt_evt_ctl : 2;
        uint32 src_stride_en : 1;
        uint32 dst_stride_en : 1;
        uint32 buf_mode : 2;
    };
    uint32 v;
} dmac_ch_blk_cfg_t;

typedef union {
    struct {
        uint32 flow_ctrl : 3;
        uint32 rsvd : 1;
        uint32 transfer_mode : 2;
        uint32 mad_crc_mode : 2;
        uint32 data_crc_mode : 2;
        uint32 data_crc_sel : 2;
        uint32 pn_det_mode : 3;
        uint32 ack_assert : 1;
        uint32 first_mad : 1;
        uint32 last_mad : 1;
        uint32 src_stride_sel : 1;
        uint32 src_coarse_stride : 4;
        uint32 dst_stride_sel : 1;
        uint32 dst_coarse_stride : 4;
        uint32 halt_en : 1;
        uint32 mad_intr : 1;
        uint32 trigger_mode : 2;
    };
    uint32 v;
} dmac_ch_op_mod_t;

typedef union {
    struct {
        uint32 opd;
    };
    uint32 v;
} dmac_ch_op_data_t;

typedef union {
    struct {
        uint32 mad_crc;
    };
    uint32 v;
} dmac_ch_mad_crc_t;

typedef union {
    struct {
        uint32 ll_addr;
    };
    struct {
        uint32 link_ch_num : 5;
        uint32 rsvd : 27;
    };
    uint32 v;
} dmac_ch_ll_addr_t;

struct dma_mad {
    volatile dmac_ch_src_t src_addr;
    volatile dmac_ch_dst_t dst_addr;
    volatile dmac_ch_tr_ctrl_t transaction_ctrl;
    volatile dmac_ch_blk_cfg_t block_cfg;
    volatile dmac_ch_op_mod_t operat_mode;
    volatile dmac_ch_op_data_t operat_data;
    volatile dmac_ch_mad_crc_t mad_crc;
    volatile dmac_ch_ll_addr_t link_addr;
};

int clz32(uint32 x)
{
    if (!x) return 32;

    int e = 31;

    if (x & 0xFFFF0000) { e -= 16; x >>= 16; }

    if (x & 0x0000FF00) { e -= 8; x >>= 8; }

    if (x & 0x000000F0) { e -= 4; x >>= 4; }

    if (x & 0x0000000C) { e -= 2; x >>= 2; }

    if (x & 0x00000002) { e -= 1; }

    return e;
}

static uint32 rd_ch_reg(paddr_t dma_base, uint32 chan_id, uint32 reg_off)
{
    return readl(reg_off + DMAC_CH_BASE(dma_base, chan_id));
}

static uint32 rd_ch_reg_bits(paddr_t dma_base, uint32 chan_id,
                             uint32 reg_off, uint32 offset, uint32 size)
{
    return BITS_SHIFT(rd_ch_reg(dma_base, chan_id, reg_off), offset + size,
                      offset);
}

static void wr_ch_reg(paddr_t dma_base, uint32 chan_id, uint32 val,
                      uint32 reg_off)
{
    writel(val, reg_off + DMAC_CH_BASE(dma_base, chan_id));
}

static void wr_ch_reg_bits(paddr_t dma_base, uint32 chan_id, uint32 reg_off,
                           uint32 offset, uint32 size, uint32 val)
{
    uint32 _val = rd_ch_reg(dma_base, chan_id, reg_off);

    _val &= ~(BIT_MASK(size) << offset);
    _val |= (val << offset);

    wr_ch_reg(dma_base, chan_id, _val, reg_off);
}

static uint32 sdrv_dmac_get_buf_sz(enum dma_loop_mode_t lp_mode,
                                   uint32 total, uint32 period)
{
    uint32 buf_sz = 0;
    uint32 lp2_sz = 0;
    uint32 lp1_cnt = 0;
    uint32 lp1_sz = 0;

    switch (lp_mode) {
    case DMA_LOOP_MODE_2:
        lp2_sz = 1u << (31 - clz32(period));
        buf_sz = LP2_TT(total) | LP2_LPSIZE(lp2_sz);
        break;

    case DMA_LOOP_MODE_1:
        lp1_cnt = total / period;
        lp1_cnt -= 1;
        lp1_sz = period - 1;
        buf_sz = lp1_cnt << 12 | lp1_sz;
        break;

    case DMA_LOOP_MODE_0:
        buf_sz = total - 1;
        break;

    default:
        break;
    }

    return buf_sz;
}

uint8 sdrv_dmac_get_ch_pscnt(paddr_t dma_base, uint32 chan)
{
    return rd_ch_reg_bits(dma_base, chan,
                          SDRV_DMAC_CH_PROGRAMM_SEQUENCE_CTRL_REG,
                          SDRV_DMAC_CH_PROG_SEQ_CTRL_PS_CNT_FIELD_OFFSET,
                          SDRV_DMAC_CH_PROG_SEQ_CTRL_PS_CNT_FIELD_SIZE);
}

void sdrv_dmac_set_mad(paddr_t dma_base, uint32 chan_id,
                       sdrv_dmac_lli_node_t *item)
{
    wr_ch_reg(dma_base, chan_id, item->src_addr,
              SDRV_DMAC_CH_SOURCE_ADDRESS_REG);
    wr_ch_reg(dma_base, chan_id, item->dst_addr,
              SDRV_DMAC_CH_DESTINATION_ADDRESS_REG);
    wr_ch_reg(dma_base, chan_id, item->transaction_ctrl,
              SDRV_DMAC_CH_TRANSACTION_CTRL_REG);
    wr_ch_reg(dma_base, chan_id, item->block_cfg,
              SDRV_DMAC_CH_DATA_BLOCK_CONFIG_REG);
    wr_ch_reg(dma_base, chan_id, item->operat_mode,
              SDRV_DMAC_CH_OPERATION_MODE_REG);
    wr_ch_reg(dma_base, chan_id, item->operat_data,
              SDRV_DMAC_CH_OPERATION_DATA_REG);
    wr_ch_reg(dma_base, chan_id, item->mad_crc, SDRV_DMAC_CH_MAD_CRC_REG);
    wr_ch_reg(dma_base, chan_id, item->link_addr,
              SDRV_DMAC_CH_LINK_ADDRESS_REG);
}
void sdrv_dmac_format_mad(sdrv_dmac_ll_cfg_t *cfg, sdrv_dmac_lli_node_t *item,
                          dma_crc_mode_e mad_crc_mode)
{
    dmac_mad_t *mad = (dmac_mad_t *)item;
    dmac_ch_tr_ctrl_t transaction_ctrl;
    dmac_ch_blk_cfg_t block_cfg;
    dmac_ch_op_mod_t operat_mode;

    transaction_ctrl.v = 0;
    transaction_ctrl.src_bst_len = DMA_BURST_LEN_16;
    transaction_ctrl.src_beat_size = cfg->src_bz;
    transaction_ctrl.src_port_sel = cfg->src_port_sel;
    transaction_ctrl.src_bst_type = cfg->src_bt;
    transaction_ctrl.src_stride_pol = 0;
    transaction_ctrl.src_protect = 0;
    transaction_ctrl.src_cache = cfg->src_cache;
    transaction_ctrl.dst_bst_len = DMA_BURST_LEN_16;
    transaction_ctrl.dst_beat_size = cfg->dst_bz;
    transaction_ctrl.dst_port_sel = cfg->dst_port_sel;
    transaction_ctrl.dst_bst_type = cfg->dst_bt;
    transaction_ctrl.dst_stride_pol = 0;
    transaction_ctrl.dst_protect = 0;
    transaction_ctrl.dst_cache = cfg->dst_cache;

    block_cfg.v = 0;

    if (cfg->flow_ctrl == DMA_DIR_MEM2DEV) {
        block_cfg.buf_size =
            sdrv_dmac_get_buf_sz((enum dma_loop_mode_t)cfg->lop_mode, cfg->buf_size, cfg->dst_bl);
    } else if (cfg->flow_ctrl == DMA_DIR_DEV2MEM) {
        block_cfg.buf_size =
            sdrv_dmac_get_buf_sz((enum dma_loop_mode_t)cfg->lop_mode, cfg->buf_size, cfg->src_bl);
    } else if (cfg->flow_ctrl == DMA_DIR_MEM2MEM ||
               cfg->flow_ctrl == DMA_DIR_REG2MEM) {
        block_cfg.buf_size =
            sdrv_dmac_get_buf_sz((enum dma_loop_mode_t)cfg->lop_mode, cfg->buf_size, cfg->buf_size);
    }

    block_cfg.lop_mode = cfg->lop_mode;
    block_cfg.swt_evt_ctl = DMA_SWT_EVT_CTL_CONTINUE_WTH_INT;
    block_cfg.src_stride_en = 0;
    block_cfg.dst_stride_en = 0;
    block_cfg.buf_mode = cfg->buffer_mode;

    operat_mode.v = 0;
    operat_mode.flow_ctrl = cfg->flow_ctrl;
    operat_mode.transfer_mode = cfg->transfer_mode;
    operat_mode.first_mad = cfg->first_mad;
    operat_mode.last_mad = cfg->last_mad;
    operat_mode.mad_intr = 1;
    operat_mode.trigger_mode = cfg->lli_trig_mode;
    operat_mode.mad_crc_mode = mad_crc_mode;

    mad->transaction_ctrl.v = transaction_ctrl.v;
    mad->block_cfg.v = block_cfg.v;
    mad->operat_mode.v = operat_mode.v;
    mad->operat_data.v = 0;
    mad->mad_crc.v = 0;
}
uint8 sdrv_dmac_get_ch_lastmad_done(paddr_t dma_base, uint32 chan_id)
{
    uint32 chan_int_sta = 0;

    chan_int_sta = sdrv_dmac_get_int_state(dma_base, chan_id);

    if (chan_int_sta &
        (1 << SDRV_DMAC_CH_INT_STAT_LST_MAD_DONE_INT_STAT_FIELD_OFFSET)) {
        /* 14
                                                                            */
        return 1;
    }

    return 0;
}

uint32 sdrv_dmac_set_ch_cmd(paddr_t dma_base, uint32 chan_id,
                            ch_ctl_stat_t cmd)
{
    uint32 ret = 0;

    switch (cmd) {
    case DMA_CH_CTL_STAT_STOP:
        wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                       SDRV_DMAC_CH_CFG_STOP_FIELD_OFFSET,
                       SDRV_DMAC_CH_CFG_STOP_FIELD_SIZE, 1);
        ret = rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                             SDRV_DMAC_CH_CFG_STOP_FIELD_OFFSET,
                             SDRV_DMAC_CH_CFG_STOP_FIELD_SIZE);

        while (ret) {
            ret =
                rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                               SDRV_DMAC_CH_CFG_STOP_FIELD_OFFSET,
                               SDRV_DMAC_CH_CFG_STOP_FIELD_SIZE);
        }

        break;

    case DMA_CH_CTL_STAT_FLUSH:
        wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                       SDRV_DMAC_CH_CFG_FLUSH_FIELD_OFFSET,
                       SDRV_DMAC_CH_CFG_FLUSH_FIELD_SIZE, 1);
        ret = rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                             SDRV_DMAC_CH_CFG_FLUSH_FIELD_OFFSET,
                             SDRV_DMAC_CH_CFG_FLUSH_FIELD_SIZE);

        break;

    case DMA_CH_CTL_STAT_REQ_FLUSH:
        wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                       SDRV_DMAC_CH_CFG_REQUEST_FLUSH_FIELD_OFFSET,
                       SDRV_DMAC_CH_CFG_REQUEST_FLUSH_FIELD_SIZE, 1);
        ret = rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                             SDRV_DMAC_CH_CFG_REQUEST_FLUSH_FIELD_OFFSET,
                             SDRV_DMAC_CH_CFG_REQUEST_FLUSH_FIELD_SIZE);
        break;

    case DMA_CH_CTL_STAT_HALT:
        wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                       SDRV_DMAC_CH_CFG_HALT_FIELD_OFFSET,
                       SDRV_DMAC_CH_CFG_HALT_FIELD_SIZE, 1);
        ret = rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                             SDRV_DMAC_CH_CFG_HALT_FIELD_OFFSET,
                             SDRV_DMAC_CH_CFG_HALT_FIELD_SIZE);
        break;

    case DMA_CH_CTL_STAT_RESUME:
        wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                       SDRV_DMAC_CH_CFG_RESUME_FIELD_OFFSET,
                       SDRV_DMAC_CH_CFG_RESUME_FIELD_SIZE, 1);
        ret = rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                             SDRV_DMAC_CH_CFG_RESUME_FIELD_OFFSET,
                             SDRV_DMAC_CH_CFG_RESUME_FIELD_SIZE);
        break;

    case DMA_CH_CTL_STAT_ABORT:
        wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                       SDRV_DMAC_CH_CFG_ABORT_FIELD_OFFSET,
                       SDRV_DMAC_CH_CFG_ABORT_FIELD_SIZE, 1);
        ret = rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                             SDRV_DMAC_CH_CFG_ABORT_FIELD_OFFSET,
                             SDRV_DMAC_CH_CFG_ABORT_FIELD_SIZE);
        break;

    default:
        break;
    }

    return ret;
}

uint32 sdrv_dmac_get_ch_en(paddr_t dma_base, uint32 chan_id)
{
    return rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                          SDRV_DMAC_CH_CFG_EN_FIELD_OFFSET,
                          SDRV_DMAC_CH_CFG_EN_FIELD_SIZE);
}

sint32 sdrv_dmac_enable_ch(paddr_t dma_base, uint32 chan, uint8 ps_cnt)
{
    wr_ch_reg_bits(dma_base, chan, SDRV_DMAC_CH_PROGRAMM_SEQUENCE_CTRL_REG,
                   SDRV_DMAC_CH_PROG_SEQ_CTRL_PS_CNT_FIELD_OFFSET,
                   SDRV_DMAC_CH_PROG_SEQ_CTRL_PS_CNT_FIELD_SIZE, ps_cnt + 1);
    wr_ch_reg_bits(dma_base, chan, SDRV_DMAC_CHANNEL_CONFIG_REG,
                   SDRV_DMAC_CH_CFG_EN_FIELD_OFFSET,
                   SDRV_DMAC_CH_CFG_EN_FIELD_SIZE, 1);
    return 1;
}

sint32 sdrv_dmac_disable_ch(paddr_t dma_base, uint32 chan)
{
    sint32 ret = -1;

    wr_ch_reg_bits(dma_base, chan, SDRV_DMAC_CHANNEL_CONFIG_REG,
                   SDRV_DMAC_CH_CFG_EN_FIELD_OFFSET,
                   SDRV_DMAC_CH_CFG_EN_FIELD_SIZE, 0);
    ret = rd_ch_reg_bits(dma_base, chan, SDRV_DMAC_CHANNEL_CONFIG_REG,
                         SDRV_DMAC_CH_CFG_EN_FIELD_OFFSET,
                         SDRV_DMAC_CH_CFG_EN_FIELD_SIZE);
    return ret;
}

void sdrv_dmac_set_ch_sw_handshake(paddr_t dma_base, uint32 chan_id)
{
    uint32 val = 0;
    sint32 limit = 5;

    while (limit--) {
        val = rd_ch_reg(dma_base, chan_id, SDRV_DMAC_CH_SOFTWARE_HANDSHAKE_REG);

        if (val == 0)
            break;
    }

    wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CH_SOFTWARE_HANDSHAKE_REG,
                   SDRV_DMAC_CH_SW_HS_REQ_FIELD_OFFSET,
                   SDRV_DMAC_CH_SW_HS_REQ_FIELD_SIZE, 1);
}

void sdrv_dmac_clr_mem2mem_ch_sw_handshake(paddr_t dma_base, uint32 chan_id)
{
    uint32 loop_time = 1000;

    /* 1000 : Set the upper times limit of a while loop */
    while (loop_time--) {
        uint32 ch_ctrl_fsm =
            rd_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CH_STATUS_REG,
                           SDRV_DMAC_CH_STAT_CH_CTRL_FSM_FIELD_OFFSET,
                           SDRV_DMAC_CH_STAT_CH_CTRL_FSM_FIELD_SIZE);

        if (3 == (ch_ctrl_fsm & 0xf)) {
            wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CH_SOFTWARE_HANDSHAKE_REG,
                           SDRV_DMAC_CH_SW_HS_REQ_FIELD_OFFSET,
                           SDRV_DMAC_CH_SW_HS_REQ_FIELD_SIZE, 0);
            break;
        }
    }
}

uint32 sdrv_dmac_get_int_state(paddr_t dma_base, uint32 chan_id)
{
    return rd_ch_reg(dma_base, chan_id, SDRV_DMAC_CH_INTERRUPT_STATUS_REG);
}

void sdrv_dmac_clr_int(paddr_t dma_base, uint32 chan_id, uint32 status)
{
    wr_ch_reg(dma_base, chan_id, status, SDRV_DMAC_CH_INTERRUPT_CLEAR_REG);
}

uint32 sdrv_dmac_irq_status_handle(uint32 status)
{
    dma_status_e chan_status = DMA_PENDING;

    if (status &
        (1 << SDRV_DMAC_CH_INT_STAT_LST_MAD_DONE_INT_STAT_FIELD_OFFSET)) {
        /* 14
                                                                            */
        chan_status = DMA_COMPLETED;
    }

    if (status &
        (1
         << SDRV_DMAC_CH_INT_STAT_EVRY_MAD_DONE_INT_STAT_FIELD_OFFSET)) {
        /* 15
                                                                          */
        chan_status = DMA_COMPLETED;
    }

    if (status &
        (1 << SDRV_DMAC_CH_INT_STAT_CH_HALT_INT_STAT_FIELD_OFFSET)) {
        /* 19
                                                                       */
        chan_status = DMA_PAUSED;
    }

    /* Add MAD_CRC_ERR_INT_STATUS processing logic */
    if (status & (1 << SDRV_DMAC_CH_INT_STAT_MAD_CRC_ERR_INT_STAT_FIELD_OFFSET)) { /* 9 */
        chan_status = DMA_MAD_CRC_ERROR;
    } else {
        /* Do Nothing */
    }

    return chan_status;
}

void sdrv_dmac_set_int_state(paddr_t dma_base, uint32 chan_id, uint32 type)
{
    wr_ch_reg(dma_base, chan_id, type, SDRV_DMAC_CH_INTERRUPT_ENABLE_REG);
}

void sdrv_dmac_set_ch_muxid(paddr_t dma_base, uint32 chan_id, uint32 mux_id)
{
    wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CH_PORT_CONFIG_REG,
                   SDRV_DMAC_CH_PORT_CFG_CSEL_FIELD_OFFSET,
                   SDRV_DMAC_CH_PORT_CFG_CSEL_FIELD_SIZE, mux_id);
}

void sdrv_dmac_set_ch_rd_outstanding(paddr_t dma_base, uint32 chan_id,
                                     uint8 value)
{
    wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CH_PORT_CONFIG_REG,
                   SDRV_DMAC_CH_PORT_CFG_ROT_FIELD_OFFSET,
                   SDRV_DMAC_CH_PORT_CFG_ROT_FIELD_SIZE, (value & 0xf));
}

void sdrv_dmac_set_ch_wr_outstanding(paddr_t dma_base, uint32 chan_id,
                                     uint8 value)
{
    wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CH_PORT_CONFIG_REG,
                   SDRV_DMAC_CH_PORT_CFG_WOT_FIELD_OFFSET,
                   SDRV_DMAC_CH_PORT_CFG_WOT_FIELD_SIZE, (value & 0xf));
}

uint32 sdrv_dmac_get_xfer_num(paddr_t dma_base, uint32 chan_id, uint8 need_clr)
{
    uint32 num = 0;

    num = rd_ch_reg(dma_base, chan_id, SDRV_DMAC_CH_DATA_TRANSFER_REG);

    if (need_clr)
        wr_ch_reg(dma_base, chan_id, 0x0, SDRV_DMAC_CH_DATA_TRANSFER_REG);

    return num;
}

void sdrv_dmac_set_local_val(paddr_t dma_base, uint32 chan_id, uint32 val)
{
    wr_ch_reg(dma_base, chan_id, val, SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG1);
    wr_ch_reg(dma_base, chan_id, val, SDRV_DMAC_CH_FOR_FLOW_CTRL_SRC_DST_REG2);
}

void sdrv_dmac_clr_abort_sta(paddr_t dma_base, uint32 chan_id)
{
    wr_ch_reg_bits(dma_base, chan_id, SDRV_DMAC_CHANNEL_CONFIG_REG,
                   SDRV_DMAC_CH_CFG_ABORT_FIELD_OFFSET,
                   SDRV_DMAC_CH_CFG_ABORT_FIELD_SIZE, 0);
}

uint32 sdrv_dmac_get_max_block_size(enum dma_loop_mode_t lp_mode)
{
    uint32 max_sz = 0;

    switch (lp_mode) {
    case DMA_LOOP_MODE_0:
        max_sz = LP0_LPSIZE_MAX;
        break;

    case DMA_LOOP_MODE_1:
        max_sz = LP1_LPSIZE_MAX;
        break;

    case DMA_LOOP_MODE_2:
        max_sz = LP2_LPSIZE_MAX;
        break;

    default:
        max_sz = LP_DEFAULT_LPSIZE_MAX;
    }

    return max_sz;
}

void sdrv_dmac_get_local_buf_prop(paddr_t dma_base, dma_local_buf_t *buf_prop)
{
    buf_prop->buf_base = (uint32)(dma_base + DMAC_LOCAL_BUFFER_OFF);
    buf_prop->buf_size = DMAC_LOCAL_BUFFER_MAX_BYTES;
}

void sdrv_dmac_core_reset_irq_sta(paddr_t dma_base)
{
#ifndef SEMIDRIVE_E3_LITE_SERIES
    /* get chip version */
    uint8 chipver = Mcu_GetChipVersion();

    if (chipver == 0x00) {
        /* clear dma uncorr err for 1.0 workaround */
        writel(0xffffffff, dma_base + SDRV_DMAC_CORE_CONT_DMA_INT_CLR_REG);
        writel(0x00000000, dma_base + SDRV_DMAC_CORE_CONT_DMA_INT_CLR_REG);
        writel(0xffffffff, dma_base + SDRV_DMAC_CORE_INT_CLR_REG);
        writel(0x00000000, dma_base + SDRV_DMAC_CORE_INT_CLR_REG);
    }

#endif
}

#ifdef __cplusplus
}
#endif
