/*
* SEMIDRIVE Copyright Statement
* Copyright (c) SEMIDRIVE. All rights reserved
*
* This software and all rights therein are owned by SEMIDRIVE, and are
* protected by copyright law and other relevant laws, regulations and
* protection. Without SEMIDRIVE's prior written consent and/or related rights,
* please do not use this software or any potion thereof in any form or by any
* means. You may not reproduce, modify or distribute this software except in
* compliance with the License. Unless required by applicable law or agreed to
* in writing, software distributed under the License is distributed on
* an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
*
* You should have received a copy of the License along with this program.
* If not, see <http://www.semidrive.com/licenses/>.
*/

/*
* @file Dma_Cfg.h
* @brief AutoSAR DMA configuration header file
* @details Automatically generated by user settings
* @date 2023-09-22 17:02:48
*/

#ifndef DMAAL_CFG_H_INCLUDED
#define DMAAL_CFG_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif
/*----------------------[version identification]-----------------------------*/
#define DMA_GEN_MODULE_ID                       ( 2048U )
#define DMA_GEN_VENDOR_ID                       ( 0x8c )
#define DMA_GEN_AR_RELEASE_MAJOR_VERSION        ( 4U )
#define DMA_GEN_AR_RELEASE_MINOR_VERSION        ( 3U )
#define DMA_GEN_AR_RELEASE_REVISION_VERSION     ( 1U )
#define DMA_GEN_SW_MAJOR_VERSION                ( 1U )
#define DMA_GEN_SW_MINOR_VERSION                ( 0U )
#define DMA_GEN_SW_PATCH_VERSION                ( 0U )

/*
Configuration:
- if STD_ON, DET is Enabled
- if STD_OFF,DET is Disabled
*/
#define DMA_PRECOMPILE_SUPPORT                  (STD_OFF)

/* Enable/Disable dma lockstep mode */
#define DMA_LOCK_STEP_MODE                      (STD_OFF)

/* Enable/Disable dma dynamic channel */
#define DMA_DYNAMIC_CHANNEL                     (STD_OFF)

/* Max dma channel number per instance */
#define DMA_MAX_CHANNEL_NUMBER                  23

/* Total Number of spi HW units configured*/
#define DMA_ADC_MAX_HWUNIT_NUMBER               3U
/* Total Number of icu HW units configured*/
#define DMA_ICU_MAX_HWUNIT_NUMBER               8U
/* Total Number of pwm HW units configured*/
#define DMA_PWM_MAX_HWUNIT_NUMBER               8U
/* Total Number of spi HW units configured*/
#define DMA_SPI_MAX_HWUNIT_NUMBER               8U
/* Total Number of Xspi HW units configured*/
#define DMA_XSPI_MAX_HWUNIT_NUMBER              2U

/* Adc instance number */
#define DMA_ADC_INSTANCE_NUMBER                 0U
/* Icu instance number */
#define DMA_ICU_INSTANCE_NUMBER                 0U
/* Pwm instance number */
#define DMA_PWM_INSTANCE_NUMBER                 0U
/* Spi instance number */
#define DMA_SPI_INSTANCE_NUMBER                 0U
/* Spi instance number */
#define DMA_XSPI_INSTANCE_NUMBER                1U



#define DMA_CHANNEL_SF0_ON_SF_NUMBER            0U

#define DMA_CHANNEL_SF1_ON_SF_NUMBER            0U

#define DMA_CHANNEL_AP0_ON_SF_NUMBER            0U

#define DMA_CHANNEL_SF0_ON_SX0_NUMBER           0U

#define DMA_CHANNEL_SF1_ON_SX0_NUMBER           0U

#define DMA_CHANNEL_AP0_ON_SX0_NUMBER           0U

#define DMA_CHANNEL_SF0_ON_SX1_NUMBER           0U

#define DMA_CHANNEL_SF1_ON_SX1_NUMBER           0U

#define DMA_CHANNEL_AP0_ON_SX1_NUMBER           0U

#define DMA_CHANNEL_SF0_ON_SP0_NUMBER           0U

#define DMA_CHANNEL_SF1_ON_SP0_NUMBER           0U

#define DMA_CHANNEL_AP0_ON_SP0_NUMBER           0U

#define DMA_CHANNEL_SF0_ON_SP1_NUMBER           0U

#define DMA_CHANNEL_SF1_ON_SP1_NUMBER           0U

#define DMA_CHANNEL_AP0_ON_SP1_NUMBER           0U

#ifdef __cplusplus
}
#endif
#endif /*!defined(DMA_CFG_H_INCLUDED)*/
