/*
* SEMIDRIVE Copyright Statement
* Copyright (c) SEMIDRIVE. All rights reserved
*
* This software and all rights therein are owned by SEMIDRIVE, and are
* protected by copyright law and other relevant laws, regulations and
* protection. Without SEMIDRIVE's prior written consent and/or related rights,
* please do not use this software or any potion thereof in any form or by any
* means. You may not reproduce, modify or distribute this software except in
* compliance with the License. Unless required by applicable law or agreed to
* in writing, software distributed under the License is distributed on
* an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
*
* You should have received a copy of the License along with this program.
* If not, see <http://www.semidrive.com/licenses/>.
*/

/*
* @file Fls_Cfg.h
* @brief AutoSAR Fls configuration header file
* @details Automatically generated by user settings
* @date 2023-09-22 17:02:48
*/

#ifndef FLS_CFG_H
#define FLS_CFG_H

#ifdef __cplusplus
extern "C" {
#endif



#define CHIP_ID_E3420
#define E3xxx_TAISHAN
#define XSPI_RESOURE_NUM (2)

#define MAX_NUMBER_OF_CONTROLLER (XSPI_RESOURE_NUM * 2)

#define FLS_DEV_ERROR_DETECT (STD_ON)   /* development error detection */

#define FLS_DEM_ERROR_DETECT (STD_OFF)    /* public error detection */

#define FLS_VERSION_INFO_API    (STD_ON)
#define FLS_CANCEL_API          (STD_OFF)
#define FLS_GET_STATUS_API      (STD_ON)
#define FLS_GET_JOB_RESULT_API  (STD_ON)
#define FLS_COMPARE_API         (STD_ON)
#define FLS_SET_MODE_API        (STD_ON)
#define FLS_BLANK_CHECK_API     (STD_ON)

#define FLS_TIMEOUT_SUPERVISION_ENABLED (STD_OFF)
#define FLS_ERASE_VERIFICATION_ENABLED  (STD_OFF)
#define FLS_WRITE_VERIFICATION_ENABLED  (STD_ON)

#define FLS_ADDRESS_ALIGNED_CHECK_ENABLED  (STD_OFF)

#define FLS_INSTANCE  0x0U 

#define FLS_BASE_ADDRESS 0U

//FlsPublishedInformation
#define FLS_AC_LOCATION_ERASE 0x0
#define FLS_AC_LOCATION_WRITE 0x0
#define FLS_AC_SIZE_ERASE 0x128U
#define FLS_AC_SIZE_WRITE 0x128U
#define FLS_ERASED_VALUE  0x128U
#define FLS_ERASE_TIME 0x10000U
#define FLS_EXPECTED_HW_ID 0
#define FLS_SPECIFIED_ERASE_CYCLES 0x10000U
#define FLS_WRITE_TIME 0x10000U
#define FLS_USE_INTERRUPTS  (STD_OFF)

typedef struct {
    void (*FlsJobEndNotification)(void);
    void (*FlsJobErrorNotification)(void);
} Fls_ProgramDescriptorType;

#ifdef __cplusplus
}
#endif
#endif /* #define FLS_CFG_H */
