/*
 * SEMIDRIVE Copyright Statement
 * Copyright (c) SEMIDRIVE. All rights reserved
 *
 * This software and all rights therein are owned by SEMIDRIVE, and are
 * protected by copyright law and other relevant laws, regulations and
 * protection. Without SEMIDRIVE's prior written consent and/or related rights,
 * please do not use this software or any potion thereof in any form or by any
 * means. You may not reproduce, modify or distribute this software except in
 * compliance with the License. Unless required by applicable law or agreed to
 * in writing, software distributed under the License is distributed on
 * an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 * You should have received a copy of the License along with this program.
 * If not, see <http://www.semidrive.com/licenses/>.
 */

/**
 * @file  ioc_reg_e3.h
 * @brief Semidrive. AUTOSAR 4.3.1 MCAL Lin
 */

/* Generated by tool. Do not modify manually. */

#ifndef IOC_TYPES_E3_H
#define IOC_TYPES_E3_H

#include "Std_Types.h"

//global variable
typedef enum {
    lpf_mode = 0,
    exp_mode = 1,
    der_mode = 2,
    byp_mode = 3,
} filter_Type;

typedef enum {
    edge  = 0,
    level = 1,
} edge_Mode;

typedef enum {
    pos_edge = 0,
    neg_edge = 1,
    pos_neg_edge = 2,
} det_Edge;

typedef enum {
    high_level = 0,
    low_level  = 1,
} det_Level;

typedef struct Ioc_cfg {
    filter_Type filter_type_pos;
    filter_Type filter_type_neg;
    edge_Mode edge_mode; 
    det_Edge det_edge_inc; 
    det_Edge det_edge_dec;
    det_Edge det_edge_default;
    det_Level det_level; 
    det_Level det_level_low;
    det_Level det_pdt;
    uint8    diff_cnt;
    uint8    pdt_thr;
    uint8    diff_cnt_fusa;
    uint8    sig_det_mode;
}ioc_cfg;


#endif /* IOC_TYPES_E3_H */
